/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 5.2 */
/* Thu Jan 10 00:57:12 2013 */

/* parameterized module instance */
pll __ (.CLK( ), .CLKOP( ), .LOCK( ));
