/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 4.9 */
/* Mon Jul 08 10:04:32 2013 */

/* parameterized module instance */
fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .Empty( ), .Full( ));
