/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.4 */
/* Fri Dec 27 22:05:04 2013 */

/* parameterized module instance */
clk100_125 __ (.CLK( ), .CLKOP( ), .LOCK( ));
