/* Verilog netlist generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 7.1 */
/* /usr/local/diamond/1.4/ispfpga/bin/lin/scuba -w -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type bram -wp 11 -rp 1010 -data_width 16 -rdata_width 16 -num_rows 4096 -byte 8 -outdataA REGISTERED -outdataB REGISTERED -writemodeA NORMAL -writemodeB NORMAL -cascade -1 -e  */
/* Tue Jan  8 23:31:49 2013 */


`timescale 1 ns / 1 ps
module ram_dp_true (DataInA, DataInB, ByteEnA, ByteEnB, AddressA, 
    AddressB, ClockA, ClockB, ClockEnA, ClockEnB, WrA, WrB, ResetA, 
    ResetB, QA, QB);
    input wire [15:0] DataInA;
    input wire [15:0] DataInB;
    input wire [1:0] ByteEnA;
    input wire [1:0] ByteEnB;
    input wire [11:0] AddressA;
    input wire [11:0] AddressB;
    input wire ClockA;
    input wire ClockB;
    input wire ClockEnA;
    input wire ClockEnB;
    input wire WrA;
    input wire WrB;
    input wire ResetA;
    input wire ResetB;
    output wire [15:0] QA;
    output wire [15:0] QB;

    wire scuba_vhi;
    wire wren0_inv;
    wire wren1_inv;
    wire mdout1_0_17;
    wire mdout0_0_17;
    wire mdout1_0_8;
    wire mdout0_0_8;
    wire mdout1_1_17;
    wire mdout0_1_17;
    wire mdout1_1_8;
    wire mdout0_1_8;
    wire mdout1_2_17;
    wire mdout0_2_17;
    wire mdout1_2_8;
    wire mdout0_2_8;
    wire mdout1_3_17;
    wire mdout0_3_17;
    wire mdout1_3_8;
    wire mdout0_3_8;
    wire wren0_inv_g;
    wire addr010_ff;
    wire addr011_ff;
    wire wren1_inv_g;
    wire addr110_ff;
    wire scuba_vlo;
    wire addr111_ff;
    wire mdout0_3_0;
    wire mdout0_2_0;
    wire mdout0_1_0;
    wire mdout0_0_0;
    wire mdout0_3_1;
    wire mdout0_2_1;
    wire mdout0_1_1;
    wire mdout0_0_1;
    wire mdout0_3_2;
    wire mdout0_2_2;
    wire mdout0_1_2;
    wire mdout0_0_2;
    wire mdout0_3_3;
    wire mdout0_2_3;
    wire mdout0_1_3;
    wire mdout0_0_3;
    wire mdout0_3_4;
    wire mdout0_2_4;
    wire mdout0_1_4;
    wire mdout0_0_4;
    wire mdout0_3_5;
    wire mdout0_2_5;
    wire mdout0_1_5;
    wire mdout0_0_5;
    wire mdout0_3_6;
    wire mdout0_2_6;
    wire mdout0_1_6;
    wire mdout0_0_6;
    wire mdout0_3_7;
    wire mdout0_2_7;
    wire mdout0_1_7;
    wire mdout0_0_7;
    wire mdout0_3_9;
    wire mdout0_2_9;
    wire mdout0_1_9;
    wire mdout0_0_9;
    wire mdout0_3_10;
    wire mdout0_2_10;
    wire mdout0_1_10;
    wire mdout0_0_10;
    wire mdout0_3_11;
    wire mdout0_2_11;
    wire mdout0_1_11;
    wire mdout0_0_11;
    wire mdout0_3_12;
    wire mdout0_2_12;
    wire mdout0_1_12;
    wire mdout0_0_12;
    wire mdout0_3_13;
    wire mdout0_2_13;
    wire mdout0_1_13;
    wire mdout0_0_13;
    wire mdout0_3_14;
    wire mdout0_2_14;
    wire mdout0_1_14;
    wire mdout0_0_14;
    wire mdout0_3_15;
    wire mdout0_2_15;
    wire mdout0_1_15;
    wire mdout0_0_15;
    wire addr011_ff2;
    wire addr010_ff2;
    wire mdout0_3_16;
    wire mdout0_2_16;
    wire mdout0_1_16;
    wire mdout0_0_16;
    wire mdout1_3_0;
    wire mdout1_2_0;
    wire mdout1_1_0;
    wire mdout1_0_0;
    wire mdout1_3_1;
    wire mdout1_2_1;
    wire mdout1_1_1;
    wire mdout1_0_1;
    wire mdout1_3_2;
    wire mdout1_2_2;
    wire mdout1_1_2;
    wire mdout1_0_2;
    wire mdout1_3_3;
    wire mdout1_2_3;
    wire mdout1_1_3;
    wire mdout1_0_3;
    wire mdout1_3_4;
    wire mdout1_2_4;
    wire mdout1_1_4;
    wire mdout1_0_4;
    wire mdout1_3_5;
    wire mdout1_2_5;
    wire mdout1_1_5;
    wire mdout1_0_5;
    wire mdout1_3_6;
    wire mdout1_2_6;
    wire mdout1_1_6;
    wire mdout1_0_6;
    wire mdout1_3_7;
    wire mdout1_2_7;
    wire mdout1_1_7;
    wire mdout1_0_7;
    wire mdout1_3_9;
    wire mdout1_2_9;
    wire mdout1_1_9;
    wire mdout1_0_9;
    wire mdout1_3_10;
    wire mdout1_2_10;
    wire mdout1_1_10;
    wire mdout1_0_10;
    wire mdout1_3_11;
    wire mdout1_2_11;
    wire mdout1_1_11;
    wire mdout1_0_11;
    wire mdout1_3_12;
    wire mdout1_2_12;
    wire mdout1_1_12;
    wire mdout1_0_12;
    wire mdout1_3_13;
    wire mdout1_2_13;
    wire mdout1_1_13;
    wire mdout1_0_13;
    wire mdout1_3_14;
    wire mdout1_2_14;
    wire mdout1_1_14;
    wire mdout1_0_14;
    wire mdout1_3_15;
    wire mdout1_2_15;
    wire mdout1_1_15;
    wire mdout1_0_15;
    wire addr111_ff2;
    wire addr110_ff2;
    wire mdout1_3_16;
    wire mdout1_2_16;
    wire mdout1_1_16;
    wire mdout1_0_16;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    INV INV_1 (.A(WrA), .Z(wren0_inv));

    AND2 AND2_t1 (.A(wren0_inv), .B(ClockEnA), .Z(wren0_inv_g));

    INV INV_0 (.A(WrB), .Z(wren1_inv));

    AND2 AND2_t0 (.A(wren1_inv), .B(ClockEnB), .Z(wren1_inv_g));

    defparam ram_dp_true_0_0_3.CSDECODE_B = "0b000" ;
    defparam ram_dp_true_0_0_3.CSDECODE_A = "0b000" ;
    defparam ram_dp_true_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_0_0_3.GSR = "DISABLED" ;
    defparam ram_dp_true_0_0_3.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_0_0_3.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_0_0_3.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_0_0_3.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_0_0_3 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(AddressA[11]), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(AddressB[11]), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_0_0), .DOA1(mdout0_0_1), .DOA2(mdout0_0_2), 
        .DOA3(mdout0_0_3), .DOA4(mdout0_0_4), .DOA5(mdout0_0_5), .DOA6(mdout0_0_6), 
        .DOA7(mdout0_0_7), .DOA8(mdout0_0_8), .DOA9(mdout0_0_9), .DOA10(mdout0_0_10), 
        .DOA11(mdout0_0_11), .DOA12(mdout0_0_12), .DOA13(mdout0_0_13), .DOA14(mdout0_0_14), 
        .DOA15(mdout0_0_15), .DOA16(mdout0_0_16), .DOA17(mdout0_0_17), .DOB0(mdout1_0_0), 
        .DOB1(mdout1_0_1), .DOB2(mdout1_0_2), .DOB3(mdout1_0_3), .DOB4(mdout1_0_4), 
        .DOB5(mdout1_0_5), .DOB6(mdout1_0_6), .DOB7(mdout1_0_7), .DOB8(mdout1_0_8), 
        .DOB9(mdout1_0_9), .DOB10(mdout1_0_10), .DOB11(mdout1_0_11), .DOB12(mdout1_0_12), 
        .DOB13(mdout1_0_13), .DOB14(mdout1_0_14), .DOB15(mdout1_0_15), .DOB16(mdout1_0_16), 
        .DOB17(mdout1_0_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_1_0_2.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_1_0_2.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_1_0_2.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_1_0_2.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_1_0_2.GSR = "DISABLED" ;
    defparam ram_dp_true_1_0_2.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_1_0_2.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_1_0_2.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_1_0_2.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_1_0_2 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(AddressA[11]), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(AddressB[11]), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_1_0), .DOA1(mdout0_1_1), .DOA2(mdout0_1_2), 
        .DOA3(mdout0_1_3), .DOA4(mdout0_1_4), .DOA5(mdout0_1_5), .DOA6(mdout0_1_6), 
        .DOA7(mdout0_1_7), .DOA8(mdout0_1_8), .DOA9(mdout0_1_9), .DOA10(mdout0_1_10), 
        .DOA11(mdout0_1_11), .DOA12(mdout0_1_12), .DOA13(mdout0_1_13), .DOA14(mdout0_1_14), 
        .DOA15(mdout0_1_15), .DOA16(mdout0_1_16), .DOA17(mdout0_1_17), .DOB0(mdout1_1_0), 
        .DOB1(mdout1_1_1), .DOB2(mdout1_1_2), .DOB3(mdout1_1_3), .DOB4(mdout1_1_4), 
        .DOB5(mdout1_1_5), .DOB6(mdout1_1_6), .DOB7(mdout1_1_7), .DOB8(mdout1_1_8), 
        .DOB9(mdout1_1_9), .DOB10(mdout1_1_10), .DOB11(mdout1_1_11), .DOB12(mdout1_1_12), 
        .DOB13(mdout1_1_13), .DOB14(mdout1_1_14), .DOB15(mdout1_1_15), .DOB16(mdout1_1_16), 
        .DOB17(mdout1_1_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_2_0_1.CSDECODE_B = "0b010" ;
    defparam ram_dp_true_2_0_1.CSDECODE_A = "0b010" ;
    defparam ram_dp_true_2_0_1.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_2_0_1.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_2_0_1.GSR = "DISABLED" ;
    defparam ram_dp_true_2_0_1.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_2_0_1.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_2_0_1.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_2_0_1.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_2_0_1 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(AddressA[11]), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(AddressB[11]), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_2_0), .DOA1(mdout0_2_1), .DOA2(mdout0_2_2), 
        .DOA3(mdout0_2_3), .DOA4(mdout0_2_4), .DOA5(mdout0_2_5), .DOA6(mdout0_2_6), 
        .DOA7(mdout0_2_7), .DOA8(mdout0_2_8), .DOA9(mdout0_2_9), .DOA10(mdout0_2_10), 
        .DOA11(mdout0_2_11), .DOA12(mdout0_2_12), .DOA13(mdout0_2_13), .DOA14(mdout0_2_14), 
        .DOA15(mdout0_2_15), .DOA16(mdout0_2_16), .DOA17(mdout0_2_17), .DOB0(mdout1_2_0), 
        .DOB1(mdout1_2_1), .DOB2(mdout1_2_2), .DOB3(mdout1_2_3), .DOB4(mdout1_2_4), 
        .DOB5(mdout1_2_5), .DOB6(mdout1_2_6), .DOB7(mdout1_2_7), .DOB8(mdout1_2_8), 
        .DOB9(mdout1_2_9), .DOB10(mdout1_2_10), .DOB11(mdout1_2_11), .DOB12(mdout1_2_12), 
        .DOB13(mdout1_2_13), .DOB14(mdout1_2_14), .DOB15(mdout1_2_15), .DOB16(mdout1_2_16), 
        .DOB17(mdout1_2_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_3_0_0.CSDECODE_B = "0b011" ;
    defparam ram_dp_true_3_0_0.CSDECODE_A = "0b011" ;
    defparam ram_dp_true_3_0_0.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_3_0_0.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_3_0_0.GSR = "DISABLED" ;
    defparam ram_dp_true_3_0_0.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_3_0_0.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_3_0_0.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_3_0_0.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_3_0_0 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(AddressA[11]), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(AddressB[11]), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_3_0), .DOA1(mdout0_3_1), .DOA2(mdout0_3_2), 
        .DOA3(mdout0_3_3), .DOA4(mdout0_3_4), .DOA5(mdout0_3_5), .DOA6(mdout0_3_6), 
        .DOA7(mdout0_3_7), .DOA8(mdout0_3_8), .DOA9(mdout0_3_9), .DOA10(mdout0_3_10), 
        .DOA11(mdout0_3_11), .DOA12(mdout0_3_12), .DOA13(mdout0_3_13), .DOA14(mdout0_3_14), 
        .DOA15(mdout0_3_15), .DOA16(mdout0_3_16), .DOA17(mdout0_3_17), .DOB0(mdout1_3_0), 
        .DOB1(mdout1_3_1), .DOB2(mdout1_3_2), .DOB3(mdout1_3_3), .DOB4(mdout1_3_4), 
        .DOB5(mdout1_3_5), .DOB6(mdout1_3_6), .DOB7(mdout1_3_7), .DOB8(mdout1_3_8), 
        .DOB9(mdout1_3_9), .DOB10(mdout1_3_10), .DOB11(mdout1_3_11), .DOB12(mdout1_3_12), 
        .DOB13(mdout1_3_13), .DOB14(mdout1_3_14), .DOB15(mdout1_3_15), .DOB16(mdout1_3_16), 
        .DOB17(mdout1_3_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    FD1P3DX FF_7 (.D(AddressA[10]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr010_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(AddressA[11]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr011_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(addr010_ff), .SP(ClockEnA), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr010_ff2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(addr011_ff), .SP(ClockEnA), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr011_ff2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(AddressB[10]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr110_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(AddressB[11]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr111_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(addr110_ff), .SP(ClockEnB), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr110_ff2))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FD1P3DX FF_0 (.D(addr111_ff), .SP(ClockEnB), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr111_ff2))
             /* synthesis GSR="ENABLED" */;

    MUX41 mux_31 (.D0(mdout0_0_0), .D1(mdout0_1_0), .D2(mdout0_2_0), .D3(mdout0_3_0), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[0]));

    MUX41 mux_30 (.D0(mdout0_0_1), .D1(mdout0_1_1), .D2(mdout0_2_1), .D3(mdout0_3_1), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[1]));

    MUX41 mux_29 (.D0(mdout0_0_2), .D1(mdout0_1_2), .D2(mdout0_2_2), .D3(mdout0_3_2), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[2]));

    MUX41 mux_28 (.D0(mdout0_0_3), .D1(mdout0_1_3), .D2(mdout0_2_3), .D3(mdout0_3_3), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[3]));

    MUX41 mux_27 (.D0(mdout0_0_4), .D1(mdout0_1_4), .D2(mdout0_2_4), .D3(mdout0_3_4), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[4]));

    MUX41 mux_26 (.D0(mdout0_0_5), .D1(mdout0_1_5), .D2(mdout0_2_5), .D3(mdout0_3_5), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[5]));

    MUX41 mux_25 (.D0(mdout0_0_6), .D1(mdout0_1_6), .D2(mdout0_2_6), .D3(mdout0_3_6), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[6]));

    MUX41 mux_24 (.D0(mdout0_0_7), .D1(mdout0_1_7), .D2(mdout0_2_7), .D3(mdout0_3_7), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[7]));

    MUX41 mux_23 (.D0(mdout0_0_9), .D1(mdout0_1_9), .D2(mdout0_2_9), .D3(mdout0_3_9), 
        .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[8]));

    MUX41 mux_22 (.D0(mdout0_0_10), .D1(mdout0_1_10), .D2(mdout0_2_10), 
        .D3(mdout0_3_10), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[9]));

    MUX41 mux_21 (.D0(mdout0_0_11), .D1(mdout0_1_11), .D2(mdout0_2_11), 
        .D3(mdout0_3_11), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[10]));

    MUX41 mux_20 (.D0(mdout0_0_12), .D1(mdout0_1_12), .D2(mdout0_2_12), 
        .D3(mdout0_3_12), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[11]));

    MUX41 mux_19 (.D0(mdout0_0_13), .D1(mdout0_1_13), .D2(mdout0_2_13), 
        .D3(mdout0_3_13), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[12]));

    MUX41 mux_18 (.D0(mdout0_0_14), .D1(mdout0_1_14), .D2(mdout0_2_14), 
        .D3(mdout0_3_14), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[13]));

    MUX41 mux_17 (.D0(mdout0_0_15), .D1(mdout0_1_15), .D2(mdout0_2_15), 
        .D3(mdout0_3_15), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[14]));

    MUX41 mux_16 (.D0(mdout0_0_16), .D1(mdout0_1_16), .D2(mdout0_2_16), 
        .D3(mdout0_3_16), .SD1(addr010_ff2), .SD2(addr011_ff2), .Z(QA[15]));

    MUX41 mux_15 (.D0(mdout1_0_0), .D1(mdout1_1_0), .D2(mdout1_2_0), .D3(mdout1_3_0), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[0]));

    MUX41 mux_14 (.D0(mdout1_0_1), .D1(mdout1_1_1), .D2(mdout1_2_1), .D3(mdout1_3_1), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[1]));

    MUX41 mux_13 (.D0(mdout1_0_2), .D1(mdout1_1_2), .D2(mdout1_2_2), .D3(mdout1_3_2), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[2]));

    MUX41 mux_12 (.D0(mdout1_0_3), .D1(mdout1_1_3), .D2(mdout1_2_3), .D3(mdout1_3_3), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[3]));

    MUX41 mux_11 (.D0(mdout1_0_4), .D1(mdout1_1_4), .D2(mdout1_2_4), .D3(mdout1_3_4), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[4]));

    MUX41 mux_10 (.D0(mdout1_0_5), .D1(mdout1_1_5), .D2(mdout1_2_5), .D3(mdout1_3_5), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[5]));

    MUX41 mux_9 (.D0(mdout1_0_6), .D1(mdout1_1_6), .D2(mdout1_2_6), .D3(mdout1_3_6), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[6]));

    MUX41 mux_8 (.D0(mdout1_0_7), .D1(mdout1_1_7), .D2(mdout1_2_7), .D3(mdout1_3_7), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[7]));

    MUX41 mux_7 (.D0(mdout1_0_9), .D1(mdout1_1_9), .D2(mdout1_2_9), .D3(mdout1_3_9), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[8]));

    MUX41 mux_6 (.D0(mdout1_0_10), .D1(mdout1_1_10), .D2(mdout1_2_10), .D3(mdout1_3_10), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[9]));

    MUX41 mux_5 (.D0(mdout1_0_11), .D1(mdout1_1_11), .D2(mdout1_2_11), .D3(mdout1_3_11), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[10]));

    MUX41 mux_4 (.D0(mdout1_0_12), .D1(mdout1_1_12), .D2(mdout1_2_12), .D3(mdout1_3_12), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[11]));

    MUX41 mux_3 (.D0(mdout1_0_13), .D1(mdout1_1_13), .D2(mdout1_2_13), .D3(mdout1_3_13), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[12]));

    MUX41 mux_2 (.D0(mdout1_0_14), .D1(mdout1_1_14), .D2(mdout1_2_14), .D3(mdout1_3_14), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[13]));

    MUX41 mux_1 (.D0(mdout1_0_15), .D1(mdout1_1_15), .D2(mdout1_2_15), .D3(mdout1_3_15), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[14]));

    MUX41 mux_0 (.D0(mdout1_0_16), .D1(mdout1_1_16), .D2(mdout1_2_16), .D3(mdout1_3_16), 
        .SD1(addr110_ff2), .SD2(addr111_ff2), .Z(QB[15]));



    // exemplar begin
    // exemplar attribute ram_dp_true_0_0_3 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_0_0_3 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_0_0_3 RESETMODE SYNC
    // exemplar attribute ram_dp_true_1_0_2 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_1_0_2 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_1_0_2 RESETMODE SYNC
    // exemplar attribute ram_dp_true_2_0_1 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_2_0_1 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_2_0_1 RESETMODE SYNC
    // exemplar attribute ram_dp_true_3_0_0 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_3_0_0 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_3_0_0 RESETMODE SYNC
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
