/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.5 */
/* C:\lscc\diamond\2.2\ispfpga\bin\nt\scuba.exe -w -n afifo18 -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type ebfifo -depth 8192 -width 18 -depth 8192 -rdata_width 18 -no_enable -pe -1 -pf -1 -e  */
/* Tue Jul 16 15:43:25 2013 */


`timescale 1 ns / 1 ps
module afifo18 (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [17:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [17:0] Q;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire w_g2b_xor_cluster_2_1;
    wire w_g2b_xor_cluster_3;
    wire w_g2b_xor_cluster_2;
    wire w_g2b_xor_cluster_1;
    wire r_g2b_xor_cluster_2_1;
    wire r_g2b_xor_cluster_3;
    wire r_g2b_xor_cluster_2;
    wire r_g2b_xor_cluster_1;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire w_gdata_6;
    wire w_gdata_7;
    wire w_gdata_8;
    wire w_gdata_9;
    wire w_gdata_10;
    wire w_gdata_11;
    wire w_gdata_12;
    wire wptr_0;
    wire wptr_1;
    wire wptr_2;
    wire wptr_3;
    wire wptr_4;
    wire wptr_5;
    wire wptr_6;
    wire wptr_7;
    wire wptr_8;
    wire wptr_9;
    wire wptr_10;
    wire wptr_11;
    wire wptr_12;
    wire wptr_13;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire r_gdata_7;
    wire r_gdata_8;
    wire r_gdata_9;
    wire r_gdata_10;
    wire r_gdata_11;
    wire r_gdata_12;
    wire rptr_0;
    wire rptr_1;
    wire rptr_2;
    wire rptr_3;
    wire rptr_4;
    wire rptr_5;
    wire rptr_6;
    wire rptr_7;
    wire rptr_8;
    wire rptr_9;
    wire rptr_10;
    wire rptr_13;
    wire rptr_11;
    wire rptr_12;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire w_gcount_7;
    wire w_gcount_8;
    wire w_gcount_9;
    wire w_gcount_10;
    wire w_gcount_11;
    wire w_gcount_12;
    wire w_gcount_13;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire r_gcount_8;
    wire r_gcount_9;
    wire r_gcount_10;
    wire r_gcount_11;
    wire r_gcount_12;
    wire r_gcount_13;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire w_gcount_r27;
    wire w_gcount_r7;
    wire w_gcount_r28;
    wire w_gcount_r8;
    wire w_gcount_r29;
    wire w_gcount_r9;
    wire w_gcount_r210;
    wire w_gcount_r10;
    wire w_gcount_r211;
    wire w_gcount_r11;
    wire w_gcount_r212;
    wire w_gcount_r12;
    wire w_gcount_r213;
    wire w_gcount_r13;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire r_gcount_w28;
    wire r_gcount_w8;
    wire r_gcount_w29;
    wire r_gcount_w9;
    wire r_gcount_w210;
    wire r_gcount_w10;
    wire r_gcount_w211;
    wire r_gcount_w11;
    wire r_gcount_w212;
    wire r_gcount_w12;
    wire r_gcount_w213;
    wire r_gcount_w13;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire iwcount_7;
    wire co2;
    wire iwcount_8;
    wire iwcount_9;
    wire co3;
    wire iwcount_10;
    wire iwcount_11;
    wire co4;
    wire iwcount_12;
    wire iwcount_13;
    wire co6;
    wire co5;
    wire wcount_13;
    wire scuba_vhi;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co2_1;
    wire ircount_8;
    wire ircount_9;
    wire co3_1;
    wire ircount_10;
    wire ircount_11;
    wire co4_1;
    wire ircount_12;
    wire ircount_13;
    wire co6_1;
    wire co5_1;
    wire rcount_13;
    wire mdout1_3_0;
    wire mdout1_2_0;
    wire mdout1_1_0;
    wire mdout1_0_0;
    wire mdout1_3_1;
    wire mdout1_2_1;
    wire mdout1_1_1;
    wire mdout1_0_1;
    wire mdout1_3_2;
    wire mdout1_2_2;
    wire mdout1_1_2;
    wire mdout1_0_2;
    wire mdout1_3_3;
    wire mdout1_2_3;
    wire mdout1_1_3;
    wire mdout1_0_3;
    wire mdout1_3_4;
    wire mdout1_2_4;
    wire mdout1_1_4;
    wire mdout1_0_4;
    wire mdout1_3_5;
    wire mdout1_2_5;
    wire mdout1_1_5;
    wire mdout1_0_5;
    wire mdout1_3_6;
    wire mdout1_2_6;
    wire mdout1_1_6;
    wire mdout1_0_6;
    wire mdout1_3_7;
    wire mdout1_2_7;
    wire mdout1_1_7;
    wire mdout1_0_7;
    wire mdout1_3_8;
    wire mdout1_2_8;
    wire mdout1_1_8;
    wire mdout1_0_8;
    wire mdout1_3_9;
    wire mdout1_2_9;
    wire mdout1_1_9;
    wire mdout1_0_9;
    wire mdout1_3_10;
    wire mdout1_2_10;
    wire mdout1_1_10;
    wire mdout1_0_10;
    wire mdout1_3_11;
    wire mdout1_2_11;
    wire mdout1_1_11;
    wire mdout1_0_11;
    wire mdout1_3_12;
    wire mdout1_2_12;
    wire mdout1_1_12;
    wire mdout1_0_12;
    wire mdout1_3_13;
    wire mdout1_2_13;
    wire mdout1_1_13;
    wire mdout1_0_13;
    wire mdout1_3_14;
    wire mdout1_2_14;
    wire mdout1_1_14;
    wire mdout1_0_14;
    wire mdout1_3_15;
    wire mdout1_2_15;
    wire mdout1_1_15;
    wire mdout1_0_15;
    wire mdout1_3_16;
    wire mdout1_2_16;
    wire mdout1_1_16;
    wire mdout1_0_16;
    wire rptr_12_ff;
    wire rptr_11_ff;
    wire mdout1_3_17;
    wire mdout1_2_17;
    wire mdout1_1_17;
    wire mdout1_0_17;
    wire rden_i;
    wire cmp_ci;
    wire wcount_r0;
    wire wcount_r1;
    wire rcount_0;
    wire rcount_1;
    wire co0_2;
    wire wcount_r2;
    wire wcount_r3;
    wire rcount_2;
    wire rcount_3;
    wire co1_2;
    wire wcount_r4;
    wire wcount_r5;
    wire rcount_4;
    wire rcount_5;
    wire co2_2;
    wire wcount_r6;
    wire wcount_r7;
    wire rcount_6;
    wire rcount_7;
    wire co3_2;
    wire wcount_r8;
    wire wcount_r9;
    wire rcount_8;
    wire rcount_9;
    wire co4_2;
    wire w_g2b_xor_cluster_0;
    wire wcount_r11;
    wire rcount_10;
    wire rcount_11;
    wire co5_2;
    wire wcount_r12;
    wire empty_cmp_clr;
    wire rcount_12;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire wren_i;
    wire cmp_ci_1;
    wire rcount_w0;
    wire rcount_w1;
    wire wcount_0;
    wire wcount_1;
    wire co0_3;
    wire rcount_w2;
    wire rcount_w3;
    wire wcount_2;
    wire wcount_3;
    wire co1_3;
    wire rcount_w4;
    wire rcount_w5;
    wire wcount_4;
    wire wcount_5;
    wire co2_3;
    wire rcount_w6;
    wire rcount_w7;
    wire wcount_6;
    wire wcount_7;
    wire co3_3;
    wire rcount_w8;
    wire rcount_w9;
    wire wcount_8;
    wire wcount_9;
    wire co4_3;
    wire r_g2b_xor_cluster_0;
    wire rcount_w11;
    wire wcount_10;
    wire wcount_11;
    wire co5_3;
    wire rcount_w12;
    wire full_cmp_clr;
    wire wcount_12;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire scuba_vlo;

    AND2 AND2_t28 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t27 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t26 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t25 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t24 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t23 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t22 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t21 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t20 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t19 (.A(wcount_6), .B(wcount_7), .Z(w_gdata_6));

    XOR2 XOR2_t18 (.A(wcount_7), .B(wcount_8), .Z(w_gdata_7));

    XOR2 XOR2_t17 (.A(wcount_8), .B(wcount_9), .Z(w_gdata_8));

    XOR2 XOR2_t16 (.A(wcount_9), .B(wcount_10), .Z(w_gdata_9));

    XOR2 XOR2_t15 (.A(wcount_10), .B(wcount_11), .Z(w_gdata_10));

    XOR2 XOR2_t14 (.A(wcount_11), .B(wcount_12), .Z(w_gdata_11));

    XOR2 XOR2_t13 (.A(wcount_12), .B(wcount_13), .Z(w_gdata_12));

    XOR2 XOR2_t12 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t11 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t10 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t9 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t8 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t7 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t6 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    XOR2 XOR2_t5 (.A(rcount_7), .B(rcount_8), .Z(r_gdata_7));

    XOR2 XOR2_t4 (.A(rcount_8), .B(rcount_9), .Z(r_gdata_8));

    XOR2 XOR2_t3 (.A(rcount_9), .B(rcount_10), .Z(r_gdata_9));

    XOR2 XOR2_t2 (.A(rcount_10), .B(rcount_11), .Z(r_gdata_10));

    XOR2 XOR2_t1 (.A(rcount_11), .B(rcount_12), .Z(r_gdata_11));

    XOR2 XOR2_t0 (.A(rcount_12), .B(rcount_13), .Z(r_gdata_12));

    defparam LUT4_37.initval =  16'h6996 ;
    ROM16X1A LUT4_37 (.AD3(w_gcount_r210), .AD2(w_gcount_r211), .AD1(w_gcount_r212), 
        .AD0(w_gcount_r213), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_36.initval =  16'h6996 ;
    ROM16X1A LUT4_36 (.AD3(w_gcount_r26), .AD2(w_gcount_r27), .AD1(w_gcount_r28), 
        .AD0(w_gcount_r29), .DO0(w_g2b_xor_cluster_1));

    defparam LUT4_35.initval =  16'h6996 ;
    ROM16X1A LUT4_35 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(w_gcount_r25), .DO0(w_g2b_xor_cluster_2));

    defparam LUT4_34.initval =  16'h6996 ;
    ROM16X1A LUT4_34 (.AD3(w_gcount_r212), .AD2(w_gcount_r213), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r12));

    defparam LUT4_33.initval =  16'h6996 ;
    ROM16X1A LUT4_33 (.AD3(w_gcount_r211), .AD2(w_gcount_r212), .AD1(w_gcount_r213), 
        .AD0(scuba_vlo), .DO0(wcount_r11));

    defparam LUT4_32.initval =  16'h6996 ;
    ROM16X1A LUT4_32 (.AD3(w_gcount_r29), .AD2(w_gcount_r210), .AD1(w_gcount_r211), 
        .AD0(wcount_r12), .DO0(wcount_r9));

    defparam LUT4_31.initval =  16'h6996 ;
    ROM16X1A LUT4_31 (.AD3(w_gcount_r28), .AD2(w_gcount_r29), .AD1(w_gcount_r210), 
        .AD0(wcount_r11), .DO0(wcount_r8));

    defparam LUT4_30.initval =  16'h6996 ;
    ROM16X1A LUT4_30 (.AD3(w_gcount_r27), .AD2(w_gcount_r28), .AD1(w_gcount_r29), 
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r7));

    defparam LUT4_29.initval =  16'h6996 ;
    ROM16X1A LUT4_29 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(wcount_r6));

    defparam LUT4_28.initval =  16'h6996 ;
    ROM16X1A LUT4_28 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r25), .AD0(scuba_vlo), .DO0(wcount_r5));

    defparam LUT4_27.initval =  16'h6996 ;
    ROM16X1A LUT4_27 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r24), .AD0(w_gcount_r25), .DO0(wcount_r4));

    defparam LUT4_26.initval =  16'h6996 ;
    ROM16X1A LUT4_26 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25), 
        .AD0(scuba_vlo), .DO0(w_g2b_xor_cluster_2_1));

    defparam LUT4_25.initval =  16'h6996 ;
    ROM16X1A LUT4_25 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2_1), .AD0(scuba_vlo), .DO0(wcount_r3));

    defparam LUT4_24.initval =  16'h6996 ;
    ROM16X1A LUT4_24 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(wcount_r2));

    defparam LUT4_23.initval =  16'h6996 ;
    ROM16X1A LUT4_23 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2), .AD0(w_gcount_r21), .DO0(wcount_r1));

    defparam LUT4_22.initval =  16'h6996 ;
    ROM16X1A LUT4_22 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(w_g2b_xor_cluster_3));

    defparam LUT4_21.initval =  16'h6996 ;
    ROM16X1A LUT4_21 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2), .AD0(w_g2b_xor_cluster_3), .DO0(wcount_r0));

    defparam LUT4_20.initval =  16'h6996 ;
    ROM16X1A LUT4_20 (.AD3(r_gcount_w210), .AD2(r_gcount_w211), .AD1(r_gcount_w212), 
        .AD0(r_gcount_w213), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(r_gcount_w28), 
        .AD0(r_gcount_w29), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(r_gcount_w25), .DO0(r_g2b_xor_cluster_2));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(r_gcount_w212), .AD2(r_gcount_w213), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w12));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(r_gcount_w211), .AD2(r_gcount_w212), .AD1(r_gcount_w213), 
        .AD0(scuba_vlo), .DO0(rcount_w11));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(r_gcount_w29), .AD2(r_gcount_w210), .AD1(r_gcount_w211), 
        .AD0(rcount_w12), .DO0(rcount_w9));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(r_gcount_w28), .AD2(r_gcount_w29), .AD1(r_gcount_w210), 
        .AD0(rcount_w11), .DO0(rcount_w8));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(r_gcount_w27), .AD2(r_gcount_w28), .AD1(r_gcount_w29), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w7));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w6));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w25), .AD0(scuba_vlo), .DO0(rcount_w5));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w24), .AD0(r_gcount_w25), .DO0(rcount_w4));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(scuba_vlo), .DO0(r_g2b_xor_cluster_2_1));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2_1), .AD0(scuba_vlo), .DO0(rcount_w3));

    defparam LUT4_7.initval =  16'h6996 ;
    ROM16X1A LUT4_7 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(rcount_w2));

    defparam LUT4_6.initval =  16'h6996 ;
    ROM16X1A LUT4_6 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2), .AD0(r_gcount_w21), .DO0(rcount_w1));

    defparam LUT4_5.initval =  16'h6996 ;
    ROM16X1A LUT4_5 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(r_g2b_xor_cluster_3));

    defparam LUT4_4.initval =  16'h6996 ;
    ROM16X1A LUT4_4 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2), .AD0(r_g2b_xor_cluster_3), .DO0(rcount_w0));

    defparam LUT4_3.initval =  16'h0410 ;
    ROM16X1A LUT4_3 (.AD3(rptr_13), .AD2(rcount_13), .AD1(w_gcount_r213), 
        .AD0(scuba_vlo), .DO0(empty_cmp_set));

    defparam LUT4_2.initval =  16'h1004 ;
    ROM16X1A LUT4_2 (.AD3(rptr_13), .AD2(rcount_13), .AD1(w_gcount_r213), 
        .AD0(scuba_vlo), .DO0(empty_cmp_clr));

    defparam LUT4_1.initval =  16'h0140 ;
    ROM16X1A LUT4_1 (.AD3(wptr_13), .AD2(wcount_13), .AD1(r_gcount_w213), 
        .AD0(scuba_vlo), .DO0(full_cmp_set));

    defparam LUT4_0.initval =  16'h4001 ;
    ROM16X1A LUT4_0 (.AD3(wptr_13), .AD2(wcount_13), .AD1(r_gcount_w213), 
        .AD0(scuba_vlo), .DO0(full_cmp_clr));

    defparam pdp_ram_0_0_7.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_0_7.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_0_7.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_7.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_7.GSR = "DISABLED" ;
    defparam pdp_ram_0_0_7.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_0_7.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_0_7.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_0_7.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_0_0_7 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_0_0), .DOB1(mdout1_0_1), 
        .DOB2(mdout1_0_2), .DOB3(mdout1_0_3), .DOB4(mdout1_0_4), .DOB5(mdout1_0_5), 
        .DOB6(mdout1_0_6), .DOB7(mdout1_0_7), .DOB8(mdout1_0_8), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_0_1_6.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_1_6.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_1_6.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_1_6.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_1_6.GSR = "DISABLED" ;
    defparam pdp_ram_0_1_6.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_1_6.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_1_6.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_1_6.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_0_1_6 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_0_9), .DOB1(mdout1_0_10), 
        .DOB2(mdout1_0_11), .DOB3(mdout1_0_12), .DOB4(mdout1_0_13), .DOB5(mdout1_0_14), 
        .DOB6(mdout1_0_15), .DOB7(mdout1_0_16), .DOB8(mdout1_0_17), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_1_0_5.CSDECODE_B = "0b001" ;
    defparam pdp_ram_1_0_5.CSDECODE_A = "0b001" ;
    defparam pdp_ram_1_0_5.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_1_0_5.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_1_0_5.GSR = "DISABLED" ;
    defparam pdp_ram_1_0_5.REGMODE_B = "NOREG" ;
    defparam pdp_ram_1_0_5.REGMODE_A = "NOREG" ;
    defparam pdp_ram_1_0_5.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_1_0_5.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_1_0_5 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_1_0), .DOB1(mdout1_1_1), 
        .DOB2(mdout1_1_2), .DOB3(mdout1_1_3), .DOB4(mdout1_1_4), .DOB5(mdout1_1_5), 
        .DOB6(mdout1_1_6), .DOB7(mdout1_1_7), .DOB8(mdout1_1_8), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_1_1_4.CSDECODE_B = "0b001" ;
    defparam pdp_ram_1_1_4.CSDECODE_A = "0b001" ;
    defparam pdp_ram_1_1_4.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_1_1_4.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_1_1_4.GSR = "DISABLED" ;
    defparam pdp_ram_1_1_4.REGMODE_B = "NOREG" ;
    defparam pdp_ram_1_1_4.REGMODE_A = "NOREG" ;
    defparam pdp_ram_1_1_4.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_1_1_4.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_1_1_4 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_1_9), .DOB1(mdout1_1_10), 
        .DOB2(mdout1_1_11), .DOB3(mdout1_1_12), .DOB4(mdout1_1_13), .DOB5(mdout1_1_14), 
        .DOB6(mdout1_1_15), .DOB7(mdout1_1_16), .DOB8(mdout1_1_17), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_2_0_3.CSDECODE_B = "0b010" ;
    defparam pdp_ram_2_0_3.CSDECODE_A = "0b010" ;
    defparam pdp_ram_2_0_3.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_2_0_3.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_2_0_3.GSR = "DISABLED" ;
    defparam pdp_ram_2_0_3.REGMODE_B = "NOREG" ;
    defparam pdp_ram_2_0_3.REGMODE_A = "NOREG" ;
    defparam pdp_ram_2_0_3.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_2_0_3.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_2_0_3 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_2_0), .DOB1(mdout1_2_1), 
        .DOB2(mdout1_2_2), .DOB3(mdout1_2_3), .DOB4(mdout1_2_4), .DOB5(mdout1_2_5), 
        .DOB6(mdout1_2_6), .DOB7(mdout1_2_7), .DOB8(mdout1_2_8), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_2_1_2.CSDECODE_B = "0b010" ;
    defparam pdp_ram_2_1_2.CSDECODE_A = "0b010" ;
    defparam pdp_ram_2_1_2.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_2_1_2.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_2_1_2.GSR = "DISABLED" ;
    defparam pdp_ram_2_1_2.REGMODE_B = "NOREG" ;
    defparam pdp_ram_2_1_2.REGMODE_A = "NOREG" ;
    defparam pdp_ram_2_1_2.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_2_1_2.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_2_1_2 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_2_9), .DOB1(mdout1_2_10), 
        .DOB2(mdout1_2_11), .DOB3(mdout1_2_12), .DOB4(mdout1_2_13), .DOB5(mdout1_2_14), 
        .DOB6(mdout1_2_15), .DOB7(mdout1_2_16), .DOB8(mdout1_2_17), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_3_0_1.CSDECODE_B = "0b011" ;
    defparam pdp_ram_3_0_1.CSDECODE_A = "0b011" ;
    defparam pdp_ram_3_0_1.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_3_0_1.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_3_0_1.GSR = "DISABLED" ;
    defparam pdp_ram_3_0_1.REGMODE_B = "NOREG" ;
    defparam pdp_ram_3_0_1.REGMODE_A = "NOREG" ;
    defparam pdp_ram_3_0_1.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_3_0_1.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_3_0_1 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_3_0), .DOB1(mdout1_3_1), 
        .DOB2(mdout1_3_2), .DOB3(mdout1_3_3), .DOB4(mdout1_3_4), .DOB5(mdout1_3_5), 
        .DOB6(mdout1_3_6), .DOB7(mdout1_3_7), .DOB8(mdout1_3_8), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam pdp_ram_3_1_0.CSDECODE_B = "0b011" ;
    defparam pdp_ram_3_1_0.CSDECODE_A = "0b011" ;
    defparam pdp_ram_3_1_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_3_1_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_3_1_0.GSR = "DISABLED" ;
    defparam pdp_ram_3_1_0.REGMODE_B = "NOREG" ;
    defparam pdp_ram_3_1_0.REGMODE_A = "NOREG" ;
    defparam pdp_ram_3_1_0.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_3_1_0.DATA_WIDTH_A = 9 ;
    DP16KC pdp_ram_3_1_0 (.DIA0(Data[9]), .DIA1(Data[10]), .DIA2(Data[11]), 
        .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), .DIA6(Data[15]), 
        .DIA7(Data[16]), .DIA8(Data[17]), .DIA9(scuba_vlo), .DIA10(scuba_vlo), 
        .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), .DIA14(scuba_vlo), 
        .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(wptr_0), .ADA4(wptr_1), 
        .ADA5(wptr_2), .ADA6(wptr_3), .ADA7(wptr_4), .ADA8(wptr_5), .ADA9(wptr_6), 
        .ADA10(wptr_7), .ADA11(wptr_8), .ADA12(wptr_9), .ADA13(wptr_10), 
        .CEA(wren_i), .CLKA(WrClock), .OCEA(wren_i), .WEA(scuba_vhi), .CSA0(wptr_11), 
        .CSA1(wptr_12), .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), 
        .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), 
        .ADB3(rptr_0), .ADB4(rptr_1), .ADB5(rptr_2), .ADB6(rptr_3), .ADB7(rptr_4), 
        .ADB8(rptr_5), .ADB9(rptr_6), .ADB10(rptr_7), .ADB11(rptr_8), .ADB12(rptr_9), 
        .ADB13(rptr_10), .CEB(rden_i), .CLKB(RdClock), .OCEB(rden_i), .WEB(scuba_vlo), 
        .CSB0(rptr_11), .CSB1(rptr_12), .CSB2(scuba_vlo), .RSTB(Reset), 
        .DOA0(), .DOA1(), .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), 
        .DOA8(), .DOA9(), .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), 
        .DOA15(), .DOA16(), .DOA17(), .DOB0(mdout1_3_9), .DOB1(mdout1_3_10), 
        .DOB2(mdout1_3_11), .DOB3(mdout1_3_12), .DOB4(mdout1_3_13), .DOB5(mdout1_3_14), 
        .DOB6(mdout1_3_15), .DOB7(mdout1_3_16), .DOB8(mdout1_3_17), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="afifo18.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    FD1P3BX FF_143 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_142 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_141 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_140 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_139 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_138 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_137 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_136 (.D(iwcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_135 (.D(iwcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_134 (.D(iwcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_133 (.D(iwcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_132 (.D(iwcount_11), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_131 (.D(iwcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_130 (.D(iwcount_13), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_129 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_128 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_127 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_126 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_125 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_124 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_123 (.D(w_gdata_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_122 (.D(w_gdata_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_121 (.D(w_gdata_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_120 (.D(w_gdata_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_119 (.D(w_gdata_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_118 (.D(w_gdata_11), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_117 (.D(w_gdata_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_116 (.D(wcount_13), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_115 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_114 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_113 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_112 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_111 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_110 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_109 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_108 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_107 (.D(wcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_106 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_105 (.D(wcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_104 (.D(wcount_11), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_103 (.D(wcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_102 (.D(wcount_13), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_101 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_100 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_99 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_98 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_97 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_96 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_95 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_93 (.D(ircount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(ircount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(ircount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(ircount_11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(ircount_12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(ircount_13), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(r_gdata_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(r_gdata_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(r_gdata_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_77 (.D(r_gdata_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(r_gdata_11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(r_gdata_12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(rcount_13), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(rcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(rcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(rcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(rcount_11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(rcount_12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(rcount_13), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(rptr_11), .SP(rden_i), .CK(RdClock), .CD(scuba_vlo), 
        .Q(rptr_11_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(rptr_12), .SP(rden_i), .CK(RdClock), .CD(scuba_vlo), 
        .Q(rptr_12_ff))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_57 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_56 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_55 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_54 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_53 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_52 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_51 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_50 (.D(w_gcount_7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_49 (.D(w_gcount_8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_48 (.D(w_gcount_9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_47 (.D(w_gcount_10), .CK(RdClock), .CD(Reset), .Q(w_gcount_r10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_46 (.D(w_gcount_11), .CK(RdClock), .CD(Reset), .Q(w_gcount_r11))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_45 (.D(w_gcount_12), .CK(RdClock), .CD(Reset), .Q(w_gcount_r12))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_44 (.D(w_gcount_13), .CK(RdClock), .CD(Reset), .Q(w_gcount_r13))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_43 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_42 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_41 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_39 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_38 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_35 (.D(r_gcount_8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(r_gcount_9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(r_gcount_10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(r_gcount_11), .CK(WrClock), .CD(rRst), .Q(r_gcount_w11))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(r_gcount_12), .CK(WrClock), .CD(rRst), .Q(r_gcount_w12))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(r_gcount_13), .CK(WrClock), .CD(rRst), .Q(r_gcount_w13))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_26 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_25 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_24 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_23 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(w_gcount_r7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_21 (.D(w_gcount_r8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_20 (.D(w_gcount_r9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_19 (.D(w_gcount_r10), .CK(RdClock), .CD(Reset), .Q(w_gcount_r210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_18 (.D(w_gcount_r11), .CK(RdClock), .CD(Reset), .Q(w_gcount_r211))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_17 (.D(w_gcount_r12), .CK(RdClock), .CD(Reset), .Q(w_gcount_r212))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_16 (.D(w_gcount_r13), .CK(RdClock), .CD(Reset), .Q(w_gcount_r213))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_15 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_14 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_13 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_12 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_11 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_10 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_9 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_8 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_7 (.D(r_gcount_w8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_6 (.D(r_gcount_w9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_5 (.D(r_gcount_w10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_4 (.D(r_gcount_w11), .CK(WrClock), .CD(rRst), .Q(r_gcount_w211))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_3 (.D(r_gcount_w12), .CK(WrClock), .CD(rRst), .Q(r_gcount_w212))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_2 (.D(r_gcount_w13), .CK(WrClock), .CD(rRst), .Q(r_gcount_w213))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_1 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FADD2B w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(w_gctr_ci), .S0(), .S1());

    CU2 w_gctr_0 (.CI(w_gctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0), 
        .NC0(iwcount_0), .NC1(iwcount_1));

    CU2 w_gctr_1 (.CI(co0), .PC0(wcount_2), .PC1(wcount_3), .CO(co1), .NC0(iwcount_2), 
        .NC1(iwcount_3));

    CU2 w_gctr_2 (.CI(co1), .PC0(wcount_4), .PC1(wcount_5), .CO(co2), .NC0(iwcount_4), 
        .NC1(iwcount_5));

    CU2 w_gctr_3 (.CI(co2), .PC0(wcount_6), .PC1(wcount_7), .CO(co3), .NC0(iwcount_6), 
        .NC1(iwcount_7));

    CU2 w_gctr_4 (.CI(co3), .PC0(wcount_8), .PC1(wcount_9), .CO(co4), .NC0(iwcount_8), 
        .NC1(iwcount_9));

    CU2 w_gctr_5 (.CI(co4), .PC0(wcount_10), .PC1(wcount_11), .CO(co5), 
        .NC0(iwcount_10), .NC1(iwcount_11));

    CU2 w_gctr_6 (.CI(co5), .PC0(wcount_12), .PC1(wcount_13), .CO(co6), 
        .NC0(iwcount_12), .NC1(iwcount_13));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(r_gctr_ci), .S0(), .S1());

    CU2 r_gctr_0 (.CI(r_gctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_1), 
        .NC0(ircount_0), .NC1(ircount_1));

    CU2 r_gctr_1 (.CI(co0_1), .PC0(rcount_2), .PC1(rcount_3), .CO(co1_1), 
        .NC0(ircount_2), .NC1(ircount_3));

    CU2 r_gctr_2 (.CI(co1_1), .PC0(rcount_4), .PC1(rcount_5), .CO(co2_1), 
        .NC0(ircount_4), .NC1(ircount_5));

    CU2 r_gctr_3 (.CI(co2_1), .PC0(rcount_6), .PC1(rcount_7), .CO(co3_1), 
        .NC0(ircount_6), .NC1(ircount_7));

    CU2 r_gctr_4 (.CI(co3_1), .PC0(rcount_8), .PC1(rcount_9), .CO(co4_1), 
        .NC0(ircount_8), .NC1(ircount_9));

    CU2 r_gctr_5 (.CI(co4_1), .PC0(rcount_10), .PC1(rcount_11), .CO(co5_1), 
        .NC0(ircount_10), .NC1(ircount_11));

    CU2 r_gctr_6 (.CI(co5_1), .PC0(rcount_12), .PC1(rcount_13), .CO(co6_1), 
        .NC0(ircount_12), .NC1(ircount_13));

    MUX41 mux_17 (.D0(mdout1_0_0), .D1(mdout1_1_0), .D2(mdout1_2_0), .D3(mdout1_3_0), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[0]));

    MUX41 mux_16 (.D0(mdout1_0_1), .D1(mdout1_1_1), .D2(mdout1_2_1), .D3(mdout1_3_1), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[1]));

    MUX41 mux_15 (.D0(mdout1_0_2), .D1(mdout1_1_2), .D2(mdout1_2_2), .D3(mdout1_3_2), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[2]));

    MUX41 mux_14 (.D0(mdout1_0_3), .D1(mdout1_1_3), .D2(mdout1_2_3), .D3(mdout1_3_3), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[3]));

    MUX41 mux_13 (.D0(mdout1_0_4), .D1(mdout1_1_4), .D2(mdout1_2_4), .D3(mdout1_3_4), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[4]));

    MUX41 mux_12 (.D0(mdout1_0_5), .D1(mdout1_1_5), .D2(mdout1_2_5), .D3(mdout1_3_5), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[5]));

    MUX41 mux_11 (.D0(mdout1_0_6), .D1(mdout1_1_6), .D2(mdout1_2_6), .D3(mdout1_3_6), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[6]));

    MUX41 mux_10 (.D0(mdout1_0_7), .D1(mdout1_1_7), .D2(mdout1_2_7), .D3(mdout1_3_7), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[7]));

    MUX41 mux_9 (.D0(mdout1_0_8), .D1(mdout1_1_8), .D2(mdout1_2_8), .D3(mdout1_3_8), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[8]));

    MUX41 mux_8 (.D0(mdout1_0_9), .D1(mdout1_1_9), .D2(mdout1_2_9), .D3(mdout1_3_9), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[9]));

    MUX41 mux_7 (.D0(mdout1_0_10), .D1(mdout1_1_10), .D2(mdout1_2_10), .D3(mdout1_3_10), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[10]));

    MUX41 mux_6 (.D0(mdout1_0_11), .D1(mdout1_1_11), .D2(mdout1_2_11), .D3(mdout1_3_11), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[11]));

    MUX41 mux_5 (.D0(mdout1_0_12), .D1(mdout1_1_12), .D2(mdout1_2_12), .D3(mdout1_3_12), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[12]));

    MUX41 mux_4 (.D0(mdout1_0_13), .D1(mdout1_1_13), .D2(mdout1_2_13), .D3(mdout1_3_13), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[13]));

    MUX41 mux_3 (.D0(mdout1_0_14), .D1(mdout1_1_14), .D2(mdout1_2_14), .D3(mdout1_3_14), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[14]));

    MUX41 mux_2 (.D0(mdout1_0_15), .D1(mdout1_1_15), .D2(mdout1_2_15), .D3(mdout1_3_15), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[15]));

    MUX41 mux_1 (.D0(mdout1_0_16), .D1(mdout1_1_16), .D2(mdout1_2_16), .D3(mdout1_3_16), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[16]));

    MUX41 mux_0 (.D0(mdout1_0_17), .D1(mdout1_1_17), .D2(mdout1_2_17), .D3(mdout1_3_17), 
        .SD1(rptr_11_ff), .SD2(rptr_12_ff), .Z(Q[17]));

    FADD2B empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    AGEB2 empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1), 
        .CI(cmp_ci), .GE(co0_2));

    AGEB2 empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r2), .B1(wcount_r3), 
        .CI(co0_2), .GE(co1_2));

    AGEB2 empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(wcount_r4), .B1(wcount_r5), 
        .CI(co1_2), .GE(co2_2));

    AGEB2 empty_cmp_3 (.A0(rcount_6), .A1(rcount_7), .B0(wcount_r6), .B1(wcount_r7), 
        .CI(co2_2), .GE(co3_2));

    AGEB2 empty_cmp_4 (.A0(rcount_8), .A1(rcount_9), .B0(wcount_r8), .B1(wcount_r9), 
        .CI(co3_2), .GE(co4_2));

    AGEB2 empty_cmp_5 (.A0(rcount_10), .A1(rcount_11), .B0(w_g2b_xor_cluster_0), 
        .B1(wcount_r11), .CI(co4_2), .GE(co5_2));

    AGEB2 empty_cmp_6 (.A0(rcount_12), .A1(empty_cmp_set), .B0(wcount_r12), 
        .B1(empty_cmp_clr), .CI(co5_2), .GE(empty_d_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(empty_d_c), .COUT(), .S0(empty_d), .S1());

    FADD2B full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1), 
        .CI(cmp_ci_1), .GE(co0_3));

    AGEB2 full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w2), .B1(rcount_w3), 
        .CI(co0_3), .GE(co1_3));

    AGEB2 full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(rcount_w4), .B1(rcount_w5), 
        .CI(co1_3), .GE(co2_3));

    AGEB2 full_cmp_3 (.A0(wcount_6), .A1(wcount_7), .B0(rcount_w6), .B1(rcount_w7), 
        .CI(co2_3), .GE(co3_3));

    AGEB2 full_cmp_4 (.A0(wcount_8), .A1(wcount_9), .B0(rcount_w8), .B1(rcount_w9), 
        .CI(co3_3), .GE(co4_3));

    AGEB2 full_cmp_5 (.A0(wcount_10), .A1(wcount_11), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w11), .CI(co4_3), .GE(co5_3));

    AGEB2 full_cmp_6 (.A0(wcount_12), .A1(full_cmp_set), .B0(rcount_w12), 
        .B1(full_cmp_clr), .CI(co5_3), .GE(full_d_c));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(full_d_c), .COUT(), .S0(full_d), .S1());

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_7 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_0_0_7 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_0_7 RESETMODE SYNC
    // exemplar attribute pdp_ram_0_1_6 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_0_1_6 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_6 RESETMODE SYNC
    // exemplar attribute pdp_ram_1_0_5 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_1_0_5 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_1_0_5 RESETMODE SYNC
    // exemplar attribute pdp_ram_1_1_4 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_1_1_4 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_1_1_4 RESETMODE SYNC
    // exemplar attribute pdp_ram_2_0_3 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_2_0_3 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_2_0_3 RESETMODE SYNC
    // exemplar attribute pdp_ram_2_1_2 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_2_1_2 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_2_1_2 RESETMODE SYNC
    // exemplar attribute pdp_ram_3_0_1 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_3_0_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_3_0_1 RESETMODE SYNC
    // exemplar attribute pdp_ram_3_1_0 MEM_LPC_FILE afifo18.lpc
    // exemplar attribute pdp_ram_3_1_0 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_3_1_0 RESETMODE SYNC
    // exemplar attribute FF_143 GSR ENABLED
    // exemplar attribute FF_142 GSR ENABLED
    // exemplar attribute FF_141 GSR ENABLED
    // exemplar attribute FF_140 GSR ENABLED
    // exemplar attribute FF_139 GSR ENABLED
    // exemplar attribute FF_138 GSR ENABLED
    // exemplar attribute FF_137 GSR ENABLED
    // exemplar attribute FF_136 GSR ENABLED
    // exemplar attribute FF_135 GSR ENABLED
    // exemplar attribute FF_134 GSR ENABLED
    // exemplar attribute FF_133 GSR ENABLED
    // exemplar attribute FF_132 GSR ENABLED
    // exemplar attribute FF_131 GSR ENABLED
    // exemplar attribute FF_130 GSR ENABLED
    // exemplar attribute FF_129 GSR ENABLED
    // exemplar attribute FF_128 GSR ENABLED
    // exemplar attribute FF_127 GSR ENABLED
    // exemplar attribute FF_126 GSR ENABLED
    // exemplar attribute FF_125 GSR ENABLED
    // exemplar attribute FF_124 GSR ENABLED
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
