/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 7.1 */
/* Tue Apr 09 16:32:57 2013 */

/* parameterized module instance */
ram_dp_true __ (.DataInA( ), .DataInB( ), .ByteEnA( ), .ByteEnB( ), 
    .AddressA( ), .AddressB( ), .ClockA( ), .ClockB( ), .ClockEnA( ), 
    .ClockEnB( ), .WrA( ), .WrB( ), .ResetA( ), .ResetB( ), .QA( ), 
    .QB( ));
