/* Verilog netlist generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 7.1 */
/* C:\lscc\diamond\1.4\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type bram -wp 11 -rp 1010 -data_width 32 -rdata_width 32 -num_rows 2048 -byte 8 -outdataA REGISTERED -outdataB REGISTERED -writemodeA NORMAL -writemodeB NORMAL -cascade -1 -e  */
/* Sat Apr 06 14:57:33 2013 */


`timescale 1 ns / 1 ps
module ram_dp_true (DataInA, DataInB, ByteEnA, ByteEnB, AddressA, 
    AddressB, ClockA, ClockB, ClockEnA, ClockEnB, WrA, WrB, ResetA, 
    ResetB, QA, QB);
    input wire [31:0] DataInA;
    input wire [31:0] DataInB;
    input wire [3:0] ByteEnA;
    input wire [3:0] ByteEnB;
    input wire [10:0] AddressA;
    input wire [10:0] AddressB;
    input wire ClockA;
    input wire ClockB;
    input wire ClockEnA;
    input wire ClockEnB;
    input wire WrA;
    input wire WrB;
    input wire ResetA;
    input wire ResetB;
    output wire [31:0] QA;
    output wire [31:0] QB;

    wire scuba_vhi;
    wire wren0_inv;
    wire wren1_inv;
    wire mdout1_0_17;
    wire mdout0_0_17;
    wire mdout1_0_8;
    wire mdout0_0_8;
    wire mdout1_0_35;
    wire mdout0_0_35;
    wire mdout1_0_26;
    wire mdout0_0_26;
    wire mdout1_1_17;
    wire mdout0_1_17;
    wire mdout1_1_8;
    wire mdout0_1_8;
    wire mdout1_1_35;
    wire mdout0_1_35;
    wire mdout1_1_26;
    wire mdout0_1_26;
    wire wren0_inv_g;
    wire addr010_ff;
    wire wren1_inv_g;
    wire scuba_vlo;
    wire addr110_ff;
    wire mdout0_1_0;
    wire mdout0_0_0;
    wire mdout0_1_1;
    wire mdout0_0_1;
    wire mdout0_1_2;
    wire mdout0_0_2;
    wire mdout0_1_3;
    wire mdout0_0_3;
    wire mdout0_1_4;
    wire mdout0_0_4;
    wire mdout0_1_5;
    wire mdout0_0_5;
    wire mdout0_1_6;
    wire mdout0_0_6;
    wire mdout0_1_7;
    wire mdout0_0_7;
    wire mdout0_1_9;
    wire mdout0_0_9;
    wire mdout0_1_10;
    wire mdout0_0_10;
    wire mdout0_1_11;
    wire mdout0_0_11;
    wire mdout0_1_12;
    wire mdout0_0_12;
    wire mdout0_1_13;
    wire mdout0_0_13;
    wire mdout0_1_14;
    wire mdout0_0_14;
    wire mdout0_1_15;
    wire mdout0_0_15;
    wire mdout0_1_16;
    wire mdout0_0_16;
    wire mdout0_1_18;
    wire mdout0_0_18;
    wire mdout0_1_19;
    wire mdout0_0_19;
    wire mdout0_1_20;
    wire mdout0_0_20;
    wire mdout0_1_21;
    wire mdout0_0_21;
    wire mdout0_1_22;
    wire mdout0_0_22;
    wire mdout0_1_23;
    wire mdout0_0_23;
    wire mdout0_1_24;
    wire mdout0_0_24;
    wire mdout0_1_25;
    wire mdout0_0_25;
    wire mdout0_1_27;
    wire mdout0_0_27;
    wire mdout0_1_28;
    wire mdout0_0_28;
    wire mdout0_1_29;
    wire mdout0_0_29;
    wire mdout0_1_30;
    wire mdout0_0_30;
    wire mdout0_1_31;
    wire mdout0_0_31;
    wire mdout0_1_32;
    wire mdout0_0_32;
    wire mdout0_1_33;
    wire mdout0_0_33;
    wire addr010_ff2;
    wire mdout0_1_34;
    wire mdout0_0_34;
    wire mdout1_1_0;
    wire mdout1_0_0;
    wire mdout1_1_1;
    wire mdout1_0_1;
    wire mdout1_1_2;
    wire mdout1_0_2;
    wire mdout1_1_3;
    wire mdout1_0_3;
    wire mdout1_1_4;
    wire mdout1_0_4;
    wire mdout1_1_5;
    wire mdout1_0_5;
    wire mdout1_1_6;
    wire mdout1_0_6;
    wire mdout1_1_7;
    wire mdout1_0_7;
    wire mdout1_1_9;
    wire mdout1_0_9;
    wire mdout1_1_10;
    wire mdout1_0_10;
    wire mdout1_1_11;
    wire mdout1_0_11;
    wire mdout1_1_12;
    wire mdout1_0_12;
    wire mdout1_1_13;
    wire mdout1_0_13;
    wire mdout1_1_14;
    wire mdout1_0_14;
    wire mdout1_1_15;
    wire mdout1_0_15;
    wire mdout1_1_16;
    wire mdout1_0_16;
    wire mdout1_1_18;
    wire mdout1_0_18;
    wire mdout1_1_19;
    wire mdout1_0_19;
    wire mdout1_1_20;
    wire mdout1_0_20;
    wire mdout1_1_21;
    wire mdout1_0_21;
    wire mdout1_1_22;
    wire mdout1_0_22;
    wire mdout1_1_23;
    wire mdout1_0_23;
    wire mdout1_1_24;
    wire mdout1_0_24;
    wire mdout1_1_25;
    wire mdout1_0_25;
    wire mdout1_1_27;
    wire mdout1_0_27;
    wire mdout1_1_28;
    wire mdout1_0_28;
    wire mdout1_1_29;
    wire mdout1_0_29;
    wire mdout1_1_30;
    wire mdout1_0_30;
    wire mdout1_1_31;
    wire mdout1_0_31;
    wire mdout1_1_32;
    wire mdout1_0_32;
    wire mdout1_1_33;
    wire mdout1_0_33;
    wire addr110_ff2;
    wire mdout1_1_34;
    wire mdout1_0_34;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    INV INV_1 (.A(WrA), .Z(wren0_inv));

    AND2 AND2_t1 (.A(wren0_inv), .B(ClockEnA), .Z(wren0_inv_g));

    INV INV_0 (.A(WrB), .Z(wren1_inv));

    AND2 AND2_t0 (.A(wren1_inv), .B(ClockEnB), .Z(wren1_inv_g));

    defparam ram_dp_true_0_0_3.CSDECODE_B = "0b000" ;
    defparam ram_dp_true_0_0_3.CSDECODE_A = "0b000" ;
    defparam ram_dp_true_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_0_0_3.GSR = "DISABLED" ;
    defparam ram_dp_true_0_0_3.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_0_0_3.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_0_0_3.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_0_0_3.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_0_0_3 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_0_0), .DOA1(mdout0_0_1), .DOA2(mdout0_0_2), 
        .DOA3(mdout0_0_3), .DOA4(mdout0_0_4), .DOA5(mdout0_0_5), .DOA6(mdout0_0_6), 
        .DOA7(mdout0_0_7), .DOA8(mdout0_0_8), .DOA9(mdout0_0_9), .DOA10(mdout0_0_10), 
        .DOA11(mdout0_0_11), .DOA12(mdout0_0_12), .DOA13(mdout0_0_13), .DOA14(mdout0_0_14), 
        .DOA15(mdout0_0_15), .DOA16(mdout0_0_16), .DOA17(mdout0_0_17), .DOB0(mdout1_0_0), 
        .DOB1(mdout1_0_1), .DOB2(mdout1_0_2), .DOB3(mdout1_0_3), .DOB4(mdout1_0_4), 
        .DOB5(mdout1_0_5), .DOB6(mdout1_0_6), .DOB7(mdout1_0_7), .DOB8(mdout1_0_8), 
        .DOB9(mdout1_0_9), .DOB10(mdout1_0_10), .DOB11(mdout1_0_11), .DOB12(mdout1_0_12), 
        .DOB13(mdout1_0_13), .DOB14(mdout1_0_14), .DOB15(mdout1_0_15), .DOB16(mdout1_0_16), 
        .DOB17(mdout1_0_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_0_1_2.CSDECODE_B = "0b000" ;
    defparam ram_dp_true_0_1_2.CSDECODE_A = "0b000" ;
    defparam ram_dp_true_0_1_2.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_0_1_2.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_0_1_2.GSR = "DISABLED" ;
    defparam ram_dp_true_0_1_2.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_0_1_2.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_0_1_2.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_0_1_2.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_0_1_2 (.DIA0(DataInA[16]), .DIA1(DataInA[17]), .DIA2(DataInA[18]), 
        .DIA3(DataInA[19]), .DIA4(DataInA[20]), .DIA5(DataInA[21]), .DIA6(DataInA[22]), 
        .DIA7(DataInA[23]), .DIA8(scuba_vlo), .DIA9(DataInA[24]), .DIA10(DataInA[25]), 
        .DIA11(DataInA[26]), .DIA12(DataInA[27]), .DIA13(DataInA[28]), .DIA14(DataInA[29]), 
        .DIA15(DataInA[30]), .DIA16(DataInA[31]), .DIA17(scuba_vlo), .ADA0(ByteEnA[2]), 
        .ADA1(ByteEnA[3]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[16]), .DIB1(DataInB[17]), .DIB2(DataInB[18]), 
        .DIB3(DataInB[19]), .DIB4(DataInB[20]), .DIB5(DataInB[21]), .DIB6(DataInB[22]), 
        .DIB7(DataInB[23]), .DIB8(scuba_vlo), .DIB9(DataInB[24]), .DIB10(DataInB[25]), 
        .DIB11(DataInB[26]), .DIB12(DataInB[27]), .DIB13(DataInB[28]), .DIB14(DataInB[29]), 
        .DIB15(DataInB[30]), .DIB16(DataInB[31]), .DIB17(scuba_vlo), .ADB0(ByteEnB[2]), 
        .ADB1(ByteEnB[3]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_0_18), .DOA1(mdout0_0_19), .DOA2(mdout0_0_20), 
        .DOA3(mdout0_0_21), .DOA4(mdout0_0_22), .DOA5(mdout0_0_23), .DOA6(mdout0_0_24), 
        .DOA7(mdout0_0_25), .DOA8(mdout0_0_26), .DOA9(mdout0_0_27), .DOA10(mdout0_0_28), 
        .DOA11(mdout0_0_29), .DOA12(mdout0_0_30), .DOA13(mdout0_0_31), .DOA14(mdout0_0_32), 
        .DOA15(mdout0_0_33), .DOA16(mdout0_0_34), .DOA17(mdout0_0_35), .DOB0(mdout1_0_18), 
        .DOB1(mdout1_0_19), .DOB2(mdout1_0_20), .DOB3(mdout1_0_21), .DOB4(mdout1_0_22), 
        .DOB5(mdout1_0_23), .DOB6(mdout1_0_24), .DOB7(mdout1_0_25), .DOB8(mdout1_0_26), 
        .DOB9(mdout1_0_27), .DOB10(mdout1_0_28), .DOB11(mdout1_0_29), .DOB12(mdout1_0_30), 
        .DOB13(mdout1_0_31), .DOB14(mdout1_0_32), .DOB15(mdout1_0_33), .DOB16(mdout1_0_34), 
        .DOB17(mdout1_0_35))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_1_0_1.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_1_0_1.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_1_0_1.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_1_0_1.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_1_0_1.GSR = "DISABLED" ;
    defparam ram_dp_true_1_0_1.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_1_0_1.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_1_0_1.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_1_0_1.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_1_0_1 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_1_0), .DOA1(mdout0_1_1), .DOA2(mdout0_1_2), 
        .DOA3(mdout0_1_3), .DOA4(mdout0_1_4), .DOA5(mdout0_1_5), .DOA6(mdout0_1_6), 
        .DOA7(mdout0_1_7), .DOA8(mdout0_1_8), .DOA9(mdout0_1_9), .DOA10(mdout0_1_10), 
        .DOA11(mdout0_1_11), .DOA12(mdout0_1_12), .DOA13(mdout0_1_13), .DOA14(mdout0_1_14), 
        .DOA15(mdout0_1_15), .DOA16(mdout0_1_16), .DOA17(mdout0_1_17), .DOB0(mdout1_1_0), 
        .DOB1(mdout1_1_1), .DOB2(mdout1_1_2), .DOB3(mdout1_1_3), .DOB4(mdout1_1_4), 
        .DOB5(mdout1_1_5), .DOB6(mdout1_1_6), .DOB7(mdout1_1_7), .DOB8(mdout1_1_8), 
        .DOB9(mdout1_1_9), .DOB10(mdout1_1_10), .DOB11(mdout1_1_11), .DOB12(mdout1_1_12), 
        .DOB13(mdout1_1_13), .DOB14(mdout1_1_14), .DOB15(mdout1_1_15), .DOB16(mdout1_1_16), 
        .DOB17(mdout1_1_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_1_1_0.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_1_1_0.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_1_1_0.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_1_1_0.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_1_1_0.GSR = "DISABLED" ;
    defparam ram_dp_true_1_1_0.REGMODE_B = "OUTREG" ;
    defparam ram_dp_true_1_1_0.REGMODE_A = "OUTREG" ;
    defparam ram_dp_true_1_1_0.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_1_1_0.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_1_1_0 (.DIA0(DataInA[16]), .DIA1(DataInA[17]), .DIA2(DataInA[18]), 
        .DIA3(DataInA[19]), .DIA4(DataInA[20]), .DIA5(DataInA[21]), .DIA6(DataInA[22]), 
        .DIA7(DataInA[23]), .DIA8(scuba_vlo), .DIA9(DataInA[24]), .DIA10(DataInA[25]), 
        .DIA11(DataInA[26]), .DIA12(DataInA[27]), .DIA13(DataInA[28]), .DIA14(DataInA[29]), 
        .DIA15(DataInA[30]), .DIA16(DataInA[31]), .DIA17(scuba_vlo), .ADA0(ByteEnA[2]), 
        .ADA1(ByteEnA[3]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(AddressA[10]), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[16]), .DIB1(DataInB[17]), .DIB2(DataInB[18]), 
        .DIB3(DataInB[19]), .DIB4(DataInB[20]), .DIB5(DataInB[21]), .DIB6(DataInB[22]), 
        .DIB7(DataInB[23]), .DIB8(scuba_vlo), .DIB9(DataInB[24]), .DIB10(DataInB[25]), 
        .DIB11(DataInB[26]), .DIB12(DataInB[27]), .DIB13(DataInB[28]), .DIB14(DataInB[29]), 
        .DIB15(DataInB[30]), .DIB16(DataInB[31]), .DIB17(scuba_vlo), .ADB0(ByteEnB[2]), 
        .ADB1(ByteEnB[3]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(AddressB[10]), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_1_18), .DOA1(mdout0_1_19), .DOA2(mdout0_1_20), 
        .DOA3(mdout0_1_21), .DOA4(mdout0_1_22), .DOA5(mdout0_1_23), .DOA6(mdout0_1_24), 
        .DOA7(mdout0_1_25), .DOA8(mdout0_1_26), .DOA9(mdout0_1_27), .DOA10(mdout0_1_28), 
        .DOA11(mdout0_1_29), .DOA12(mdout0_1_30), .DOA13(mdout0_1_31), .DOA14(mdout0_1_32), 
        .DOA15(mdout0_1_33), .DOA16(mdout0_1_34), .DOA17(mdout0_1_35), .DOB0(mdout1_1_18), 
        .DOB1(mdout1_1_19), .DOB2(mdout1_1_20), .DOB3(mdout1_1_21), .DOB4(mdout1_1_22), 
        .DOB5(mdout1_1_23), .DOB6(mdout1_1_24), .DOB7(mdout1_1_25), .DOB8(mdout1_1_26), 
        .DOB9(mdout1_1_27), .DOB10(mdout1_1_28), .DOB11(mdout1_1_29), .DOB12(mdout1_1_30), 
        .DOB13(mdout1_1_31), .DOB14(mdout1_1_32), .DOB15(mdout1_1_33), .DOB16(mdout1_1_34), 
        .DOB17(mdout1_1_35))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    FD1P3DX FF_3 (.D(AddressA[10]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr010_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(addr010_ff), .SP(ClockEnA), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr010_ff2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(AddressB[10]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr110_ff))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FD1P3DX FF_0 (.D(addr110_ff), .SP(ClockEnB), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr110_ff2))
             /* synthesis GSR="ENABLED" */;

    MUX21 mux_63 (.D0(mdout0_0_0), .D1(mdout0_1_0), .SD(addr010_ff2), .Z(QA[0]));

    MUX21 mux_62 (.D0(mdout0_0_1), .D1(mdout0_1_1), .SD(addr010_ff2), .Z(QA[1]));

    MUX21 mux_61 (.D0(mdout0_0_2), .D1(mdout0_1_2), .SD(addr010_ff2), .Z(QA[2]));

    MUX21 mux_60 (.D0(mdout0_0_3), .D1(mdout0_1_3), .SD(addr010_ff2), .Z(QA[3]));

    MUX21 mux_59 (.D0(mdout0_0_4), .D1(mdout0_1_4), .SD(addr010_ff2), .Z(QA[4]));

    MUX21 mux_58 (.D0(mdout0_0_5), .D1(mdout0_1_5), .SD(addr010_ff2), .Z(QA[5]));

    MUX21 mux_57 (.D0(mdout0_0_6), .D1(mdout0_1_6), .SD(addr010_ff2), .Z(QA[6]));

    MUX21 mux_56 (.D0(mdout0_0_7), .D1(mdout0_1_7), .SD(addr010_ff2), .Z(QA[7]));

    MUX21 mux_55 (.D0(mdout0_0_9), .D1(mdout0_1_9), .SD(addr010_ff2), .Z(QA[8]));

    MUX21 mux_54 (.D0(mdout0_0_10), .D1(mdout0_1_10), .SD(addr010_ff2), 
        .Z(QA[9]));

    MUX21 mux_53 (.D0(mdout0_0_11), .D1(mdout0_1_11), .SD(addr010_ff2), 
        .Z(QA[10]));

    MUX21 mux_52 (.D0(mdout0_0_12), .D1(mdout0_1_12), .SD(addr010_ff2), 
        .Z(QA[11]));

    MUX21 mux_51 (.D0(mdout0_0_13), .D1(mdout0_1_13), .SD(addr010_ff2), 
        .Z(QA[12]));

    MUX21 mux_50 (.D0(mdout0_0_14), .D1(mdout0_1_14), .SD(addr010_ff2), 
        .Z(QA[13]));

    MUX21 mux_49 (.D0(mdout0_0_15), .D1(mdout0_1_15), .SD(addr010_ff2), 
        .Z(QA[14]));

    MUX21 mux_48 (.D0(mdout0_0_16), .D1(mdout0_1_16), .SD(addr010_ff2), 
        .Z(QA[15]));

    MUX21 mux_47 (.D0(mdout0_0_18), .D1(mdout0_1_18), .SD(addr010_ff2), 
        .Z(QA[16]));

    MUX21 mux_46 (.D0(mdout0_0_19), .D1(mdout0_1_19), .SD(addr010_ff2), 
        .Z(QA[17]));

    MUX21 mux_45 (.D0(mdout0_0_20), .D1(mdout0_1_20), .SD(addr010_ff2), 
        .Z(QA[18]));

    MUX21 mux_44 (.D0(mdout0_0_21), .D1(mdout0_1_21), .SD(addr010_ff2), 
        .Z(QA[19]));

    MUX21 mux_43 (.D0(mdout0_0_22), .D1(mdout0_1_22), .SD(addr010_ff2), 
        .Z(QA[20]));

    MUX21 mux_42 (.D0(mdout0_0_23), .D1(mdout0_1_23), .SD(addr010_ff2), 
        .Z(QA[21]));

    MUX21 mux_41 (.D0(mdout0_0_24), .D1(mdout0_1_24), .SD(addr010_ff2), 
        .Z(QA[22]));

    MUX21 mux_40 (.D0(mdout0_0_25), .D1(mdout0_1_25), .SD(addr010_ff2), 
        .Z(QA[23]));

    MUX21 mux_39 (.D0(mdout0_0_27), .D1(mdout0_1_27), .SD(addr010_ff2), 
        .Z(QA[24]));

    MUX21 mux_38 (.D0(mdout0_0_28), .D1(mdout0_1_28), .SD(addr010_ff2), 
        .Z(QA[25]));

    MUX21 mux_37 (.D0(mdout0_0_29), .D1(mdout0_1_29), .SD(addr010_ff2), 
        .Z(QA[26]));

    MUX21 mux_36 (.D0(mdout0_0_30), .D1(mdout0_1_30), .SD(addr010_ff2), 
        .Z(QA[27]));

    MUX21 mux_35 (.D0(mdout0_0_31), .D1(mdout0_1_31), .SD(addr010_ff2), 
        .Z(QA[28]));

    MUX21 mux_34 (.D0(mdout0_0_32), .D1(mdout0_1_32), .SD(addr010_ff2), 
        .Z(QA[29]));

    MUX21 mux_33 (.D0(mdout0_0_33), .D1(mdout0_1_33), .SD(addr010_ff2), 
        .Z(QA[30]));

    MUX21 mux_32 (.D0(mdout0_0_34), .D1(mdout0_1_34), .SD(addr010_ff2), 
        .Z(QA[31]));

    MUX21 mux_31 (.D0(mdout1_0_0), .D1(mdout1_1_0), .SD(addr110_ff2), .Z(QB[0]));

    MUX21 mux_30 (.D0(mdout1_0_1), .D1(mdout1_1_1), .SD(addr110_ff2), .Z(QB[1]));

    MUX21 mux_29 (.D0(mdout1_0_2), .D1(mdout1_1_2), .SD(addr110_ff2), .Z(QB[2]));

    MUX21 mux_28 (.D0(mdout1_0_3), .D1(mdout1_1_3), .SD(addr110_ff2), .Z(QB[3]));

    MUX21 mux_27 (.D0(mdout1_0_4), .D1(mdout1_1_4), .SD(addr110_ff2), .Z(QB[4]));

    MUX21 mux_26 (.D0(mdout1_0_5), .D1(mdout1_1_5), .SD(addr110_ff2), .Z(QB[5]));

    MUX21 mux_25 (.D0(mdout1_0_6), .D1(mdout1_1_6), .SD(addr110_ff2), .Z(QB[6]));

    MUX21 mux_24 (.D0(mdout1_0_7), .D1(mdout1_1_7), .SD(addr110_ff2), .Z(QB[7]));

    MUX21 mux_23 (.D0(mdout1_0_9), .D1(mdout1_1_9), .SD(addr110_ff2), .Z(QB[8]));

    MUX21 mux_22 (.D0(mdout1_0_10), .D1(mdout1_1_10), .SD(addr110_ff2), 
        .Z(QB[9]));

    MUX21 mux_21 (.D0(mdout1_0_11), .D1(mdout1_1_11), .SD(addr110_ff2), 
        .Z(QB[10]));

    MUX21 mux_20 (.D0(mdout1_0_12), .D1(mdout1_1_12), .SD(addr110_ff2), 
        .Z(QB[11]));

    MUX21 mux_19 (.D0(mdout1_0_13), .D1(mdout1_1_13), .SD(addr110_ff2), 
        .Z(QB[12]));

    MUX21 mux_18 (.D0(mdout1_0_14), .D1(mdout1_1_14), .SD(addr110_ff2), 
        .Z(QB[13]));

    MUX21 mux_17 (.D0(mdout1_0_15), .D1(mdout1_1_15), .SD(addr110_ff2), 
        .Z(QB[14]));

    MUX21 mux_16 (.D0(mdout1_0_16), .D1(mdout1_1_16), .SD(addr110_ff2), 
        .Z(QB[15]));

    MUX21 mux_15 (.D0(mdout1_0_18), .D1(mdout1_1_18), .SD(addr110_ff2), 
        .Z(QB[16]));

    MUX21 mux_14 (.D0(mdout1_0_19), .D1(mdout1_1_19), .SD(addr110_ff2), 
        .Z(QB[17]));

    MUX21 mux_13 (.D0(mdout1_0_20), .D1(mdout1_1_20), .SD(addr110_ff2), 
        .Z(QB[18]));

    MUX21 mux_12 (.D0(mdout1_0_21), .D1(mdout1_1_21), .SD(addr110_ff2), 
        .Z(QB[19]));

    MUX21 mux_11 (.D0(mdout1_0_22), .D1(mdout1_1_22), .SD(addr110_ff2), 
        .Z(QB[20]));

    MUX21 mux_10 (.D0(mdout1_0_23), .D1(mdout1_1_23), .SD(addr110_ff2), 
        .Z(QB[21]));

    MUX21 mux_9 (.D0(mdout1_0_24), .D1(mdout1_1_24), .SD(addr110_ff2), .Z(QB[22]));

    MUX21 mux_8 (.D0(mdout1_0_25), .D1(mdout1_1_25), .SD(addr110_ff2), .Z(QB[23]));

    MUX21 mux_7 (.D0(mdout1_0_27), .D1(mdout1_1_27), .SD(addr110_ff2), .Z(QB[24]));

    MUX21 mux_6 (.D0(mdout1_0_28), .D1(mdout1_1_28), .SD(addr110_ff2), .Z(QB[25]));

    MUX21 mux_5 (.D0(mdout1_0_29), .D1(mdout1_1_29), .SD(addr110_ff2), .Z(QB[26]));

    MUX21 mux_4 (.D0(mdout1_0_30), .D1(mdout1_1_30), .SD(addr110_ff2), .Z(QB[27]));

    MUX21 mux_3 (.D0(mdout1_0_31), .D1(mdout1_1_31), .SD(addr110_ff2), .Z(QB[28]));

    MUX21 mux_2 (.D0(mdout1_0_32), .D1(mdout1_1_32), .SD(addr110_ff2), .Z(QB[29]));

    MUX21 mux_1 (.D0(mdout1_0_33), .D1(mdout1_1_33), .SD(addr110_ff2), .Z(QB[30]));

    MUX21 mux_0 (.D0(mdout1_0_34), .D1(mdout1_1_34), .SD(addr110_ff2), .Z(QB[31]));



    // exemplar begin
    // exemplar attribute ram_dp_true_0_0_3 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_0_0_3 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_0_0_3 RESETMODE SYNC
    // exemplar attribute ram_dp_true_0_1_2 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_0_1_2 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_0_1_2 RESETMODE SYNC
    // exemplar attribute ram_dp_true_1_0_1 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_1_0_1 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_1_0_1 RESETMODE SYNC
    // exemplar attribute ram_dp_true_1_1_0 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_1_1_0 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_1_1_0 RESETMODE SYNC
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
