/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* Wed Jul 17 17:34:38 2013 */

/* parameterized module instance */
ram_dp_true __ (.DataInA( ), .DataInB( ), .ByteEnA( ), .ByteEnB( ), 
    .AddressA( ), .AddressB( ), .ClockA( ), .ClockB( ), .ClockEnA( ), 
    .ClockEnB( ), .WrA( ), .WrB( ), .ResetA( ), .ResetB( ), .QA( ), 
    .QB( ));
