/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* C:\lscc\diamond\2.2\ispfpga\bin\nt\scuba.exe -w -n ram_dp_true -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type bram -wp 11 -rp 1010 -data_width 16 -rdata_width 16 -num_rows 16384 -byte 8 -writemodeA NORMAL -writemodeB NORMAL -cascade -1 -e  */
/* Wed Jul 17 17:34:38 2013 */


`timescale 1 ns / 1 ps
module ram_dp_true (DataInA, DataInB, ByteEnA, ByteEnB, AddressA, 
    AddressB, ClockA, ClockB, ClockEnA, ClockEnB, WrA, WrB, ResetA, 
    ResetB, QA, QB)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] DataInA;
    input wire [15:0] DataInB;
    input wire [1:0] ByteEnA;
    input wire [1:0] ByteEnB;
    input wire [13:0] AddressA;
    input wire [13:0] AddressB;
    input wire ClockA;
    input wire ClockB;
    input wire ClockEnA;
    input wire ClockEnB;
    input wire WrA;
    input wire WrB;
    input wire ResetA;
    input wire ResetB;
    output wire [15:0] QA;
    output wire [15:0] QB;

    wire scuba_vhi;
    wire addr013_inv;
    wire addr113_inv;
    wire addr012_inv;
    wire addr112_inv;
    wire addr011_inv;
    wire addr111_inv;
    wire addr010_inv;
    wire addr110_inv;
    wire wren0_inv;
    wire wren1_inv;
    wire mdout1_0_17;
    wire mdout0_0_17;
    wire mdout1_0_8;
    wire mdout0_0_8;
    wire dec1_p10;
    wire dec0_p00;
    wire mdout1_1_17;
    wire mdout0_1_17;
    wire mdout1_1_8;
    wire mdout0_1_8;
    wire dec3_p11;
    wire dec2_p01;
    wire mdout1_2_17;
    wire mdout0_2_17;
    wire mdout1_2_8;
    wire mdout0_2_8;
    wire dec5_p12;
    wire dec4_p02;
    wire mdout1_3_17;
    wire mdout0_3_17;
    wire mdout1_3_8;
    wire mdout0_3_8;
    wire dec7_p13;
    wire dec6_p03;
    wire mdout1_4_17;
    wire mdout0_4_17;
    wire mdout1_4_8;
    wire mdout0_4_8;
    wire dec9_p14;
    wire dec8_p04;
    wire mdout1_5_17;
    wire mdout0_5_17;
    wire mdout1_5_8;
    wire mdout0_5_8;
    wire dec11_p15;
    wire dec10_p05;
    wire mdout1_6_17;
    wire mdout0_6_17;
    wire mdout1_6_8;
    wire mdout0_6_8;
    wire dec13_p16;
    wire dec12_p06;
    wire mdout1_7_17;
    wire mdout0_7_17;
    wire mdout1_7_8;
    wire mdout0_7_8;
    wire dec15_p17;
    wire dec14_p07;
    wire mdout1_8_17;
    wire mdout0_8_17;
    wire mdout1_8_8;
    wire mdout0_8_8;
    wire dec17_p18;
    wire dec16_p08;
    wire mdout1_9_17;
    wire mdout0_9_17;
    wire mdout1_9_8;
    wire mdout0_9_8;
    wire dec19_p19;
    wire dec18_p09;
    wire mdout1_10_17;
    wire mdout0_10_17;
    wire mdout1_10_8;
    wire mdout0_10_8;
    wire dec21_p110;
    wire dec20_p010;
    wire mdout1_11_17;
    wire mdout0_11_17;
    wire mdout1_11_8;
    wire mdout0_11_8;
    wire dec23_p111;
    wire dec22_p011;
    wire mdout1_12_17;
    wire mdout0_12_17;
    wire mdout1_12_8;
    wire mdout0_12_8;
    wire dec25_p112;
    wire dec24_p012;
    wire mdout1_13_17;
    wire mdout0_13_17;
    wire mdout1_13_8;
    wire mdout0_13_8;
    wire dec27_p113;
    wire dec26_p013;
    wire mdout1_14_17;
    wire mdout0_14_17;
    wire mdout1_14_8;
    wire mdout0_14_8;
    wire dec29_p114;
    wire dec28_p014;
    wire mdout1_15_17;
    wire mdout0_15_17;
    wire mdout1_15_8;
    wire mdout0_15_8;
    wire dec31_p115;
    wire dec30_p015;
    wire wren0_inv_g;
    wire scuba_vlo;
    wire wren1_inv_g;
    wire mdout0_15_0;
    wire mdout0_14_0;
    wire mdout0_13_0;
    wire mdout0_12_0;
    wire mdout0_11_0;
    wire mdout0_10_0;
    wire mdout0_9_0;
    wire mdout0_8_0;
    wire mdout0_7_0;
    wire mdout0_6_0;
    wire mdout0_5_0;
    wire mdout0_4_0;
    wire mdout0_3_0;
    wire mdout0_2_0;
    wire mdout0_1_0;
    wire mdout0_0_0;
    wire mdout0_15_1;
    wire mdout0_14_1;
    wire mdout0_13_1;
    wire mdout0_12_1;
    wire mdout0_11_1;
    wire mdout0_10_1;
    wire mdout0_9_1;
    wire mdout0_8_1;
    wire mdout0_7_1;
    wire mdout0_6_1;
    wire mdout0_5_1;
    wire mdout0_4_1;
    wire mdout0_3_1;
    wire mdout0_2_1;
    wire mdout0_1_1;
    wire mdout0_0_1;
    wire mdout0_15_2;
    wire mdout0_14_2;
    wire mdout0_13_2;
    wire mdout0_12_2;
    wire mdout0_11_2;
    wire mdout0_10_2;
    wire mdout0_9_2;
    wire mdout0_8_2;
    wire mdout0_7_2;
    wire mdout0_6_2;
    wire mdout0_5_2;
    wire mdout0_4_2;
    wire mdout0_3_2;
    wire mdout0_2_2;
    wire mdout0_1_2;
    wire mdout0_0_2;
    wire mdout0_15_3;
    wire mdout0_14_3;
    wire mdout0_13_3;
    wire mdout0_12_3;
    wire mdout0_11_3;
    wire mdout0_10_3;
    wire mdout0_9_3;
    wire mdout0_8_3;
    wire mdout0_7_3;
    wire mdout0_6_3;
    wire mdout0_5_3;
    wire mdout0_4_3;
    wire mdout0_3_3;
    wire mdout0_2_3;
    wire mdout0_1_3;
    wire mdout0_0_3;
    wire mdout0_15_4;
    wire mdout0_14_4;
    wire mdout0_13_4;
    wire mdout0_12_4;
    wire mdout0_11_4;
    wire mdout0_10_4;
    wire mdout0_9_4;
    wire mdout0_8_4;
    wire mdout0_7_4;
    wire mdout0_6_4;
    wire mdout0_5_4;
    wire mdout0_4_4;
    wire mdout0_3_4;
    wire mdout0_2_4;
    wire mdout0_1_4;
    wire mdout0_0_4;
    wire mdout0_15_5;
    wire mdout0_14_5;
    wire mdout0_13_5;
    wire mdout0_12_5;
    wire mdout0_11_5;
    wire mdout0_10_5;
    wire mdout0_9_5;
    wire mdout0_8_5;
    wire mdout0_7_5;
    wire mdout0_6_5;
    wire mdout0_5_5;
    wire mdout0_4_5;
    wire mdout0_3_5;
    wire mdout0_2_5;
    wire mdout0_1_5;
    wire mdout0_0_5;
    wire mdout0_15_6;
    wire mdout0_14_6;
    wire mdout0_13_6;
    wire mdout0_12_6;
    wire mdout0_11_6;
    wire mdout0_10_6;
    wire mdout0_9_6;
    wire mdout0_8_6;
    wire mdout0_7_6;
    wire mdout0_6_6;
    wire mdout0_5_6;
    wire mdout0_4_6;
    wire mdout0_3_6;
    wire mdout0_2_6;
    wire mdout0_1_6;
    wire mdout0_0_6;
    wire mdout0_15_7;
    wire mdout0_14_7;
    wire mdout0_13_7;
    wire mdout0_12_7;
    wire mdout0_11_7;
    wire mdout0_10_7;
    wire mdout0_9_7;
    wire mdout0_8_7;
    wire mdout0_7_7;
    wire mdout0_6_7;
    wire mdout0_5_7;
    wire mdout0_4_7;
    wire mdout0_3_7;
    wire mdout0_2_7;
    wire mdout0_1_7;
    wire mdout0_0_7;
    wire mdout0_15_9;
    wire mdout0_14_9;
    wire mdout0_13_9;
    wire mdout0_12_9;
    wire mdout0_11_9;
    wire mdout0_10_9;
    wire mdout0_9_9;
    wire mdout0_8_9;
    wire mdout0_7_9;
    wire mdout0_6_9;
    wire mdout0_5_9;
    wire mdout0_4_9;
    wire mdout0_3_9;
    wire mdout0_2_9;
    wire mdout0_1_9;
    wire mdout0_0_9;
    wire mdout0_15_10;
    wire mdout0_14_10;
    wire mdout0_13_10;
    wire mdout0_12_10;
    wire mdout0_11_10;
    wire mdout0_10_10;
    wire mdout0_9_10;
    wire mdout0_8_10;
    wire mdout0_7_10;
    wire mdout0_6_10;
    wire mdout0_5_10;
    wire mdout0_4_10;
    wire mdout0_3_10;
    wire mdout0_2_10;
    wire mdout0_1_10;
    wire mdout0_0_10;
    wire mdout0_15_11;
    wire mdout0_14_11;
    wire mdout0_13_11;
    wire mdout0_12_11;
    wire mdout0_11_11;
    wire mdout0_10_11;
    wire mdout0_9_11;
    wire mdout0_8_11;
    wire mdout0_7_11;
    wire mdout0_6_11;
    wire mdout0_5_11;
    wire mdout0_4_11;
    wire mdout0_3_11;
    wire mdout0_2_11;
    wire mdout0_1_11;
    wire mdout0_0_11;
    wire mdout0_15_12;
    wire mdout0_14_12;
    wire mdout0_13_12;
    wire mdout0_12_12;
    wire mdout0_11_12;
    wire mdout0_10_12;
    wire mdout0_9_12;
    wire mdout0_8_12;
    wire mdout0_7_12;
    wire mdout0_6_12;
    wire mdout0_5_12;
    wire mdout0_4_12;
    wire mdout0_3_12;
    wire mdout0_2_12;
    wire mdout0_1_12;
    wire mdout0_0_12;
    wire mdout0_15_13;
    wire mdout0_14_13;
    wire mdout0_13_13;
    wire mdout0_12_13;
    wire mdout0_11_13;
    wire mdout0_10_13;
    wire mdout0_9_13;
    wire mdout0_8_13;
    wire mdout0_7_13;
    wire mdout0_6_13;
    wire mdout0_5_13;
    wire mdout0_4_13;
    wire mdout0_3_13;
    wire mdout0_2_13;
    wire mdout0_1_13;
    wire mdout0_0_13;
    wire mdout0_15_14;
    wire mdout0_14_14;
    wire mdout0_13_14;
    wire mdout0_12_14;
    wire mdout0_11_14;
    wire mdout0_10_14;
    wire mdout0_9_14;
    wire mdout0_8_14;
    wire mdout0_7_14;
    wire mdout0_6_14;
    wire mdout0_5_14;
    wire mdout0_4_14;
    wire mdout0_3_14;
    wire mdout0_2_14;
    wire mdout0_1_14;
    wire mdout0_0_14;
    wire mdout0_15_15;
    wire mdout0_14_15;
    wire mdout0_13_15;
    wire mdout0_12_15;
    wire mdout0_11_15;
    wire mdout0_10_15;
    wire mdout0_9_15;
    wire mdout0_8_15;
    wire mdout0_7_15;
    wire mdout0_6_15;
    wire mdout0_5_15;
    wire mdout0_4_15;
    wire mdout0_3_15;
    wire mdout0_2_15;
    wire mdout0_1_15;
    wire mdout0_0_15;
    wire addr013_ff;
    wire addr012_ff;
    wire addr011_ff;
    wire addr010_ff;
    wire mdout0_15_16;
    wire mdout0_14_16;
    wire mdout0_13_16;
    wire mdout0_12_16;
    wire mdout0_11_16;
    wire mdout0_10_16;
    wire mdout0_9_16;
    wire mdout0_8_16;
    wire mdout0_7_16;
    wire mdout0_6_16;
    wire mdout0_5_16;
    wire mdout0_4_16;
    wire mdout0_3_16;
    wire mdout0_2_16;
    wire mdout0_1_16;
    wire mdout0_0_16;
    wire mdout1_15_0;
    wire mdout1_14_0;
    wire mdout1_13_0;
    wire mdout1_12_0;
    wire mdout1_11_0;
    wire mdout1_10_0;
    wire mdout1_9_0;
    wire mdout1_8_0;
    wire mdout1_7_0;
    wire mdout1_6_0;
    wire mdout1_5_0;
    wire mdout1_4_0;
    wire mdout1_3_0;
    wire mdout1_2_0;
    wire mdout1_1_0;
    wire mdout1_0_0;
    wire mdout1_15_1;
    wire mdout1_14_1;
    wire mdout1_13_1;
    wire mdout1_12_1;
    wire mdout1_11_1;
    wire mdout1_10_1;
    wire mdout1_9_1;
    wire mdout1_8_1;
    wire mdout1_7_1;
    wire mdout1_6_1;
    wire mdout1_5_1;
    wire mdout1_4_1;
    wire mdout1_3_1;
    wire mdout1_2_1;
    wire mdout1_1_1;
    wire mdout1_0_1;
    wire mdout1_15_2;
    wire mdout1_14_2;
    wire mdout1_13_2;
    wire mdout1_12_2;
    wire mdout1_11_2;
    wire mdout1_10_2;
    wire mdout1_9_2;
    wire mdout1_8_2;
    wire mdout1_7_2;
    wire mdout1_6_2;
    wire mdout1_5_2;
    wire mdout1_4_2;
    wire mdout1_3_2;
    wire mdout1_2_2;
    wire mdout1_1_2;
    wire mdout1_0_2;
    wire mdout1_15_3;
    wire mdout1_14_3;
    wire mdout1_13_3;
    wire mdout1_12_3;
    wire mdout1_11_3;
    wire mdout1_10_3;
    wire mdout1_9_3;
    wire mdout1_8_3;
    wire mdout1_7_3;
    wire mdout1_6_3;
    wire mdout1_5_3;
    wire mdout1_4_3;
    wire mdout1_3_3;
    wire mdout1_2_3;
    wire mdout1_1_3;
    wire mdout1_0_3;
    wire mdout1_15_4;
    wire mdout1_14_4;
    wire mdout1_13_4;
    wire mdout1_12_4;
    wire mdout1_11_4;
    wire mdout1_10_4;
    wire mdout1_9_4;
    wire mdout1_8_4;
    wire mdout1_7_4;
    wire mdout1_6_4;
    wire mdout1_5_4;
    wire mdout1_4_4;
    wire mdout1_3_4;
    wire mdout1_2_4;
    wire mdout1_1_4;
    wire mdout1_0_4;
    wire mdout1_15_5;
    wire mdout1_14_5;
    wire mdout1_13_5;
    wire mdout1_12_5;
    wire mdout1_11_5;
    wire mdout1_10_5;
    wire mdout1_9_5;
    wire mdout1_8_5;
    wire mdout1_7_5;
    wire mdout1_6_5;
    wire mdout1_5_5;
    wire mdout1_4_5;
    wire mdout1_3_5;
    wire mdout1_2_5;
    wire mdout1_1_5;
    wire mdout1_0_5;
    wire mdout1_15_6;
    wire mdout1_14_6;
    wire mdout1_13_6;
    wire mdout1_12_6;
    wire mdout1_11_6;
    wire mdout1_10_6;
    wire mdout1_9_6;
    wire mdout1_8_6;
    wire mdout1_7_6;
    wire mdout1_6_6;
    wire mdout1_5_6;
    wire mdout1_4_6;
    wire mdout1_3_6;
    wire mdout1_2_6;
    wire mdout1_1_6;
    wire mdout1_0_6;
    wire mdout1_15_7;
    wire mdout1_14_7;
    wire mdout1_13_7;
    wire mdout1_12_7;
    wire mdout1_11_7;
    wire mdout1_10_7;
    wire mdout1_9_7;
    wire mdout1_8_7;
    wire mdout1_7_7;
    wire mdout1_6_7;
    wire mdout1_5_7;
    wire mdout1_4_7;
    wire mdout1_3_7;
    wire mdout1_2_7;
    wire mdout1_1_7;
    wire mdout1_0_7;
    wire mdout1_15_9;
    wire mdout1_14_9;
    wire mdout1_13_9;
    wire mdout1_12_9;
    wire mdout1_11_9;
    wire mdout1_10_9;
    wire mdout1_9_9;
    wire mdout1_8_9;
    wire mdout1_7_9;
    wire mdout1_6_9;
    wire mdout1_5_9;
    wire mdout1_4_9;
    wire mdout1_3_9;
    wire mdout1_2_9;
    wire mdout1_1_9;
    wire mdout1_0_9;
    wire mdout1_15_10;
    wire mdout1_14_10;
    wire mdout1_13_10;
    wire mdout1_12_10;
    wire mdout1_11_10;
    wire mdout1_10_10;
    wire mdout1_9_10;
    wire mdout1_8_10;
    wire mdout1_7_10;
    wire mdout1_6_10;
    wire mdout1_5_10;
    wire mdout1_4_10;
    wire mdout1_3_10;
    wire mdout1_2_10;
    wire mdout1_1_10;
    wire mdout1_0_10;
    wire mdout1_15_11;
    wire mdout1_14_11;
    wire mdout1_13_11;
    wire mdout1_12_11;
    wire mdout1_11_11;
    wire mdout1_10_11;
    wire mdout1_9_11;
    wire mdout1_8_11;
    wire mdout1_7_11;
    wire mdout1_6_11;
    wire mdout1_5_11;
    wire mdout1_4_11;
    wire mdout1_3_11;
    wire mdout1_2_11;
    wire mdout1_1_11;
    wire mdout1_0_11;
    wire mdout1_15_12;
    wire mdout1_14_12;
    wire mdout1_13_12;
    wire mdout1_12_12;
    wire mdout1_11_12;
    wire mdout1_10_12;
    wire mdout1_9_12;
    wire mdout1_8_12;
    wire mdout1_7_12;
    wire mdout1_6_12;
    wire mdout1_5_12;
    wire mdout1_4_12;
    wire mdout1_3_12;
    wire mdout1_2_12;
    wire mdout1_1_12;
    wire mdout1_0_12;
    wire mdout1_15_13;
    wire mdout1_14_13;
    wire mdout1_13_13;
    wire mdout1_12_13;
    wire mdout1_11_13;
    wire mdout1_10_13;
    wire mdout1_9_13;
    wire mdout1_8_13;
    wire mdout1_7_13;
    wire mdout1_6_13;
    wire mdout1_5_13;
    wire mdout1_4_13;
    wire mdout1_3_13;
    wire mdout1_2_13;
    wire mdout1_1_13;
    wire mdout1_0_13;
    wire mdout1_15_14;
    wire mdout1_14_14;
    wire mdout1_13_14;
    wire mdout1_12_14;
    wire mdout1_11_14;
    wire mdout1_10_14;
    wire mdout1_9_14;
    wire mdout1_8_14;
    wire mdout1_7_14;
    wire mdout1_6_14;
    wire mdout1_5_14;
    wire mdout1_4_14;
    wire mdout1_3_14;
    wire mdout1_2_14;
    wire mdout1_1_14;
    wire mdout1_0_14;
    wire mdout1_15_15;
    wire mdout1_14_15;
    wire mdout1_13_15;
    wire mdout1_12_15;
    wire mdout1_11_15;
    wire mdout1_10_15;
    wire mdout1_9_15;
    wire mdout1_8_15;
    wire mdout1_7_15;
    wire mdout1_6_15;
    wire mdout1_5_15;
    wire mdout1_4_15;
    wire mdout1_3_15;
    wire mdout1_2_15;
    wire mdout1_1_15;
    wire mdout1_0_15;
    wire addr113_ff;
    wire addr112_ff;
    wire addr111_ff;
    wire addr110_ff;
    wire mdout1_15_16;
    wire mdout1_14_16;
    wire mdout1_13_16;
    wire mdout1_12_16;
    wire mdout1_11_16;
    wire mdout1_10_16;
    wire mdout1_9_16;
    wire mdout1_8_16;
    wire mdout1_7_16;
    wire mdout1_6_16;
    wire mdout1_5_16;
    wire mdout1_4_16;
    wire mdout1_3_16;
    wire mdout1_2_16;
    wire mdout1_1_16;
    wire mdout1_0_16;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    INV INV_9 (.A(AddressA[10]), .Z(addr010_inv));

    INV INV_8 (.A(AddressA[11]), .Z(addr011_inv));

    INV INV_7 (.A(AddressA[12]), .Z(addr012_inv));

    INV INV_6 (.A(AddressA[13]), .Z(addr013_inv));

    defparam LUT4_31.initval =  16'h8000 ;
    ROM16X1A LUT4_31 (.AD3(addr010_inv), .AD2(addr011_inv), .AD1(addr012_inv), 
        .AD0(addr013_inv), .DO0(dec0_p00));

    INV INV_5 (.A(AddressB[10]), .Z(addr110_inv));

    INV INV_4 (.A(AddressB[11]), .Z(addr111_inv));

    INV INV_3 (.A(AddressB[12]), .Z(addr112_inv));

    INV INV_2 (.A(AddressB[13]), .Z(addr113_inv));

    defparam LUT4_30.initval =  16'h8000 ;
    ROM16X1A LUT4_30 (.AD3(addr110_inv), .AD2(addr111_inv), .AD1(addr112_inv), 
        .AD0(addr113_inv), .DO0(dec1_p10));

    defparam LUT4_29.initval =  16'h8000 ;
    ROM16X1A LUT4_29 (.AD3(AddressA[10]), .AD2(addr011_inv), .AD1(addr012_inv), 
        .AD0(addr013_inv), .DO0(dec2_p01));

    defparam LUT4_28.initval =  16'h8000 ;
    ROM16X1A LUT4_28 (.AD3(AddressB[10]), .AD2(addr111_inv), .AD1(addr112_inv), 
        .AD0(addr113_inv), .DO0(dec3_p11));

    defparam LUT4_27.initval =  16'h8000 ;
    ROM16X1A LUT4_27 (.AD3(addr010_inv), .AD2(AddressA[11]), .AD1(addr012_inv), 
        .AD0(addr013_inv), .DO0(dec4_p02));

    defparam LUT4_26.initval =  16'h8000 ;
    ROM16X1A LUT4_26 (.AD3(addr110_inv), .AD2(AddressB[11]), .AD1(addr112_inv), 
        .AD0(addr113_inv), .DO0(dec5_p12));

    defparam LUT4_25.initval =  16'h8000 ;
    ROM16X1A LUT4_25 (.AD3(AddressA[10]), .AD2(AddressA[11]), .AD1(addr012_inv), 
        .AD0(addr013_inv), .DO0(dec6_p03));

    defparam LUT4_24.initval =  16'h8000 ;
    ROM16X1A LUT4_24 (.AD3(AddressB[10]), .AD2(AddressB[11]), .AD1(addr112_inv), 
        .AD0(addr113_inv), .DO0(dec7_p13));

    defparam LUT4_23.initval =  16'h8000 ;
    ROM16X1A LUT4_23 (.AD3(addr010_inv), .AD2(addr011_inv), .AD1(AddressA[12]), 
        .AD0(addr013_inv), .DO0(dec8_p04));

    defparam LUT4_22.initval =  16'h8000 ;
    ROM16X1A LUT4_22 (.AD3(addr110_inv), .AD2(addr111_inv), .AD1(AddressB[12]), 
        .AD0(addr113_inv), .DO0(dec9_p14));

    defparam LUT4_21.initval =  16'h8000 ;
    ROM16X1A LUT4_21 (.AD3(AddressA[10]), .AD2(addr011_inv), .AD1(AddressA[12]), 
        .AD0(addr013_inv), .DO0(dec10_p05));

    defparam LUT4_20.initval =  16'h8000 ;
    ROM16X1A LUT4_20 (.AD3(AddressB[10]), .AD2(addr111_inv), .AD1(AddressB[12]), 
        .AD0(addr113_inv), .DO0(dec11_p15));

    defparam LUT4_19.initval =  16'h8000 ;
    ROM16X1A LUT4_19 (.AD3(addr010_inv), .AD2(AddressA[11]), .AD1(AddressA[12]), 
        .AD0(addr013_inv), .DO0(dec12_p06));

    defparam LUT4_18.initval =  16'h8000 ;
    ROM16X1A LUT4_18 (.AD3(addr110_inv), .AD2(AddressB[11]), .AD1(AddressB[12]), 
        .AD0(addr113_inv), .DO0(dec13_p16));

    defparam LUT4_17.initval =  16'h8000 ;
    ROM16X1A LUT4_17 (.AD3(AddressA[10]), .AD2(AddressA[11]), .AD1(AddressA[12]), 
        .AD0(addr013_inv), .DO0(dec14_p07));

    defparam LUT4_16.initval =  16'h8000 ;
    ROM16X1A LUT4_16 (.AD3(AddressB[10]), .AD2(AddressB[11]), .AD1(AddressB[12]), 
        .AD0(addr113_inv), .DO0(dec15_p17));

    defparam LUT4_15.initval =  16'h8000 ;
    ROM16X1A LUT4_15 (.AD3(addr010_inv), .AD2(addr011_inv), .AD1(addr012_inv), 
        .AD0(AddressA[13]), .DO0(dec16_p08));

    defparam LUT4_14.initval =  16'h8000 ;
    ROM16X1A LUT4_14 (.AD3(addr110_inv), .AD2(addr111_inv), .AD1(addr112_inv), 
        .AD0(AddressB[13]), .DO0(dec17_p18));

    defparam LUT4_13.initval =  16'h8000 ;
    ROM16X1A LUT4_13 (.AD3(AddressA[10]), .AD2(addr011_inv), .AD1(addr012_inv), 
        .AD0(AddressA[13]), .DO0(dec18_p09));

    defparam LUT4_12.initval =  16'h8000 ;
    ROM16X1A LUT4_12 (.AD3(AddressB[10]), .AD2(addr111_inv), .AD1(addr112_inv), 
        .AD0(AddressB[13]), .DO0(dec19_p19));

    defparam LUT4_11.initval =  16'h8000 ;
    ROM16X1A LUT4_11 (.AD3(addr010_inv), .AD2(AddressA[11]), .AD1(addr012_inv), 
        .AD0(AddressA[13]), .DO0(dec20_p010));

    defparam LUT4_10.initval =  16'h8000 ;
    ROM16X1A LUT4_10 (.AD3(addr110_inv), .AD2(AddressB[11]), .AD1(addr112_inv), 
        .AD0(AddressB[13]), .DO0(dec21_p110));

    defparam LUT4_9.initval =  16'h8000 ;
    ROM16X1A LUT4_9 (.AD3(AddressA[10]), .AD2(AddressA[11]), .AD1(addr012_inv), 
        .AD0(AddressA[13]), .DO0(dec22_p011));

    defparam LUT4_8.initval =  16'h8000 ;
    ROM16X1A LUT4_8 (.AD3(AddressB[10]), .AD2(AddressB[11]), .AD1(addr112_inv), 
        .AD0(AddressB[13]), .DO0(dec23_p111));

    defparam LUT4_7.initval =  16'h8000 ;
    ROM16X1A LUT4_7 (.AD3(addr010_inv), .AD2(addr011_inv), .AD1(AddressA[12]), 
        .AD0(AddressA[13]), .DO0(dec24_p012));

    defparam LUT4_6.initval =  16'h8000 ;
    ROM16X1A LUT4_6 (.AD3(addr110_inv), .AD2(addr111_inv), .AD1(AddressB[12]), 
        .AD0(AddressB[13]), .DO0(dec25_p112));

    defparam LUT4_5.initval =  16'h8000 ;
    ROM16X1A LUT4_5 (.AD3(AddressA[10]), .AD2(addr011_inv), .AD1(AddressA[12]), 
        .AD0(AddressA[13]), .DO0(dec26_p013));

    defparam LUT4_4.initval =  16'h8000 ;
    ROM16X1A LUT4_4 (.AD3(AddressB[10]), .AD2(addr111_inv), .AD1(AddressB[12]), 
        .AD0(AddressB[13]), .DO0(dec27_p113));

    defparam LUT4_3.initval =  16'h8000 ;
    ROM16X1A LUT4_3 (.AD3(addr010_inv), .AD2(AddressA[11]), .AD1(AddressA[12]), 
        .AD0(AddressA[13]), .DO0(dec28_p014));

    defparam LUT4_2.initval =  16'h8000 ;
    ROM16X1A LUT4_2 (.AD3(addr110_inv), .AD2(AddressB[11]), .AD1(AddressB[12]), 
        .AD0(AddressB[13]), .DO0(dec29_p114));

    defparam LUT4_1.initval =  16'h8000 ;
    ROM16X1A LUT4_1 (.AD3(AddressA[10]), .AD2(AddressA[11]), .AD1(AddressA[12]), 
        .AD0(AddressA[13]), .DO0(dec30_p015));

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(AddressB[10]), .AD2(AddressB[11]), .AD1(AddressB[12]), 
        .AD0(AddressB[13]), .DO0(dec31_p115));

    INV INV_1 (.A(WrA), .Z(wren0_inv));

    AND2 AND2_t1 (.A(wren0_inv), .B(ClockEnA), .Z(wren0_inv_g));

    INV INV_0 (.A(WrB), .Z(wren1_inv));

    AND2 AND2_t0 (.A(wren1_inv), .B(ClockEnB), .Z(wren1_inv_g));

    defparam ram_dp_true_0_0_15.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_0_0_15.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_0_0_15.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_0_0_15.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_0_0_15.GSR = "DISABLED" ;
    defparam ram_dp_true_0_0_15.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_0_0_15.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_0_0_15.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_0_0_15.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_0_0_15 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec0_p00), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec1_p10), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_0_0), .DOA1(mdout0_0_1), .DOA2(mdout0_0_2), 
        .DOA3(mdout0_0_3), .DOA4(mdout0_0_4), .DOA5(mdout0_0_5), .DOA6(mdout0_0_6), 
        .DOA7(mdout0_0_7), .DOA8(mdout0_0_8), .DOA9(mdout0_0_9), .DOA10(mdout0_0_10), 
        .DOA11(mdout0_0_11), .DOA12(mdout0_0_12), .DOA13(mdout0_0_13), .DOA14(mdout0_0_14), 
        .DOA15(mdout0_0_15), .DOA16(mdout0_0_16), .DOA17(mdout0_0_17), .DOB0(mdout1_0_0), 
        .DOB1(mdout1_0_1), .DOB2(mdout1_0_2), .DOB3(mdout1_0_3), .DOB4(mdout1_0_4), 
        .DOB5(mdout1_0_5), .DOB6(mdout1_0_6), .DOB7(mdout1_0_7), .DOB8(mdout1_0_8), 
        .DOB9(mdout1_0_9), .DOB10(mdout1_0_10), .DOB11(mdout1_0_11), .DOB12(mdout1_0_12), 
        .DOB13(mdout1_0_13), .DOB14(mdout1_0_14), .DOB15(mdout1_0_15), .DOB16(mdout1_0_16), 
        .DOB17(mdout1_0_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_1_0_14.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_1_0_14.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_1_0_14.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_1_0_14.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_1_0_14.GSR = "DISABLED" ;
    defparam ram_dp_true_1_0_14.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_1_0_14.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_1_0_14.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_1_0_14.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_1_0_14 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec2_p01), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec3_p11), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_1_0), .DOA1(mdout0_1_1), .DOA2(mdout0_1_2), 
        .DOA3(mdout0_1_3), .DOA4(mdout0_1_4), .DOA5(mdout0_1_5), .DOA6(mdout0_1_6), 
        .DOA7(mdout0_1_7), .DOA8(mdout0_1_8), .DOA9(mdout0_1_9), .DOA10(mdout0_1_10), 
        .DOA11(mdout0_1_11), .DOA12(mdout0_1_12), .DOA13(mdout0_1_13), .DOA14(mdout0_1_14), 
        .DOA15(mdout0_1_15), .DOA16(mdout0_1_16), .DOA17(mdout0_1_17), .DOB0(mdout1_1_0), 
        .DOB1(mdout1_1_1), .DOB2(mdout1_1_2), .DOB3(mdout1_1_3), .DOB4(mdout1_1_4), 
        .DOB5(mdout1_1_5), .DOB6(mdout1_1_6), .DOB7(mdout1_1_7), .DOB8(mdout1_1_8), 
        .DOB9(mdout1_1_9), .DOB10(mdout1_1_10), .DOB11(mdout1_1_11), .DOB12(mdout1_1_12), 
        .DOB13(mdout1_1_13), .DOB14(mdout1_1_14), .DOB15(mdout1_1_15), .DOB16(mdout1_1_16), 
        .DOB17(mdout1_1_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_2_0_13.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_2_0_13.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_2_0_13.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_2_0_13.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_2_0_13.GSR = "DISABLED" ;
    defparam ram_dp_true_2_0_13.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_2_0_13.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_2_0_13.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_2_0_13.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_2_0_13 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec4_p02), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec5_p12), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_2_0), .DOA1(mdout0_2_1), .DOA2(mdout0_2_2), 
        .DOA3(mdout0_2_3), .DOA4(mdout0_2_4), .DOA5(mdout0_2_5), .DOA6(mdout0_2_6), 
        .DOA7(mdout0_2_7), .DOA8(mdout0_2_8), .DOA9(mdout0_2_9), .DOA10(mdout0_2_10), 
        .DOA11(mdout0_2_11), .DOA12(mdout0_2_12), .DOA13(mdout0_2_13), .DOA14(mdout0_2_14), 
        .DOA15(mdout0_2_15), .DOA16(mdout0_2_16), .DOA17(mdout0_2_17), .DOB0(mdout1_2_0), 
        .DOB1(mdout1_2_1), .DOB2(mdout1_2_2), .DOB3(mdout1_2_3), .DOB4(mdout1_2_4), 
        .DOB5(mdout1_2_5), .DOB6(mdout1_2_6), .DOB7(mdout1_2_7), .DOB8(mdout1_2_8), 
        .DOB9(mdout1_2_9), .DOB10(mdout1_2_10), .DOB11(mdout1_2_11), .DOB12(mdout1_2_12), 
        .DOB13(mdout1_2_13), .DOB14(mdout1_2_14), .DOB15(mdout1_2_15), .DOB16(mdout1_2_16), 
        .DOB17(mdout1_2_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_3_0_12.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_3_0_12.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_3_0_12.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_3_0_12.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_3_0_12.GSR = "DISABLED" ;
    defparam ram_dp_true_3_0_12.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_3_0_12.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_3_0_12.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_3_0_12.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_3_0_12 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec6_p03), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec7_p13), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_3_0), .DOA1(mdout0_3_1), .DOA2(mdout0_3_2), 
        .DOA3(mdout0_3_3), .DOA4(mdout0_3_4), .DOA5(mdout0_3_5), .DOA6(mdout0_3_6), 
        .DOA7(mdout0_3_7), .DOA8(mdout0_3_8), .DOA9(mdout0_3_9), .DOA10(mdout0_3_10), 
        .DOA11(mdout0_3_11), .DOA12(mdout0_3_12), .DOA13(mdout0_3_13), .DOA14(mdout0_3_14), 
        .DOA15(mdout0_3_15), .DOA16(mdout0_3_16), .DOA17(mdout0_3_17), .DOB0(mdout1_3_0), 
        .DOB1(mdout1_3_1), .DOB2(mdout1_3_2), .DOB3(mdout1_3_3), .DOB4(mdout1_3_4), 
        .DOB5(mdout1_3_5), .DOB6(mdout1_3_6), .DOB7(mdout1_3_7), .DOB8(mdout1_3_8), 
        .DOB9(mdout1_3_9), .DOB10(mdout1_3_10), .DOB11(mdout1_3_11), .DOB12(mdout1_3_12), 
        .DOB13(mdout1_3_13), .DOB14(mdout1_3_14), .DOB15(mdout1_3_15), .DOB16(mdout1_3_16), 
        .DOB17(mdout1_3_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_4_0_11.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_4_0_11.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_4_0_11.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_4_0_11.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_4_0_11.GSR = "DISABLED" ;
    defparam ram_dp_true_4_0_11.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_4_0_11.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_4_0_11.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_4_0_11.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_4_0_11 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec8_p04), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec9_p14), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_4_0), .DOA1(mdout0_4_1), .DOA2(mdout0_4_2), 
        .DOA3(mdout0_4_3), .DOA4(mdout0_4_4), .DOA5(mdout0_4_5), .DOA6(mdout0_4_6), 
        .DOA7(mdout0_4_7), .DOA8(mdout0_4_8), .DOA9(mdout0_4_9), .DOA10(mdout0_4_10), 
        .DOA11(mdout0_4_11), .DOA12(mdout0_4_12), .DOA13(mdout0_4_13), .DOA14(mdout0_4_14), 
        .DOA15(mdout0_4_15), .DOA16(mdout0_4_16), .DOA17(mdout0_4_17), .DOB0(mdout1_4_0), 
        .DOB1(mdout1_4_1), .DOB2(mdout1_4_2), .DOB3(mdout1_4_3), .DOB4(mdout1_4_4), 
        .DOB5(mdout1_4_5), .DOB6(mdout1_4_6), .DOB7(mdout1_4_7), .DOB8(mdout1_4_8), 
        .DOB9(mdout1_4_9), .DOB10(mdout1_4_10), .DOB11(mdout1_4_11), .DOB12(mdout1_4_12), 
        .DOB13(mdout1_4_13), .DOB14(mdout1_4_14), .DOB15(mdout1_4_15), .DOB16(mdout1_4_16), 
        .DOB17(mdout1_4_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_5_0_10.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_5_0_10.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_5_0_10.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_5_0_10.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_5_0_10.GSR = "DISABLED" ;
    defparam ram_dp_true_5_0_10.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_5_0_10.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_5_0_10.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_5_0_10.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_5_0_10 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec10_p05), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec11_p15), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_5_0), .DOA1(mdout0_5_1), .DOA2(mdout0_5_2), 
        .DOA3(mdout0_5_3), .DOA4(mdout0_5_4), .DOA5(mdout0_5_5), .DOA6(mdout0_5_6), 
        .DOA7(mdout0_5_7), .DOA8(mdout0_5_8), .DOA9(mdout0_5_9), .DOA10(mdout0_5_10), 
        .DOA11(mdout0_5_11), .DOA12(mdout0_5_12), .DOA13(mdout0_5_13), .DOA14(mdout0_5_14), 
        .DOA15(mdout0_5_15), .DOA16(mdout0_5_16), .DOA17(mdout0_5_17), .DOB0(mdout1_5_0), 
        .DOB1(mdout1_5_1), .DOB2(mdout1_5_2), .DOB3(mdout1_5_3), .DOB4(mdout1_5_4), 
        .DOB5(mdout1_5_5), .DOB6(mdout1_5_6), .DOB7(mdout1_5_7), .DOB8(mdout1_5_8), 
        .DOB9(mdout1_5_9), .DOB10(mdout1_5_10), .DOB11(mdout1_5_11), .DOB12(mdout1_5_12), 
        .DOB13(mdout1_5_13), .DOB14(mdout1_5_14), .DOB15(mdout1_5_15), .DOB16(mdout1_5_16), 
        .DOB17(mdout1_5_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_6_0_9.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_6_0_9.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_6_0_9.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_6_0_9.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_6_0_9.GSR = "DISABLED" ;
    defparam ram_dp_true_6_0_9.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_6_0_9.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_6_0_9.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_6_0_9.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_6_0_9 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec12_p06), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec13_p16), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_6_0), .DOA1(mdout0_6_1), .DOA2(mdout0_6_2), 
        .DOA3(mdout0_6_3), .DOA4(mdout0_6_4), .DOA5(mdout0_6_5), .DOA6(mdout0_6_6), 
        .DOA7(mdout0_6_7), .DOA8(mdout0_6_8), .DOA9(mdout0_6_9), .DOA10(mdout0_6_10), 
        .DOA11(mdout0_6_11), .DOA12(mdout0_6_12), .DOA13(mdout0_6_13), .DOA14(mdout0_6_14), 
        .DOA15(mdout0_6_15), .DOA16(mdout0_6_16), .DOA17(mdout0_6_17), .DOB0(mdout1_6_0), 
        .DOB1(mdout1_6_1), .DOB2(mdout1_6_2), .DOB3(mdout1_6_3), .DOB4(mdout1_6_4), 
        .DOB5(mdout1_6_5), .DOB6(mdout1_6_6), .DOB7(mdout1_6_7), .DOB8(mdout1_6_8), 
        .DOB9(mdout1_6_9), .DOB10(mdout1_6_10), .DOB11(mdout1_6_11), .DOB12(mdout1_6_12), 
        .DOB13(mdout1_6_13), .DOB14(mdout1_6_14), .DOB15(mdout1_6_15), .DOB16(mdout1_6_16), 
        .DOB17(mdout1_6_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_7_0_8.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_7_0_8.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_7_0_8.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_7_0_8.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_7_0_8.GSR = "DISABLED" ;
    defparam ram_dp_true_7_0_8.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_7_0_8.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_7_0_8.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_7_0_8.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_7_0_8 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec14_p07), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec15_p17), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_7_0), .DOA1(mdout0_7_1), .DOA2(mdout0_7_2), 
        .DOA3(mdout0_7_3), .DOA4(mdout0_7_4), .DOA5(mdout0_7_5), .DOA6(mdout0_7_6), 
        .DOA7(mdout0_7_7), .DOA8(mdout0_7_8), .DOA9(mdout0_7_9), .DOA10(mdout0_7_10), 
        .DOA11(mdout0_7_11), .DOA12(mdout0_7_12), .DOA13(mdout0_7_13), .DOA14(mdout0_7_14), 
        .DOA15(mdout0_7_15), .DOA16(mdout0_7_16), .DOA17(mdout0_7_17), .DOB0(mdout1_7_0), 
        .DOB1(mdout1_7_1), .DOB2(mdout1_7_2), .DOB3(mdout1_7_3), .DOB4(mdout1_7_4), 
        .DOB5(mdout1_7_5), .DOB6(mdout1_7_6), .DOB7(mdout1_7_7), .DOB8(mdout1_7_8), 
        .DOB9(mdout1_7_9), .DOB10(mdout1_7_10), .DOB11(mdout1_7_11), .DOB12(mdout1_7_12), 
        .DOB13(mdout1_7_13), .DOB14(mdout1_7_14), .DOB15(mdout1_7_15), .DOB16(mdout1_7_16), 
        .DOB17(mdout1_7_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_8_0_7.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_8_0_7.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_8_0_7.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_8_0_7.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_8_0_7.GSR = "DISABLED" ;
    defparam ram_dp_true_8_0_7.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_8_0_7.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_8_0_7.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_8_0_7.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_8_0_7 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec16_p08), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec17_p18), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_8_0), .DOA1(mdout0_8_1), .DOA2(mdout0_8_2), 
        .DOA3(mdout0_8_3), .DOA4(mdout0_8_4), .DOA5(mdout0_8_5), .DOA6(mdout0_8_6), 
        .DOA7(mdout0_8_7), .DOA8(mdout0_8_8), .DOA9(mdout0_8_9), .DOA10(mdout0_8_10), 
        .DOA11(mdout0_8_11), .DOA12(mdout0_8_12), .DOA13(mdout0_8_13), .DOA14(mdout0_8_14), 
        .DOA15(mdout0_8_15), .DOA16(mdout0_8_16), .DOA17(mdout0_8_17), .DOB0(mdout1_8_0), 
        .DOB1(mdout1_8_1), .DOB2(mdout1_8_2), .DOB3(mdout1_8_3), .DOB4(mdout1_8_4), 
        .DOB5(mdout1_8_5), .DOB6(mdout1_8_6), .DOB7(mdout1_8_7), .DOB8(mdout1_8_8), 
        .DOB9(mdout1_8_9), .DOB10(mdout1_8_10), .DOB11(mdout1_8_11), .DOB12(mdout1_8_12), 
        .DOB13(mdout1_8_13), .DOB14(mdout1_8_14), .DOB15(mdout1_8_15), .DOB16(mdout1_8_16), 
        .DOB17(mdout1_8_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_9_0_6.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_9_0_6.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_9_0_6.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_9_0_6.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_9_0_6.GSR = "DISABLED" ;
    defparam ram_dp_true_9_0_6.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_9_0_6.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_9_0_6.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_9_0_6.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_9_0_6 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec18_p09), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec19_p19), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_9_0), .DOA1(mdout0_9_1), .DOA2(mdout0_9_2), 
        .DOA3(mdout0_9_3), .DOA4(mdout0_9_4), .DOA5(mdout0_9_5), .DOA6(mdout0_9_6), 
        .DOA7(mdout0_9_7), .DOA8(mdout0_9_8), .DOA9(mdout0_9_9), .DOA10(mdout0_9_10), 
        .DOA11(mdout0_9_11), .DOA12(mdout0_9_12), .DOA13(mdout0_9_13), .DOA14(mdout0_9_14), 
        .DOA15(mdout0_9_15), .DOA16(mdout0_9_16), .DOA17(mdout0_9_17), .DOB0(mdout1_9_0), 
        .DOB1(mdout1_9_1), .DOB2(mdout1_9_2), .DOB3(mdout1_9_3), .DOB4(mdout1_9_4), 
        .DOB5(mdout1_9_5), .DOB6(mdout1_9_6), .DOB7(mdout1_9_7), .DOB8(mdout1_9_8), 
        .DOB9(mdout1_9_9), .DOB10(mdout1_9_10), .DOB11(mdout1_9_11), .DOB12(mdout1_9_12), 
        .DOB13(mdout1_9_13), .DOB14(mdout1_9_14), .DOB15(mdout1_9_15), .DOB16(mdout1_9_16), 
        .DOB17(mdout1_9_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_10_0_5.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_10_0_5.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_10_0_5.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_10_0_5.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_10_0_5.GSR = "DISABLED" ;
    defparam ram_dp_true_10_0_5.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_10_0_5.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_10_0_5.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_10_0_5.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_10_0_5 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec20_p010), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec21_p110), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_10_0), .DOA1(mdout0_10_1), .DOA2(mdout0_10_2), 
        .DOA3(mdout0_10_3), .DOA4(mdout0_10_4), .DOA5(mdout0_10_5), .DOA6(mdout0_10_6), 
        .DOA7(mdout0_10_7), .DOA8(mdout0_10_8), .DOA9(mdout0_10_9), .DOA10(mdout0_10_10), 
        .DOA11(mdout0_10_11), .DOA12(mdout0_10_12), .DOA13(mdout0_10_13), 
        .DOA14(mdout0_10_14), .DOA15(mdout0_10_15), .DOA16(mdout0_10_16), 
        .DOA17(mdout0_10_17), .DOB0(mdout1_10_0), .DOB1(mdout1_10_1), .DOB2(mdout1_10_2), 
        .DOB3(mdout1_10_3), .DOB4(mdout1_10_4), .DOB5(mdout1_10_5), .DOB6(mdout1_10_6), 
        .DOB7(mdout1_10_7), .DOB8(mdout1_10_8), .DOB9(mdout1_10_9), .DOB10(mdout1_10_10), 
        .DOB11(mdout1_10_11), .DOB12(mdout1_10_12), .DOB13(mdout1_10_13), 
        .DOB14(mdout1_10_14), .DOB15(mdout1_10_15), .DOB16(mdout1_10_16), 
        .DOB17(mdout1_10_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_11_0_4.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_11_0_4.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_11_0_4.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_11_0_4.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_11_0_4.GSR = "DISABLED" ;
    defparam ram_dp_true_11_0_4.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_11_0_4.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_11_0_4.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_11_0_4.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_11_0_4 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec22_p011), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec23_p111), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_11_0), .DOA1(mdout0_11_1), .DOA2(mdout0_11_2), 
        .DOA3(mdout0_11_3), .DOA4(mdout0_11_4), .DOA5(mdout0_11_5), .DOA6(mdout0_11_6), 
        .DOA7(mdout0_11_7), .DOA8(mdout0_11_8), .DOA9(mdout0_11_9), .DOA10(mdout0_11_10), 
        .DOA11(mdout0_11_11), .DOA12(mdout0_11_12), .DOA13(mdout0_11_13), 
        .DOA14(mdout0_11_14), .DOA15(mdout0_11_15), .DOA16(mdout0_11_16), 
        .DOA17(mdout0_11_17), .DOB0(mdout1_11_0), .DOB1(mdout1_11_1), .DOB2(mdout1_11_2), 
        .DOB3(mdout1_11_3), .DOB4(mdout1_11_4), .DOB5(mdout1_11_5), .DOB6(mdout1_11_6), 
        .DOB7(mdout1_11_7), .DOB8(mdout1_11_8), .DOB9(mdout1_11_9), .DOB10(mdout1_11_10), 
        .DOB11(mdout1_11_11), .DOB12(mdout1_11_12), .DOB13(mdout1_11_13), 
        .DOB14(mdout1_11_14), .DOB15(mdout1_11_15), .DOB16(mdout1_11_16), 
        .DOB17(mdout1_11_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_12_0_3.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_12_0_3.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_12_0_3.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_12_0_3.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_12_0_3.GSR = "DISABLED" ;
    defparam ram_dp_true_12_0_3.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_12_0_3.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_12_0_3.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_12_0_3.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_12_0_3 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec24_p012), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec25_p112), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_12_0), .DOA1(mdout0_12_1), .DOA2(mdout0_12_2), 
        .DOA3(mdout0_12_3), .DOA4(mdout0_12_4), .DOA5(mdout0_12_5), .DOA6(mdout0_12_6), 
        .DOA7(mdout0_12_7), .DOA8(mdout0_12_8), .DOA9(mdout0_12_9), .DOA10(mdout0_12_10), 
        .DOA11(mdout0_12_11), .DOA12(mdout0_12_12), .DOA13(mdout0_12_13), 
        .DOA14(mdout0_12_14), .DOA15(mdout0_12_15), .DOA16(mdout0_12_16), 
        .DOA17(mdout0_12_17), .DOB0(mdout1_12_0), .DOB1(mdout1_12_1), .DOB2(mdout1_12_2), 
        .DOB3(mdout1_12_3), .DOB4(mdout1_12_4), .DOB5(mdout1_12_5), .DOB6(mdout1_12_6), 
        .DOB7(mdout1_12_7), .DOB8(mdout1_12_8), .DOB9(mdout1_12_9), .DOB10(mdout1_12_10), 
        .DOB11(mdout1_12_11), .DOB12(mdout1_12_12), .DOB13(mdout1_12_13), 
        .DOB14(mdout1_12_14), .DOB15(mdout1_12_15), .DOB16(mdout1_12_16), 
        .DOB17(mdout1_12_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_13_0_2.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_13_0_2.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_13_0_2.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_13_0_2.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_13_0_2.GSR = "DISABLED" ;
    defparam ram_dp_true_13_0_2.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_13_0_2.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_13_0_2.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_13_0_2.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_13_0_2 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec26_p013), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec27_p113), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_13_0), .DOA1(mdout0_13_1), .DOA2(mdout0_13_2), 
        .DOA3(mdout0_13_3), .DOA4(mdout0_13_4), .DOA5(mdout0_13_5), .DOA6(mdout0_13_6), 
        .DOA7(mdout0_13_7), .DOA8(mdout0_13_8), .DOA9(mdout0_13_9), .DOA10(mdout0_13_10), 
        .DOA11(mdout0_13_11), .DOA12(mdout0_13_12), .DOA13(mdout0_13_13), 
        .DOA14(mdout0_13_14), .DOA15(mdout0_13_15), .DOA16(mdout0_13_16), 
        .DOA17(mdout0_13_17), .DOB0(mdout1_13_0), .DOB1(mdout1_13_1), .DOB2(mdout1_13_2), 
        .DOB3(mdout1_13_3), .DOB4(mdout1_13_4), .DOB5(mdout1_13_5), .DOB6(mdout1_13_6), 
        .DOB7(mdout1_13_7), .DOB8(mdout1_13_8), .DOB9(mdout1_13_9), .DOB10(mdout1_13_10), 
        .DOB11(mdout1_13_11), .DOB12(mdout1_13_12), .DOB13(mdout1_13_13), 
        .DOB14(mdout1_13_14), .DOB15(mdout1_13_15), .DOB16(mdout1_13_16), 
        .DOB17(mdout1_13_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_14_0_1.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_14_0_1.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_14_0_1.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_14_0_1.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_14_0_1.GSR = "DISABLED" ;
    defparam ram_dp_true_14_0_1.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_14_0_1.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_14_0_1.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_14_0_1.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_14_0_1 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec28_p014), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec29_p114), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_14_0), .DOA1(mdout0_14_1), .DOA2(mdout0_14_2), 
        .DOA3(mdout0_14_3), .DOA4(mdout0_14_4), .DOA5(mdout0_14_5), .DOA6(mdout0_14_6), 
        .DOA7(mdout0_14_7), .DOA8(mdout0_14_8), .DOA9(mdout0_14_9), .DOA10(mdout0_14_10), 
        .DOA11(mdout0_14_11), .DOA12(mdout0_14_12), .DOA13(mdout0_14_13), 
        .DOA14(mdout0_14_14), .DOA15(mdout0_14_15), .DOA16(mdout0_14_16), 
        .DOA17(mdout0_14_17), .DOB0(mdout1_14_0), .DOB1(mdout1_14_1), .DOB2(mdout1_14_2), 
        .DOB3(mdout1_14_3), .DOB4(mdout1_14_4), .DOB5(mdout1_14_5), .DOB6(mdout1_14_6), 
        .DOB7(mdout1_14_7), .DOB8(mdout1_14_8), .DOB9(mdout1_14_9), .DOB10(mdout1_14_10), 
        .DOB11(mdout1_14_11), .DOB12(mdout1_14_12), .DOB13(mdout1_14_13), 
        .DOB14(mdout1_14_14), .DOB15(mdout1_14_15), .DOB16(mdout1_14_16), 
        .DOB17(mdout1_14_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dp_true_15_0_0.CSDECODE_B = "0b001" ;
    defparam ram_dp_true_15_0_0.CSDECODE_A = "0b001" ;
    defparam ram_dp_true_15_0_0.WRITEMODE_B = "NORMAL" ;
    defparam ram_dp_true_15_0_0.WRITEMODE_A = "NORMAL" ;
    defparam ram_dp_true_15_0_0.GSR = "DISABLED" ;
    defparam ram_dp_true_15_0_0.REGMODE_B = "NOREG" ;
    defparam ram_dp_true_15_0_0.REGMODE_A = "NOREG" ;
    defparam ram_dp_true_15_0_0.DATA_WIDTH_B = 18 ;
    defparam ram_dp_true_15_0_0.DATA_WIDTH_A = 18 ;
    DP16KC ram_dp_true_15_0_0 (.DIA0(DataInA[0]), .DIA1(DataInA[1]), .DIA2(DataInA[2]), 
        .DIA3(DataInA[3]), .DIA4(DataInA[4]), .DIA5(DataInA[5]), .DIA6(DataInA[6]), 
        .DIA7(DataInA[7]), .DIA8(scuba_vlo), .DIA9(DataInA[8]), .DIA10(DataInA[9]), 
        .DIA11(DataInA[10]), .DIA12(DataInA[11]), .DIA13(DataInA[12]), .DIA14(DataInA[13]), 
        .DIA15(DataInA[14]), .DIA16(DataInA[15]), .DIA17(scuba_vlo), .ADA0(ByteEnA[0]), 
        .ADA1(ByteEnA[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(AddressA[0]), 
        .ADA5(AddressA[1]), .ADA6(AddressA[2]), .ADA7(AddressA[3]), .ADA8(AddressA[4]), 
        .ADA9(AddressA[5]), .ADA10(AddressA[6]), .ADA11(AddressA[7]), .ADA12(AddressA[8]), 
        .ADA13(AddressA[9]), .CEA(ClockEnA), .CLKA(ClockA), .OCEA(ClockEnA), 
        .WEA(WrA), .CSA0(dec30_p015), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(ResetA), .DIB0(DataInB[0]), .DIB1(DataInB[1]), .DIB2(DataInB[2]), 
        .DIB3(DataInB[3]), .DIB4(DataInB[4]), .DIB5(DataInB[5]), .DIB6(DataInB[6]), 
        .DIB7(DataInB[7]), .DIB8(scuba_vlo), .DIB9(DataInB[8]), .DIB10(DataInB[9]), 
        .DIB11(DataInB[10]), .DIB12(DataInB[11]), .DIB13(DataInB[12]), .DIB14(DataInB[13]), 
        .DIB15(DataInB[14]), .DIB16(DataInB[15]), .DIB17(scuba_vlo), .ADB0(ByteEnB[0]), 
        .ADB1(ByteEnB[1]), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(AddressB[0]), 
        .ADB5(AddressB[1]), .ADB6(AddressB[2]), .ADB7(AddressB[3]), .ADB8(AddressB[4]), 
        .ADB9(AddressB[5]), .ADB10(AddressB[6]), .ADB11(AddressB[7]), .ADB12(AddressB[8]), 
        .ADB13(AddressB[9]), .CEB(ClockEnB), .CLKB(ClockB), .OCEB(ClockEnB), 
        .WEB(WrB), .CSB0(dec31_p115), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(ResetB), .DOA0(mdout0_15_0), .DOA1(mdout0_15_1), .DOA2(mdout0_15_2), 
        .DOA3(mdout0_15_3), .DOA4(mdout0_15_4), .DOA5(mdout0_15_5), .DOA6(mdout0_15_6), 
        .DOA7(mdout0_15_7), .DOA8(mdout0_15_8), .DOA9(mdout0_15_9), .DOA10(mdout0_15_10), 
        .DOA11(mdout0_15_11), .DOA12(mdout0_15_12), .DOA13(mdout0_15_13), 
        .DOA14(mdout0_15_14), .DOA15(mdout0_15_15), .DOA16(mdout0_15_16), 
        .DOA17(mdout0_15_17), .DOB0(mdout1_15_0), .DOB1(mdout1_15_1), .DOB2(mdout1_15_2), 
        .DOB3(mdout1_15_3), .DOB4(mdout1_15_4), .DOB5(mdout1_15_5), .DOB6(mdout1_15_6), 
        .DOB7(mdout1_15_7), .DOB8(mdout1_15_8), .DOB9(mdout1_15_9), .DOB10(mdout1_15_10), 
        .DOB11(mdout1_15_11), .DOB12(mdout1_15_12), .DOB13(mdout1_15_13), 
        .DOB14(mdout1_15_14), .DOB15(mdout1_15_15), .DOB16(mdout1_15_16), 
        .DOB17(mdout1_15_17))
             /* synthesis MEM_LPC_FILE="ram_dp_true.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    FD1P3DX FF_7 (.D(AddressA[10]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr010_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(AddressA[11]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr011_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(AddressA[12]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr012_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(AddressA[13]), .SP(wren0_inv_g), .CK(ClockA), .CD(scuba_vlo), 
        .Q(addr013_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(AddressB[10]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr110_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(AddressB[11]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr111_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(AddressB[12]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr112_ff))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FD1P3DX FF_0 (.D(AddressB[13]), .SP(wren1_inv_g), .CK(ClockB), .CD(scuba_vlo), 
        .Q(addr113_ff))
             /* synthesis GSR="ENABLED" */;

    MUX161 mux_31 (.D0(mdout0_0_0), .D1(mdout0_1_0), .D2(mdout0_2_0), .D3(mdout0_3_0), 
        .D4(mdout0_4_0), .D5(mdout0_5_0), .D6(mdout0_6_0), .D7(mdout0_7_0), 
        .D8(mdout0_8_0), .D9(mdout0_9_0), .D10(mdout0_10_0), .D11(mdout0_11_0), 
        .D12(mdout0_12_0), .D13(mdout0_13_0), .D14(mdout0_14_0), .D15(mdout0_15_0), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[0]));

    MUX161 mux_30 (.D0(mdout0_0_1), .D1(mdout0_1_1), .D2(mdout0_2_1), .D3(mdout0_3_1), 
        .D4(mdout0_4_1), .D5(mdout0_5_1), .D6(mdout0_6_1), .D7(mdout0_7_1), 
        .D8(mdout0_8_1), .D9(mdout0_9_1), .D10(mdout0_10_1), .D11(mdout0_11_1), 
        .D12(mdout0_12_1), .D13(mdout0_13_1), .D14(mdout0_14_1), .D15(mdout0_15_1), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[1]));

    MUX161 mux_29 (.D0(mdout0_0_2), .D1(mdout0_1_2), .D2(mdout0_2_2), .D3(mdout0_3_2), 
        .D4(mdout0_4_2), .D5(mdout0_5_2), .D6(mdout0_6_2), .D7(mdout0_7_2), 
        .D8(mdout0_8_2), .D9(mdout0_9_2), .D10(mdout0_10_2), .D11(mdout0_11_2), 
        .D12(mdout0_12_2), .D13(mdout0_13_2), .D14(mdout0_14_2), .D15(mdout0_15_2), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[2]));

    MUX161 mux_28 (.D0(mdout0_0_3), .D1(mdout0_1_3), .D2(mdout0_2_3), .D3(mdout0_3_3), 
        .D4(mdout0_4_3), .D5(mdout0_5_3), .D6(mdout0_6_3), .D7(mdout0_7_3), 
        .D8(mdout0_8_3), .D9(mdout0_9_3), .D10(mdout0_10_3), .D11(mdout0_11_3), 
        .D12(mdout0_12_3), .D13(mdout0_13_3), .D14(mdout0_14_3), .D15(mdout0_15_3), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[3]));

    MUX161 mux_27 (.D0(mdout0_0_4), .D1(mdout0_1_4), .D2(mdout0_2_4), .D3(mdout0_3_4), 
        .D4(mdout0_4_4), .D5(mdout0_5_4), .D6(mdout0_6_4), .D7(mdout0_7_4), 
        .D8(mdout0_8_4), .D9(mdout0_9_4), .D10(mdout0_10_4), .D11(mdout0_11_4), 
        .D12(mdout0_12_4), .D13(mdout0_13_4), .D14(mdout0_14_4), .D15(mdout0_15_4), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[4]));

    MUX161 mux_26 (.D0(mdout0_0_5), .D1(mdout0_1_5), .D2(mdout0_2_5), .D3(mdout0_3_5), 
        .D4(mdout0_4_5), .D5(mdout0_5_5), .D6(mdout0_6_5), .D7(mdout0_7_5), 
        .D8(mdout0_8_5), .D9(mdout0_9_5), .D10(mdout0_10_5), .D11(mdout0_11_5), 
        .D12(mdout0_12_5), .D13(mdout0_13_5), .D14(mdout0_14_5), .D15(mdout0_15_5), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[5]));

    MUX161 mux_25 (.D0(mdout0_0_6), .D1(mdout0_1_6), .D2(mdout0_2_6), .D3(mdout0_3_6), 
        .D4(mdout0_4_6), .D5(mdout0_5_6), .D6(mdout0_6_6), .D7(mdout0_7_6), 
        .D8(mdout0_8_6), .D9(mdout0_9_6), .D10(mdout0_10_6), .D11(mdout0_11_6), 
        .D12(mdout0_12_6), .D13(mdout0_13_6), .D14(mdout0_14_6), .D15(mdout0_15_6), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[6]));

    MUX161 mux_24 (.D0(mdout0_0_7), .D1(mdout0_1_7), .D2(mdout0_2_7), .D3(mdout0_3_7), 
        .D4(mdout0_4_7), .D5(mdout0_5_7), .D6(mdout0_6_7), .D7(mdout0_7_7), 
        .D8(mdout0_8_7), .D9(mdout0_9_7), .D10(mdout0_10_7), .D11(mdout0_11_7), 
        .D12(mdout0_12_7), .D13(mdout0_13_7), .D14(mdout0_14_7), .D15(mdout0_15_7), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[7]));

    MUX161 mux_23 (.D0(mdout0_0_9), .D1(mdout0_1_9), .D2(mdout0_2_9), .D3(mdout0_3_9), 
        .D4(mdout0_4_9), .D5(mdout0_5_9), .D6(mdout0_6_9), .D7(mdout0_7_9), 
        .D8(mdout0_8_9), .D9(mdout0_9_9), .D10(mdout0_10_9), .D11(mdout0_11_9), 
        .D12(mdout0_12_9), .D13(mdout0_13_9), .D14(mdout0_14_9), .D15(mdout0_15_9), 
        .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), .SD4(addr013_ff), 
        .Z(QA[8]));

    MUX161 mux_22 (.D0(mdout0_0_10), .D1(mdout0_1_10), .D2(mdout0_2_10), 
        .D3(mdout0_3_10), .D4(mdout0_4_10), .D5(mdout0_5_10), .D6(mdout0_6_10), 
        .D7(mdout0_7_10), .D8(mdout0_8_10), .D9(mdout0_9_10), .D10(mdout0_10_10), 
        .D11(mdout0_11_10), .D12(mdout0_12_10), .D13(mdout0_13_10), .D14(mdout0_14_10), 
        .D15(mdout0_15_10), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[9]));

    MUX161 mux_21 (.D0(mdout0_0_11), .D1(mdout0_1_11), .D2(mdout0_2_11), 
        .D3(mdout0_3_11), .D4(mdout0_4_11), .D5(mdout0_5_11), .D6(mdout0_6_11), 
        .D7(mdout0_7_11), .D8(mdout0_8_11), .D9(mdout0_9_11), .D10(mdout0_10_11), 
        .D11(mdout0_11_11), .D12(mdout0_12_11), .D13(mdout0_13_11), .D14(mdout0_14_11), 
        .D15(mdout0_15_11), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[10]));

    MUX161 mux_20 (.D0(mdout0_0_12), .D1(mdout0_1_12), .D2(mdout0_2_12), 
        .D3(mdout0_3_12), .D4(mdout0_4_12), .D5(mdout0_5_12), .D6(mdout0_6_12), 
        .D7(mdout0_7_12), .D8(mdout0_8_12), .D9(mdout0_9_12), .D10(mdout0_10_12), 
        .D11(mdout0_11_12), .D12(mdout0_12_12), .D13(mdout0_13_12), .D14(mdout0_14_12), 
        .D15(mdout0_15_12), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[11]));

    MUX161 mux_19 (.D0(mdout0_0_13), .D1(mdout0_1_13), .D2(mdout0_2_13), 
        .D3(mdout0_3_13), .D4(mdout0_4_13), .D5(mdout0_5_13), .D6(mdout0_6_13), 
        .D7(mdout0_7_13), .D8(mdout0_8_13), .D9(mdout0_9_13), .D10(mdout0_10_13), 
        .D11(mdout0_11_13), .D12(mdout0_12_13), .D13(mdout0_13_13), .D14(mdout0_14_13), 
        .D15(mdout0_15_13), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[12]));

    MUX161 mux_18 (.D0(mdout0_0_14), .D1(mdout0_1_14), .D2(mdout0_2_14), 
        .D3(mdout0_3_14), .D4(mdout0_4_14), .D5(mdout0_5_14), .D6(mdout0_6_14), 
        .D7(mdout0_7_14), .D8(mdout0_8_14), .D9(mdout0_9_14), .D10(mdout0_10_14), 
        .D11(mdout0_11_14), .D12(mdout0_12_14), .D13(mdout0_13_14), .D14(mdout0_14_14), 
        .D15(mdout0_15_14), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[13]));

    MUX161 mux_17 (.D0(mdout0_0_15), .D1(mdout0_1_15), .D2(mdout0_2_15), 
        .D3(mdout0_3_15), .D4(mdout0_4_15), .D5(mdout0_5_15), .D6(mdout0_6_15), 
        .D7(mdout0_7_15), .D8(mdout0_8_15), .D9(mdout0_9_15), .D10(mdout0_10_15), 
        .D11(mdout0_11_15), .D12(mdout0_12_15), .D13(mdout0_13_15), .D14(mdout0_14_15), 
        .D15(mdout0_15_15), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[14]));

    MUX161 mux_16 (.D0(mdout0_0_16), .D1(mdout0_1_16), .D2(mdout0_2_16), 
        .D3(mdout0_3_16), .D4(mdout0_4_16), .D5(mdout0_5_16), .D6(mdout0_6_16), 
        .D7(mdout0_7_16), .D8(mdout0_8_16), .D9(mdout0_9_16), .D10(mdout0_10_16), 
        .D11(mdout0_11_16), .D12(mdout0_12_16), .D13(mdout0_13_16), .D14(mdout0_14_16), 
        .D15(mdout0_15_16), .SD1(addr010_ff), .SD2(addr011_ff), .SD3(addr012_ff), 
        .SD4(addr013_ff), .Z(QA[15]));

    MUX161 mux_15 (.D0(mdout1_0_0), .D1(mdout1_1_0), .D2(mdout1_2_0), .D3(mdout1_3_0), 
        .D4(mdout1_4_0), .D5(mdout1_5_0), .D6(mdout1_6_0), .D7(mdout1_7_0), 
        .D8(mdout1_8_0), .D9(mdout1_9_0), .D10(mdout1_10_0), .D11(mdout1_11_0), 
        .D12(mdout1_12_0), .D13(mdout1_13_0), .D14(mdout1_14_0), .D15(mdout1_15_0), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[0]));

    MUX161 mux_14 (.D0(mdout1_0_1), .D1(mdout1_1_1), .D2(mdout1_2_1), .D3(mdout1_3_1), 
        .D4(mdout1_4_1), .D5(mdout1_5_1), .D6(mdout1_6_1), .D7(mdout1_7_1), 
        .D8(mdout1_8_1), .D9(mdout1_9_1), .D10(mdout1_10_1), .D11(mdout1_11_1), 
        .D12(mdout1_12_1), .D13(mdout1_13_1), .D14(mdout1_14_1), .D15(mdout1_15_1), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[1]));

    MUX161 mux_13 (.D0(mdout1_0_2), .D1(mdout1_1_2), .D2(mdout1_2_2), .D3(mdout1_3_2), 
        .D4(mdout1_4_2), .D5(mdout1_5_2), .D6(mdout1_6_2), .D7(mdout1_7_2), 
        .D8(mdout1_8_2), .D9(mdout1_9_2), .D10(mdout1_10_2), .D11(mdout1_11_2), 
        .D12(mdout1_12_2), .D13(mdout1_13_2), .D14(mdout1_14_2), .D15(mdout1_15_2), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[2]));

    MUX161 mux_12 (.D0(mdout1_0_3), .D1(mdout1_1_3), .D2(mdout1_2_3), .D3(mdout1_3_3), 
        .D4(mdout1_4_3), .D5(mdout1_5_3), .D6(mdout1_6_3), .D7(mdout1_7_3), 
        .D8(mdout1_8_3), .D9(mdout1_9_3), .D10(mdout1_10_3), .D11(mdout1_11_3), 
        .D12(mdout1_12_3), .D13(mdout1_13_3), .D14(mdout1_14_3), .D15(mdout1_15_3), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[3]));

    MUX161 mux_11 (.D0(mdout1_0_4), .D1(mdout1_1_4), .D2(mdout1_2_4), .D3(mdout1_3_4), 
        .D4(mdout1_4_4), .D5(mdout1_5_4), .D6(mdout1_6_4), .D7(mdout1_7_4), 
        .D8(mdout1_8_4), .D9(mdout1_9_4), .D10(mdout1_10_4), .D11(mdout1_11_4), 
        .D12(mdout1_12_4), .D13(mdout1_13_4), .D14(mdout1_14_4), .D15(mdout1_15_4), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[4]));

    MUX161 mux_10 (.D0(mdout1_0_5), .D1(mdout1_1_5), .D2(mdout1_2_5), .D3(mdout1_3_5), 
        .D4(mdout1_4_5), .D5(mdout1_5_5), .D6(mdout1_6_5), .D7(mdout1_7_5), 
        .D8(mdout1_8_5), .D9(mdout1_9_5), .D10(mdout1_10_5), .D11(mdout1_11_5), 
        .D12(mdout1_12_5), .D13(mdout1_13_5), .D14(mdout1_14_5), .D15(mdout1_15_5), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[5]));

    MUX161 mux_9 (.D0(mdout1_0_6), .D1(mdout1_1_6), .D2(mdout1_2_6), .D3(mdout1_3_6), 
        .D4(mdout1_4_6), .D5(mdout1_5_6), .D6(mdout1_6_6), .D7(mdout1_7_6), 
        .D8(mdout1_8_6), .D9(mdout1_9_6), .D10(mdout1_10_6), .D11(mdout1_11_6), 
        .D12(mdout1_12_6), .D13(mdout1_13_6), .D14(mdout1_14_6), .D15(mdout1_15_6), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[6]));

    MUX161 mux_8 (.D0(mdout1_0_7), .D1(mdout1_1_7), .D2(mdout1_2_7), .D3(mdout1_3_7), 
        .D4(mdout1_4_7), .D5(mdout1_5_7), .D6(mdout1_6_7), .D7(mdout1_7_7), 
        .D8(mdout1_8_7), .D9(mdout1_9_7), .D10(mdout1_10_7), .D11(mdout1_11_7), 
        .D12(mdout1_12_7), .D13(mdout1_13_7), .D14(mdout1_14_7), .D15(mdout1_15_7), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[7]));

    MUX161 mux_7 (.D0(mdout1_0_9), .D1(mdout1_1_9), .D2(mdout1_2_9), .D3(mdout1_3_9), 
        .D4(mdout1_4_9), .D5(mdout1_5_9), .D6(mdout1_6_9), .D7(mdout1_7_9), 
        .D8(mdout1_8_9), .D9(mdout1_9_9), .D10(mdout1_10_9), .D11(mdout1_11_9), 
        .D12(mdout1_12_9), .D13(mdout1_13_9), .D14(mdout1_14_9), .D15(mdout1_15_9), 
        .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), .SD4(addr113_ff), 
        .Z(QB[8]));

    MUX161 mux_6 (.D0(mdout1_0_10), .D1(mdout1_1_10), .D2(mdout1_2_10), 
        .D3(mdout1_3_10), .D4(mdout1_4_10), .D5(mdout1_5_10), .D6(mdout1_6_10), 
        .D7(mdout1_7_10), .D8(mdout1_8_10), .D9(mdout1_9_10), .D10(mdout1_10_10), 
        .D11(mdout1_11_10), .D12(mdout1_12_10), .D13(mdout1_13_10), .D14(mdout1_14_10), 
        .D15(mdout1_15_10), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[9]));

    MUX161 mux_5 (.D0(mdout1_0_11), .D1(mdout1_1_11), .D2(mdout1_2_11), 
        .D3(mdout1_3_11), .D4(mdout1_4_11), .D5(mdout1_5_11), .D6(mdout1_6_11), 
        .D7(mdout1_7_11), .D8(mdout1_8_11), .D9(mdout1_9_11), .D10(mdout1_10_11), 
        .D11(mdout1_11_11), .D12(mdout1_12_11), .D13(mdout1_13_11), .D14(mdout1_14_11), 
        .D15(mdout1_15_11), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[10]));

    MUX161 mux_4 (.D0(mdout1_0_12), .D1(mdout1_1_12), .D2(mdout1_2_12), 
        .D3(mdout1_3_12), .D4(mdout1_4_12), .D5(mdout1_5_12), .D6(mdout1_6_12), 
        .D7(mdout1_7_12), .D8(mdout1_8_12), .D9(mdout1_9_12), .D10(mdout1_10_12), 
        .D11(mdout1_11_12), .D12(mdout1_12_12), .D13(mdout1_13_12), .D14(mdout1_14_12), 
        .D15(mdout1_15_12), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[11]));

    MUX161 mux_3 (.D0(mdout1_0_13), .D1(mdout1_1_13), .D2(mdout1_2_13), 
        .D3(mdout1_3_13), .D4(mdout1_4_13), .D5(mdout1_5_13), .D6(mdout1_6_13), 
        .D7(mdout1_7_13), .D8(mdout1_8_13), .D9(mdout1_9_13), .D10(mdout1_10_13), 
        .D11(mdout1_11_13), .D12(mdout1_12_13), .D13(mdout1_13_13), .D14(mdout1_14_13), 
        .D15(mdout1_15_13), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[12]));

    MUX161 mux_2 (.D0(mdout1_0_14), .D1(mdout1_1_14), .D2(mdout1_2_14), 
        .D3(mdout1_3_14), .D4(mdout1_4_14), .D5(mdout1_5_14), .D6(mdout1_6_14), 
        .D7(mdout1_7_14), .D8(mdout1_8_14), .D9(mdout1_9_14), .D10(mdout1_10_14), 
        .D11(mdout1_11_14), .D12(mdout1_12_14), .D13(mdout1_13_14), .D14(mdout1_14_14), 
        .D15(mdout1_15_14), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[13]));

    MUX161 mux_1 (.D0(mdout1_0_15), .D1(mdout1_1_15), .D2(mdout1_2_15), 
        .D3(mdout1_3_15), .D4(mdout1_4_15), .D5(mdout1_5_15), .D6(mdout1_6_15), 
        .D7(mdout1_7_15), .D8(mdout1_8_15), .D9(mdout1_9_15), .D10(mdout1_10_15), 
        .D11(mdout1_11_15), .D12(mdout1_12_15), .D13(mdout1_13_15), .D14(mdout1_14_15), 
        .D15(mdout1_15_15), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[14]));

    MUX161 mux_0 (.D0(mdout1_0_16), .D1(mdout1_1_16), .D2(mdout1_2_16), 
        .D3(mdout1_3_16), .D4(mdout1_4_16), .D5(mdout1_5_16), .D6(mdout1_6_16), 
        .D7(mdout1_7_16), .D8(mdout1_8_16), .D9(mdout1_9_16), .D10(mdout1_10_16), 
        .D11(mdout1_11_16), .D12(mdout1_12_16), .D13(mdout1_13_16), .D14(mdout1_14_16), 
        .D15(mdout1_15_16), .SD1(addr110_ff), .SD2(addr111_ff), .SD3(addr112_ff), 
        .SD4(addr113_ff), .Z(QB[15]));



    // exemplar begin
    // exemplar attribute ram_dp_true_0_0_15 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_0_0_15 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_0_0_15 RESETMODE SYNC
    // exemplar attribute ram_dp_true_1_0_14 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_1_0_14 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_1_0_14 RESETMODE SYNC
    // exemplar attribute ram_dp_true_2_0_13 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_2_0_13 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_2_0_13 RESETMODE SYNC
    // exemplar attribute ram_dp_true_3_0_12 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_3_0_12 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_3_0_12 RESETMODE SYNC
    // exemplar attribute ram_dp_true_4_0_11 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_4_0_11 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_4_0_11 RESETMODE SYNC
    // exemplar attribute ram_dp_true_5_0_10 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_5_0_10 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_5_0_10 RESETMODE SYNC
    // exemplar attribute ram_dp_true_6_0_9 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_6_0_9 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_6_0_9 RESETMODE SYNC
    // exemplar attribute ram_dp_true_7_0_8 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_7_0_8 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_7_0_8 RESETMODE SYNC
    // exemplar attribute ram_dp_true_8_0_7 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_8_0_7 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_8_0_7 RESETMODE SYNC
    // exemplar attribute ram_dp_true_9_0_6 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_9_0_6 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_9_0_6 RESETMODE SYNC
    // exemplar attribute ram_dp_true_10_0_5 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_10_0_5 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_10_0_5 RESETMODE SYNC
    // exemplar attribute ram_dp_true_11_0_4 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_11_0_4 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_11_0_4 RESETMODE SYNC
    // exemplar attribute ram_dp_true_12_0_3 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_12_0_3 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_12_0_3 RESETMODE SYNC
    // exemplar attribute ram_dp_true_13_0_2 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_13_0_2 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_13_0_2 RESETMODE SYNC
    // exemplar attribute ram_dp_true_14_0_1 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_14_0_1 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_14_0_1 RESETMODE SYNC
    // exemplar attribute ram_dp_true_15_0_0 MEM_LPC_FILE ram_dp_true.lpc
    // exemplar attribute ram_dp_true_15_0_0 MEM_INIT_FILE 
    // exemplar attribute ram_dp_true_15_0_0 RESETMODE SYNC
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
