/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* C:\lscc\diamond\2.2\ispfpga\bin\nt\scuba.exe -w -n ram_dq -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type bram -wp 10 -rp 1000 -addr_width 14 -data_width 16 -num_rows 16384 -writemode NORMAL -byte 8 -cascade 11 -e  */
/* Fri Jun 28 23:31:06 2013 */


`timescale 1 ns / 1 ps
module ram_dq (Clock, ClockEn, Reset, ByteEn, WE, Address, Data, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClockEn;
    input wire Reset;
    input wire [1:0] ByteEn;
    input wire WE;
    input wire [13:0] Address;
    input wire [15:0] Data;
    output wire [15:0] Q;

    wire addr13_inv;
    wire addr12_inv;
    wire addr11_inv;
    wire addr10_inv;
    wire wren_inv;
    wire mdout0_0_17;
    wire mdout0_0_8;
    wire dec0_p00;
    wire mdout0_1_17;
    wire mdout0_1_8;
    wire dec1_p01;
    wire mdout0_2_17;
    wire mdout0_2_8;
    wire dec2_p02;
    wire mdout0_3_17;
    wire mdout0_3_8;
    wire dec3_p03;
    wire mdout0_4_17;
    wire mdout0_4_8;
    wire dec4_p04;
    wire mdout0_5_17;
    wire mdout0_5_8;
    wire dec5_p05;
    wire mdout0_6_17;
    wire mdout0_6_8;
    wire dec6_p06;
    wire mdout0_7_17;
    wire mdout0_7_8;
    wire dec7_p07;
    wire mdout0_8_17;
    wire mdout0_8_8;
    wire dec8_p08;
    wire mdout0_9_17;
    wire mdout0_9_8;
    wire dec9_p09;
    wire mdout0_10_17;
    wire mdout0_10_8;
    wire dec10_p010;
    wire mdout0_11_17;
    wire mdout0_11_8;
    wire dec11_p011;
    wire mdout0_12_17;
    wire mdout0_12_8;
    wire dec12_p012;
    wire mdout0_13_17;
    wire mdout0_13_8;
    wire dec13_p013;
    wire mdout0_14_17;
    wire mdout0_14_8;
    wire dec14_p014;
    wire mdout0_15_17;
    wire mdout0_15_8;
    wire dec15_p015;
    wire scuba_vhi;
    wire scuba_vlo;
    wire wren_inv_g;
    wire mdout0_15_0;
    wire mdout0_14_0;
    wire mdout0_13_0;
    wire mdout0_12_0;
    wire mdout0_11_0;
    wire mdout0_10_0;
    wire mdout0_9_0;
    wire mdout0_8_0;
    wire mdout0_7_0;
    wire mdout0_6_0;
    wire mdout0_5_0;
    wire mdout0_4_0;
    wire mdout0_3_0;
    wire mdout0_2_0;
    wire mdout0_1_0;
    wire mdout0_0_0;
    wire mdout0_15_1;
    wire mdout0_14_1;
    wire mdout0_13_1;
    wire mdout0_12_1;
    wire mdout0_11_1;
    wire mdout0_10_1;
    wire mdout0_9_1;
    wire mdout0_8_1;
    wire mdout0_7_1;
    wire mdout0_6_1;
    wire mdout0_5_1;
    wire mdout0_4_1;
    wire mdout0_3_1;
    wire mdout0_2_1;
    wire mdout0_1_1;
    wire mdout0_0_1;
    wire mdout0_15_2;
    wire mdout0_14_2;
    wire mdout0_13_2;
    wire mdout0_12_2;
    wire mdout0_11_2;
    wire mdout0_10_2;
    wire mdout0_9_2;
    wire mdout0_8_2;
    wire mdout0_7_2;
    wire mdout0_6_2;
    wire mdout0_5_2;
    wire mdout0_4_2;
    wire mdout0_3_2;
    wire mdout0_2_2;
    wire mdout0_1_2;
    wire mdout0_0_2;
    wire mdout0_15_3;
    wire mdout0_14_3;
    wire mdout0_13_3;
    wire mdout0_12_3;
    wire mdout0_11_3;
    wire mdout0_10_3;
    wire mdout0_9_3;
    wire mdout0_8_3;
    wire mdout0_7_3;
    wire mdout0_6_3;
    wire mdout0_5_3;
    wire mdout0_4_3;
    wire mdout0_3_3;
    wire mdout0_2_3;
    wire mdout0_1_3;
    wire mdout0_0_3;
    wire mdout0_15_4;
    wire mdout0_14_4;
    wire mdout0_13_4;
    wire mdout0_12_4;
    wire mdout0_11_4;
    wire mdout0_10_4;
    wire mdout0_9_4;
    wire mdout0_8_4;
    wire mdout0_7_4;
    wire mdout0_6_4;
    wire mdout0_5_4;
    wire mdout0_4_4;
    wire mdout0_3_4;
    wire mdout0_2_4;
    wire mdout0_1_4;
    wire mdout0_0_4;
    wire mdout0_15_5;
    wire mdout0_14_5;
    wire mdout0_13_5;
    wire mdout0_12_5;
    wire mdout0_11_5;
    wire mdout0_10_5;
    wire mdout0_9_5;
    wire mdout0_8_5;
    wire mdout0_7_5;
    wire mdout0_6_5;
    wire mdout0_5_5;
    wire mdout0_4_5;
    wire mdout0_3_5;
    wire mdout0_2_5;
    wire mdout0_1_5;
    wire mdout0_0_5;
    wire mdout0_15_6;
    wire mdout0_14_6;
    wire mdout0_13_6;
    wire mdout0_12_6;
    wire mdout0_11_6;
    wire mdout0_10_6;
    wire mdout0_9_6;
    wire mdout0_8_6;
    wire mdout0_7_6;
    wire mdout0_6_6;
    wire mdout0_5_6;
    wire mdout0_4_6;
    wire mdout0_3_6;
    wire mdout0_2_6;
    wire mdout0_1_6;
    wire mdout0_0_6;
    wire mdout0_15_7;
    wire mdout0_14_7;
    wire mdout0_13_7;
    wire mdout0_12_7;
    wire mdout0_11_7;
    wire mdout0_10_7;
    wire mdout0_9_7;
    wire mdout0_8_7;
    wire mdout0_7_7;
    wire mdout0_6_7;
    wire mdout0_5_7;
    wire mdout0_4_7;
    wire mdout0_3_7;
    wire mdout0_2_7;
    wire mdout0_1_7;
    wire mdout0_0_7;
    wire mdout0_15_9;
    wire mdout0_14_9;
    wire mdout0_13_9;
    wire mdout0_12_9;
    wire mdout0_11_9;
    wire mdout0_10_9;
    wire mdout0_9_9;
    wire mdout0_8_9;
    wire mdout0_7_9;
    wire mdout0_6_9;
    wire mdout0_5_9;
    wire mdout0_4_9;
    wire mdout0_3_9;
    wire mdout0_2_9;
    wire mdout0_1_9;
    wire mdout0_0_9;
    wire mdout0_15_10;
    wire mdout0_14_10;
    wire mdout0_13_10;
    wire mdout0_12_10;
    wire mdout0_11_10;
    wire mdout0_10_10;
    wire mdout0_9_10;
    wire mdout0_8_10;
    wire mdout0_7_10;
    wire mdout0_6_10;
    wire mdout0_5_10;
    wire mdout0_4_10;
    wire mdout0_3_10;
    wire mdout0_2_10;
    wire mdout0_1_10;
    wire mdout0_0_10;
    wire mdout0_15_11;
    wire mdout0_14_11;
    wire mdout0_13_11;
    wire mdout0_12_11;
    wire mdout0_11_11;
    wire mdout0_10_11;
    wire mdout0_9_11;
    wire mdout0_8_11;
    wire mdout0_7_11;
    wire mdout0_6_11;
    wire mdout0_5_11;
    wire mdout0_4_11;
    wire mdout0_3_11;
    wire mdout0_2_11;
    wire mdout0_1_11;
    wire mdout0_0_11;
    wire mdout0_15_12;
    wire mdout0_14_12;
    wire mdout0_13_12;
    wire mdout0_12_12;
    wire mdout0_11_12;
    wire mdout0_10_12;
    wire mdout0_9_12;
    wire mdout0_8_12;
    wire mdout0_7_12;
    wire mdout0_6_12;
    wire mdout0_5_12;
    wire mdout0_4_12;
    wire mdout0_3_12;
    wire mdout0_2_12;
    wire mdout0_1_12;
    wire mdout0_0_12;
    wire mdout0_15_13;
    wire mdout0_14_13;
    wire mdout0_13_13;
    wire mdout0_12_13;
    wire mdout0_11_13;
    wire mdout0_10_13;
    wire mdout0_9_13;
    wire mdout0_8_13;
    wire mdout0_7_13;
    wire mdout0_6_13;
    wire mdout0_5_13;
    wire mdout0_4_13;
    wire mdout0_3_13;
    wire mdout0_2_13;
    wire mdout0_1_13;
    wire mdout0_0_13;
    wire mdout0_15_14;
    wire mdout0_14_14;
    wire mdout0_13_14;
    wire mdout0_12_14;
    wire mdout0_11_14;
    wire mdout0_10_14;
    wire mdout0_9_14;
    wire mdout0_8_14;
    wire mdout0_7_14;
    wire mdout0_6_14;
    wire mdout0_5_14;
    wire mdout0_4_14;
    wire mdout0_3_14;
    wire mdout0_2_14;
    wire mdout0_1_14;
    wire mdout0_0_14;
    wire mdout0_15_15;
    wire mdout0_14_15;
    wire mdout0_13_15;
    wire mdout0_12_15;
    wire mdout0_11_15;
    wire mdout0_10_15;
    wire mdout0_9_15;
    wire mdout0_8_15;
    wire mdout0_7_15;
    wire mdout0_6_15;
    wire mdout0_5_15;
    wire mdout0_4_15;
    wire mdout0_3_15;
    wire mdout0_2_15;
    wire mdout0_1_15;
    wire mdout0_0_15;
    wire addr13_ff;
    wire addr12_ff;
    wire addr11_ff;
    wire addr10_ff;
    wire mdout0_15_16;
    wire mdout0_14_16;
    wire mdout0_13_16;
    wire mdout0_12_16;
    wire mdout0_11_16;
    wire mdout0_10_16;
    wire mdout0_9_16;
    wire mdout0_8_16;
    wire mdout0_7_16;
    wire mdout0_6_16;
    wire mdout0_5_16;
    wire mdout0_4_16;
    wire mdout0_3_16;
    wire mdout0_2_16;
    wire mdout0_1_16;
    wire mdout0_0_16;

    INV INV_4 (.A(Address[10]), .Z(addr10_inv));

    INV INV_3 (.A(Address[11]), .Z(addr11_inv));

    INV INV_2 (.A(Address[12]), .Z(addr12_inv));

    INV INV_1 (.A(Address[13]), .Z(addr13_inv));

    defparam LUT4_15.initval =  16'h8000 ;
    ROM16X1A LUT4_15 (.AD3(addr10_inv), .AD2(addr11_inv), .AD1(addr12_inv), 
        .AD0(addr13_inv), .DO0(dec0_p00));

    defparam LUT4_14.initval =  16'h8000 ;
    ROM16X1A LUT4_14 (.AD3(Address[10]), .AD2(addr11_inv), .AD1(addr12_inv), 
        .AD0(addr13_inv), .DO0(dec1_p01));

    defparam LUT4_13.initval =  16'h8000 ;
    ROM16X1A LUT4_13 (.AD3(addr10_inv), .AD2(Address[11]), .AD1(addr12_inv), 
        .AD0(addr13_inv), .DO0(dec2_p02));

    defparam LUT4_12.initval =  16'h8000 ;
    ROM16X1A LUT4_12 (.AD3(Address[10]), .AD2(Address[11]), .AD1(addr12_inv), 
        .AD0(addr13_inv), .DO0(dec3_p03));

    defparam LUT4_11.initval =  16'h8000 ;
    ROM16X1A LUT4_11 (.AD3(addr10_inv), .AD2(addr11_inv), .AD1(Address[12]), 
        .AD0(addr13_inv), .DO0(dec4_p04));

    defparam LUT4_10.initval =  16'h8000 ;
    ROM16X1A LUT4_10 (.AD3(Address[10]), .AD2(addr11_inv), .AD1(Address[12]), 
        .AD0(addr13_inv), .DO0(dec5_p05));

    defparam LUT4_9.initval =  16'h8000 ;
    ROM16X1A LUT4_9 (.AD3(addr10_inv), .AD2(Address[11]), .AD1(Address[12]), 
        .AD0(addr13_inv), .DO0(dec6_p06));

    defparam LUT4_8.initval =  16'h8000 ;
    ROM16X1A LUT4_8 (.AD3(Address[10]), .AD2(Address[11]), .AD1(Address[12]), 
        .AD0(addr13_inv), .DO0(dec7_p07));

    defparam LUT4_7.initval =  16'h8000 ;
    ROM16X1A LUT4_7 (.AD3(addr10_inv), .AD2(addr11_inv), .AD1(addr12_inv), 
        .AD0(Address[13]), .DO0(dec8_p08));

    defparam LUT4_6.initval =  16'h8000 ;
    ROM16X1A LUT4_6 (.AD3(Address[10]), .AD2(addr11_inv), .AD1(addr12_inv), 
        .AD0(Address[13]), .DO0(dec9_p09));

    defparam LUT4_5.initval =  16'h8000 ;
    ROM16X1A LUT4_5 (.AD3(addr10_inv), .AD2(Address[11]), .AD1(addr12_inv), 
        .AD0(Address[13]), .DO0(dec10_p010));

    defparam LUT4_4.initval =  16'h8000 ;
    ROM16X1A LUT4_4 (.AD3(Address[10]), .AD2(Address[11]), .AD1(addr12_inv), 
        .AD0(Address[13]), .DO0(dec11_p011));

    defparam LUT4_3.initval =  16'h8000 ;
    ROM16X1A LUT4_3 (.AD3(addr10_inv), .AD2(addr11_inv), .AD1(Address[12]), 
        .AD0(Address[13]), .DO0(dec12_p012));

    defparam LUT4_2.initval =  16'h8000 ;
    ROM16X1A LUT4_2 (.AD3(Address[10]), .AD2(addr11_inv), .AD1(Address[12]), 
        .AD0(Address[13]), .DO0(dec13_p013));

    defparam LUT4_1.initval =  16'h8000 ;
    ROM16X1A LUT4_1 (.AD3(addr10_inv), .AD2(Address[11]), .AD1(Address[12]), 
        .AD0(Address[13]), .DO0(dec14_p014));

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(Address[10]), .AD2(Address[11]), .AD1(Address[12]), 
        .AD0(Address[13]), .DO0(dec15_p015));

    INV INV_0 (.A(WE), .Z(wren_inv));

    AND2 AND2_t0 (.A(wren_inv), .B(ClockEn), .Z(wren_inv_g));

    defparam ram_dq_0_0_15.CSDECODE_B = "0b111" ;
    defparam ram_dq_0_0_15.CSDECODE_A = "0b001" ;
    defparam ram_dq_0_0_15.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_0_0_15.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_0_0_15.GSR = "DISABLED" ;
    defparam ram_dq_0_0_15.REGMODE_B = "NOREG" ;
    defparam ram_dq_0_0_15.REGMODE_A = "NOREG" ;
    defparam ram_dq_0_0_15.DATA_WIDTH_B = 18 ;
    defparam ram_dq_0_0_15.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_0_0_15 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec0_p00), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_0_0), .DOA1(mdout0_0_1), .DOA2(mdout0_0_2), .DOA3(mdout0_0_3), 
        .DOA4(mdout0_0_4), .DOA5(mdout0_0_5), .DOA6(mdout0_0_6), .DOA7(mdout0_0_7), 
        .DOA8(mdout0_0_8), .DOA9(mdout0_0_9), .DOA10(mdout0_0_10), .DOA11(mdout0_0_11), 
        .DOA12(mdout0_0_12), .DOA13(mdout0_0_13), .DOA14(mdout0_0_14), .DOA15(mdout0_0_15), 
        .DOA16(mdout0_0_16), .DOA17(mdout0_0_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_1_0_14.CSDECODE_B = "0b111" ;
    defparam ram_dq_1_0_14.CSDECODE_A = "0b001" ;
    defparam ram_dq_1_0_14.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_1_0_14.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_1_0_14.GSR = "DISABLED" ;
    defparam ram_dq_1_0_14.REGMODE_B = "NOREG" ;
    defparam ram_dq_1_0_14.REGMODE_A = "NOREG" ;
    defparam ram_dq_1_0_14.DATA_WIDTH_B = 18 ;
    defparam ram_dq_1_0_14.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_1_0_14 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec1_p01), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_1_0), .DOA1(mdout0_1_1), .DOA2(mdout0_1_2), .DOA3(mdout0_1_3), 
        .DOA4(mdout0_1_4), .DOA5(mdout0_1_5), .DOA6(mdout0_1_6), .DOA7(mdout0_1_7), 
        .DOA8(mdout0_1_8), .DOA9(mdout0_1_9), .DOA10(mdout0_1_10), .DOA11(mdout0_1_11), 
        .DOA12(mdout0_1_12), .DOA13(mdout0_1_13), .DOA14(mdout0_1_14), .DOA15(mdout0_1_15), 
        .DOA16(mdout0_1_16), .DOA17(mdout0_1_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_2_0_13.CSDECODE_B = "0b111" ;
    defparam ram_dq_2_0_13.CSDECODE_A = "0b001" ;
    defparam ram_dq_2_0_13.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_2_0_13.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_2_0_13.GSR = "DISABLED" ;
    defparam ram_dq_2_0_13.REGMODE_B = "NOREG" ;
    defparam ram_dq_2_0_13.REGMODE_A = "NOREG" ;
    defparam ram_dq_2_0_13.DATA_WIDTH_B = 18 ;
    defparam ram_dq_2_0_13.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_2_0_13 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec2_p02), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_2_0), .DOA1(mdout0_2_1), .DOA2(mdout0_2_2), .DOA3(mdout0_2_3), 
        .DOA4(mdout0_2_4), .DOA5(mdout0_2_5), .DOA6(mdout0_2_6), .DOA7(mdout0_2_7), 
        .DOA8(mdout0_2_8), .DOA9(mdout0_2_9), .DOA10(mdout0_2_10), .DOA11(mdout0_2_11), 
        .DOA12(mdout0_2_12), .DOA13(mdout0_2_13), .DOA14(mdout0_2_14), .DOA15(mdout0_2_15), 
        .DOA16(mdout0_2_16), .DOA17(mdout0_2_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_3_0_12.CSDECODE_B = "0b111" ;
    defparam ram_dq_3_0_12.CSDECODE_A = "0b001" ;
    defparam ram_dq_3_0_12.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_3_0_12.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_3_0_12.GSR = "DISABLED" ;
    defparam ram_dq_3_0_12.REGMODE_B = "NOREG" ;
    defparam ram_dq_3_0_12.REGMODE_A = "NOREG" ;
    defparam ram_dq_3_0_12.DATA_WIDTH_B = 18 ;
    defparam ram_dq_3_0_12.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_3_0_12 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec3_p03), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_3_0), .DOA1(mdout0_3_1), .DOA2(mdout0_3_2), .DOA3(mdout0_3_3), 
        .DOA4(mdout0_3_4), .DOA5(mdout0_3_5), .DOA6(mdout0_3_6), .DOA7(mdout0_3_7), 
        .DOA8(mdout0_3_8), .DOA9(mdout0_3_9), .DOA10(mdout0_3_10), .DOA11(mdout0_3_11), 
        .DOA12(mdout0_3_12), .DOA13(mdout0_3_13), .DOA14(mdout0_3_14), .DOA15(mdout0_3_15), 
        .DOA16(mdout0_3_16), .DOA17(mdout0_3_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_4_0_11.CSDECODE_B = "0b111" ;
    defparam ram_dq_4_0_11.CSDECODE_A = "0b001" ;
    defparam ram_dq_4_0_11.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_4_0_11.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_4_0_11.GSR = "DISABLED" ;
    defparam ram_dq_4_0_11.REGMODE_B = "NOREG" ;
    defparam ram_dq_4_0_11.REGMODE_A = "NOREG" ;
    defparam ram_dq_4_0_11.DATA_WIDTH_B = 18 ;
    defparam ram_dq_4_0_11.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_4_0_11 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec4_p04), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_4_0), .DOA1(mdout0_4_1), .DOA2(mdout0_4_2), .DOA3(mdout0_4_3), 
        .DOA4(mdout0_4_4), .DOA5(mdout0_4_5), .DOA6(mdout0_4_6), .DOA7(mdout0_4_7), 
        .DOA8(mdout0_4_8), .DOA9(mdout0_4_9), .DOA10(mdout0_4_10), .DOA11(mdout0_4_11), 
        .DOA12(mdout0_4_12), .DOA13(mdout0_4_13), .DOA14(mdout0_4_14), .DOA15(mdout0_4_15), 
        .DOA16(mdout0_4_16), .DOA17(mdout0_4_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_5_0_10.CSDECODE_B = "0b111" ;
    defparam ram_dq_5_0_10.CSDECODE_A = "0b001" ;
    defparam ram_dq_5_0_10.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_5_0_10.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_5_0_10.GSR = "DISABLED" ;
    defparam ram_dq_5_0_10.REGMODE_B = "NOREG" ;
    defparam ram_dq_5_0_10.REGMODE_A = "NOREG" ;
    defparam ram_dq_5_0_10.DATA_WIDTH_B = 18 ;
    defparam ram_dq_5_0_10.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_5_0_10 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec5_p05), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_5_0), .DOA1(mdout0_5_1), .DOA2(mdout0_5_2), .DOA3(mdout0_5_3), 
        .DOA4(mdout0_5_4), .DOA5(mdout0_5_5), .DOA6(mdout0_5_6), .DOA7(mdout0_5_7), 
        .DOA8(mdout0_5_8), .DOA9(mdout0_5_9), .DOA10(mdout0_5_10), .DOA11(mdout0_5_11), 
        .DOA12(mdout0_5_12), .DOA13(mdout0_5_13), .DOA14(mdout0_5_14), .DOA15(mdout0_5_15), 
        .DOA16(mdout0_5_16), .DOA17(mdout0_5_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_6_0_9.CSDECODE_B = "0b111" ;
    defparam ram_dq_6_0_9.CSDECODE_A = "0b001" ;
    defparam ram_dq_6_0_9.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_6_0_9.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_6_0_9.GSR = "DISABLED" ;
    defparam ram_dq_6_0_9.REGMODE_B = "NOREG" ;
    defparam ram_dq_6_0_9.REGMODE_A = "NOREG" ;
    defparam ram_dq_6_0_9.DATA_WIDTH_B = 18 ;
    defparam ram_dq_6_0_9.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_6_0_9 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec6_p06), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_6_0), .DOA1(mdout0_6_1), .DOA2(mdout0_6_2), .DOA3(mdout0_6_3), 
        .DOA4(mdout0_6_4), .DOA5(mdout0_6_5), .DOA6(mdout0_6_6), .DOA7(mdout0_6_7), 
        .DOA8(mdout0_6_8), .DOA9(mdout0_6_9), .DOA10(mdout0_6_10), .DOA11(mdout0_6_11), 
        .DOA12(mdout0_6_12), .DOA13(mdout0_6_13), .DOA14(mdout0_6_14), .DOA15(mdout0_6_15), 
        .DOA16(mdout0_6_16), .DOA17(mdout0_6_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_7_0_8.CSDECODE_B = "0b111" ;
    defparam ram_dq_7_0_8.CSDECODE_A = "0b001" ;
    defparam ram_dq_7_0_8.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_7_0_8.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_7_0_8.GSR = "DISABLED" ;
    defparam ram_dq_7_0_8.REGMODE_B = "NOREG" ;
    defparam ram_dq_7_0_8.REGMODE_A = "NOREG" ;
    defparam ram_dq_7_0_8.DATA_WIDTH_B = 18 ;
    defparam ram_dq_7_0_8.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_7_0_8 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec7_p07), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_7_0), .DOA1(mdout0_7_1), .DOA2(mdout0_7_2), .DOA3(mdout0_7_3), 
        .DOA4(mdout0_7_4), .DOA5(mdout0_7_5), .DOA6(mdout0_7_6), .DOA7(mdout0_7_7), 
        .DOA8(mdout0_7_8), .DOA9(mdout0_7_9), .DOA10(mdout0_7_10), .DOA11(mdout0_7_11), 
        .DOA12(mdout0_7_12), .DOA13(mdout0_7_13), .DOA14(mdout0_7_14), .DOA15(mdout0_7_15), 
        .DOA16(mdout0_7_16), .DOA17(mdout0_7_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_8_0_7.CSDECODE_B = "0b111" ;
    defparam ram_dq_8_0_7.CSDECODE_A = "0b001" ;
    defparam ram_dq_8_0_7.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_8_0_7.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_8_0_7.GSR = "DISABLED" ;
    defparam ram_dq_8_0_7.REGMODE_B = "NOREG" ;
    defparam ram_dq_8_0_7.REGMODE_A = "NOREG" ;
    defparam ram_dq_8_0_7.DATA_WIDTH_B = 18 ;
    defparam ram_dq_8_0_7.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_8_0_7 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec8_p08), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_8_0), .DOA1(mdout0_8_1), .DOA2(mdout0_8_2), .DOA3(mdout0_8_3), 
        .DOA4(mdout0_8_4), .DOA5(mdout0_8_5), .DOA6(mdout0_8_6), .DOA7(mdout0_8_7), 
        .DOA8(mdout0_8_8), .DOA9(mdout0_8_9), .DOA10(mdout0_8_10), .DOA11(mdout0_8_11), 
        .DOA12(mdout0_8_12), .DOA13(mdout0_8_13), .DOA14(mdout0_8_14), .DOA15(mdout0_8_15), 
        .DOA16(mdout0_8_16), .DOA17(mdout0_8_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_9_0_6.CSDECODE_B = "0b111" ;
    defparam ram_dq_9_0_6.CSDECODE_A = "0b001" ;
    defparam ram_dq_9_0_6.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_9_0_6.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_9_0_6.GSR = "DISABLED" ;
    defparam ram_dq_9_0_6.REGMODE_B = "NOREG" ;
    defparam ram_dq_9_0_6.REGMODE_A = "NOREG" ;
    defparam ram_dq_9_0_6.DATA_WIDTH_B = 18 ;
    defparam ram_dq_9_0_6.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_9_0_6 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec9_p09), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), .WEB(scuba_vlo), 
        .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(scuba_vlo), 
        .DOA0(mdout0_9_0), .DOA1(mdout0_9_1), .DOA2(mdout0_9_2), .DOA3(mdout0_9_3), 
        .DOA4(mdout0_9_4), .DOA5(mdout0_9_5), .DOA6(mdout0_9_6), .DOA7(mdout0_9_7), 
        .DOA8(mdout0_9_8), .DOA9(mdout0_9_9), .DOA10(mdout0_9_10), .DOA11(mdout0_9_11), 
        .DOA12(mdout0_9_12), .DOA13(mdout0_9_13), .DOA14(mdout0_9_14), .DOA15(mdout0_9_15), 
        .DOA16(mdout0_9_16), .DOA17(mdout0_9_17), .DOB0(), .DOB1(), .DOB2(), 
        .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), 
        .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_10_0_5.CSDECODE_B = "0b111" ;
    defparam ram_dq_10_0_5.CSDECODE_A = "0b001" ;
    defparam ram_dq_10_0_5.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_10_0_5.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_10_0_5.GSR = "DISABLED" ;
    defparam ram_dq_10_0_5.REGMODE_B = "NOREG" ;
    defparam ram_dq_10_0_5.REGMODE_A = "NOREG" ;
    defparam ram_dq_10_0_5.DATA_WIDTH_B = 18 ;
    defparam ram_dq_10_0_5.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_10_0_5 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec10_p010), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(mdout0_10_0), .DOA1(mdout0_10_1), .DOA2(mdout0_10_2), 
        .DOA3(mdout0_10_3), .DOA4(mdout0_10_4), .DOA5(mdout0_10_5), .DOA6(mdout0_10_6), 
        .DOA7(mdout0_10_7), .DOA8(mdout0_10_8), .DOA9(mdout0_10_9), .DOA10(mdout0_10_10), 
        .DOA11(mdout0_10_11), .DOA12(mdout0_10_12), .DOA13(mdout0_10_13), 
        .DOA14(mdout0_10_14), .DOA15(mdout0_10_15), .DOA16(mdout0_10_16), 
        .DOA17(mdout0_10_17), .DOB0(), .DOB1(), .DOB2(), .DOB3(), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_11_0_4.CSDECODE_B = "0b111" ;
    defparam ram_dq_11_0_4.CSDECODE_A = "0b001" ;
    defparam ram_dq_11_0_4.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_11_0_4.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_11_0_4.GSR = "DISABLED" ;
    defparam ram_dq_11_0_4.REGMODE_B = "NOREG" ;
    defparam ram_dq_11_0_4.REGMODE_A = "NOREG" ;
    defparam ram_dq_11_0_4.DATA_WIDTH_B = 18 ;
    defparam ram_dq_11_0_4.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_11_0_4 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec11_p011), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(mdout0_11_0), .DOA1(mdout0_11_1), .DOA2(mdout0_11_2), 
        .DOA3(mdout0_11_3), .DOA4(mdout0_11_4), .DOA5(mdout0_11_5), .DOA6(mdout0_11_6), 
        .DOA7(mdout0_11_7), .DOA8(mdout0_11_8), .DOA9(mdout0_11_9), .DOA10(mdout0_11_10), 
        .DOA11(mdout0_11_11), .DOA12(mdout0_11_12), .DOA13(mdout0_11_13), 
        .DOA14(mdout0_11_14), .DOA15(mdout0_11_15), .DOA16(mdout0_11_16), 
        .DOA17(mdout0_11_17), .DOB0(), .DOB1(), .DOB2(), .DOB3(), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_12_0_3.CSDECODE_B = "0b111" ;
    defparam ram_dq_12_0_3.CSDECODE_A = "0b001" ;
    defparam ram_dq_12_0_3.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_12_0_3.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_12_0_3.GSR = "DISABLED" ;
    defparam ram_dq_12_0_3.REGMODE_B = "NOREG" ;
    defparam ram_dq_12_0_3.REGMODE_A = "NOREG" ;
    defparam ram_dq_12_0_3.DATA_WIDTH_B = 18 ;
    defparam ram_dq_12_0_3.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_12_0_3 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec12_p012), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(mdout0_12_0), .DOA1(mdout0_12_1), .DOA2(mdout0_12_2), 
        .DOA3(mdout0_12_3), .DOA4(mdout0_12_4), .DOA5(mdout0_12_5), .DOA6(mdout0_12_6), 
        .DOA7(mdout0_12_7), .DOA8(mdout0_12_8), .DOA9(mdout0_12_9), .DOA10(mdout0_12_10), 
        .DOA11(mdout0_12_11), .DOA12(mdout0_12_12), .DOA13(mdout0_12_13), 
        .DOA14(mdout0_12_14), .DOA15(mdout0_12_15), .DOA16(mdout0_12_16), 
        .DOA17(mdout0_12_17), .DOB0(), .DOB1(), .DOB2(), .DOB3(), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_13_0_2.CSDECODE_B = "0b111" ;
    defparam ram_dq_13_0_2.CSDECODE_A = "0b001" ;
    defparam ram_dq_13_0_2.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_13_0_2.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_13_0_2.GSR = "DISABLED" ;
    defparam ram_dq_13_0_2.REGMODE_B = "NOREG" ;
    defparam ram_dq_13_0_2.REGMODE_A = "NOREG" ;
    defparam ram_dq_13_0_2.DATA_WIDTH_B = 18 ;
    defparam ram_dq_13_0_2.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_13_0_2 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec13_p013), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(mdout0_13_0), .DOA1(mdout0_13_1), .DOA2(mdout0_13_2), 
        .DOA3(mdout0_13_3), .DOA4(mdout0_13_4), .DOA5(mdout0_13_5), .DOA6(mdout0_13_6), 
        .DOA7(mdout0_13_7), .DOA8(mdout0_13_8), .DOA9(mdout0_13_9), .DOA10(mdout0_13_10), 
        .DOA11(mdout0_13_11), .DOA12(mdout0_13_12), .DOA13(mdout0_13_13), 
        .DOA14(mdout0_13_14), .DOA15(mdout0_13_15), .DOA16(mdout0_13_16), 
        .DOA17(mdout0_13_17), .DOB0(), .DOB1(), .DOB2(), .DOB3(), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    defparam ram_dq_14_0_1.CSDECODE_B = "0b111" ;
    defparam ram_dq_14_0_1.CSDECODE_A = "0b001" ;
    defparam ram_dq_14_0_1.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_14_0_1.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_14_0_1.GSR = "DISABLED" ;
    defparam ram_dq_14_0_1.REGMODE_B = "NOREG" ;
    defparam ram_dq_14_0_1.REGMODE_A = "NOREG" ;
    defparam ram_dq_14_0_1.DATA_WIDTH_B = 18 ;
    defparam ram_dq_14_0_1.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_14_0_1 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec14_p014), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(mdout0_14_0), .DOA1(mdout0_14_1), .DOA2(mdout0_14_2), 
        .DOA3(mdout0_14_3), .DOA4(mdout0_14_4), .DOA5(mdout0_14_5), .DOA6(mdout0_14_6), 
        .DOA7(mdout0_14_7), .DOA8(mdout0_14_8), .DOA9(mdout0_14_9), .DOA10(mdout0_14_10), 
        .DOA11(mdout0_14_11), .DOA12(mdout0_14_12), .DOA13(mdout0_14_13), 
        .DOA14(mdout0_14_14), .DOA15(mdout0_14_15), .DOA16(mdout0_14_16), 
        .DOA17(mdout0_14_17), .DOB0(), .DOB1(), .DOB2(), .DOB3(), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam ram_dq_15_0_0.CSDECODE_B = "0b111" ;
    defparam ram_dq_15_0_0.CSDECODE_A = "0b001" ;
    defparam ram_dq_15_0_0.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_15_0_0.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_15_0_0.GSR = "DISABLED" ;
    defparam ram_dq_15_0_0.REGMODE_B = "NOREG" ;
    defparam ram_dq_15_0_0.REGMODE_A = "NOREG" ;
    defparam ram_dq_15_0_0.DATA_WIDTH_B = 18 ;
    defparam ram_dq_15_0_0.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_15_0_0 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(scuba_vlo), .DIA9(Data[8]), .DIA10(Data[9]), 
        .DIA11(Data[10]), .DIA12(Data[11]), .DIA13(Data[12]), .DIA14(Data[13]), 
        .DIA15(Data[14]), .DIA16(Data[15]), .DIA17(scuba_vlo), .ADA0(ByteEn[0]), 
        .ADA1(ByteEn[1]), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(Address[9]), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(dec15_p015), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(mdout0_15_0), .DOA1(mdout0_15_1), .DOA2(mdout0_15_2), 
        .DOA3(mdout0_15_3), .DOA4(mdout0_15_4), .DOA5(mdout0_15_5), .DOA6(mdout0_15_6), 
        .DOA7(mdout0_15_7), .DOA8(mdout0_15_8), .DOA9(mdout0_15_9), .DOA10(mdout0_15_10), 
        .DOA11(mdout0_15_11), .DOA12(mdout0_15_12), .DOA13(mdout0_15_13), 
        .DOA14(mdout0_15_14), .DOA15(mdout0_15_15), .DOA16(mdout0_15_16), 
        .DOA17(mdout0_15_17), .DOB0(), .DOB1(), .DOB2(), .DOB3(), .DOB4(), 
        .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), .DOB10(), .DOB11(), 
        .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    FD1P3DX FF_3 (.D(Address[10]), .SP(wren_inv_g), .CK(Clock), .CD(scuba_vlo), 
        .Q(addr10_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(Address[11]), .SP(wren_inv_g), .CK(Clock), .CD(scuba_vlo), 
        .Q(addr11_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(Address[12]), .SP(wren_inv_g), .CK(Clock), .CD(scuba_vlo), 
        .Q(addr12_ff))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FD1P3DX FF_0 (.D(Address[13]), .SP(wren_inv_g), .CK(Clock), .CD(scuba_vlo), 
        .Q(addr13_ff))
             /* synthesis GSR="ENABLED" */;

    MUX161 mux_15 (.D0(mdout0_0_0), .D1(mdout0_1_0), .D2(mdout0_2_0), .D3(mdout0_3_0), 
        .D4(mdout0_4_0), .D5(mdout0_5_0), .D6(mdout0_6_0), .D7(mdout0_7_0), 
        .D8(mdout0_8_0), .D9(mdout0_9_0), .D10(mdout0_10_0), .D11(mdout0_11_0), 
        .D12(mdout0_12_0), .D13(mdout0_13_0), .D14(mdout0_14_0), .D15(mdout0_15_0), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[0]));

    MUX161 mux_14 (.D0(mdout0_0_1), .D1(mdout0_1_1), .D2(mdout0_2_1), .D3(mdout0_3_1), 
        .D4(mdout0_4_1), .D5(mdout0_5_1), .D6(mdout0_6_1), .D7(mdout0_7_1), 
        .D8(mdout0_8_1), .D9(mdout0_9_1), .D10(mdout0_10_1), .D11(mdout0_11_1), 
        .D12(mdout0_12_1), .D13(mdout0_13_1), .D14(mdout0_14_1), .D15(mdout0_15_1), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[1]));

    MUX161 mux_13 (.D0(mdout0_0_2), .D1(mdout0_1_2), .D2(mdout0_2_2), .D3(mdout0_3_2), 
        .D4(mdout0_4_2), .D5(mdout0_5_2), .D6(mdout0_6_2), .D7(mdout0_7_2), 
        .D8(mdout0_8_2), .D9(mdout0_9_2), .D10(mdout0_10_2), .D11(mdout0_11_2), 
        .D12(mdout0_12_2), .D13(mdout0_13_2), .D14(mdout0_14_2), .D15(mdout0_15_2), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[2]));

    MUX161 mux_12 (.D0(mdout0_0_3), .D1(mdout0_1_3), .D2(mdout0_2_3), .D3(mdout0_3_3), 
        .D4(mdout0_4_3), .D5(mdout0_5_3), .D6(mdout0_6_3), .D7(mdout0_7_3), 
        .D8(mdout0_8_3), .D9(mdout0_9_3), .D10(mdout0_10_3), .D11(mdout0_11_3), 
        .D12(mdout0_12_3), .D13(mdout0_13_3), .D14(mdout0_14_3), .D15(mdout0_15_3), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[3]));

    MUX161 mux_11 (.D0(mdout0_0_4), .D1(mdout0_1_4), .D2(mdout0_2_4), .D3(mdout0_3_4), 
        .D4(mdout0_4_4), .D5(mdout0_5_4), .D6(mdout0_6_4), .D7(mdout0_7_4), 
        .D8(mdout0_8_4), .D9(mdout0_9_4), .D10(mdout0_10_4), .D11(mdout0_11_4), 
        .D12(mdout0_12_4), .D13(mdout0_13_4), .D14(mdout0_14_4), .D15(mdout0_15_4), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[4]));

    MUX161 mux_10 (.D0(mdout0_0_5), .D1(mdout0_1_5), .D2(mdout0_2_5), .D3(mdout0_3_5), 
        .D4(mdout0_4_5), .D5(mdout0_5_5), .D6(mdout0_6_5), .D7(mdout0_7_5), 
        .D8(mdout0_8_5), .D9(mdout0_9_5), .D10(mdout0_10_5), .D11(mdout0_11_5), 
        .D12(mdout0_12_5), .D13(mdout0_13_5), .D14(mdout0_14_5), .D15(mdout0_15_5), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[5]));

    MUX161 mux_9 (.D0(mdout0_0_6), .D1(mdout0_1_6), .D2(mdout0_2_6), .D3(mdout0_3_6), 
        .D4(mdout0_4_6), .D5(mdout0_5_6), .D6(mdout0_6_6), .D7(mdout0_7_6), 
        .D8(mdout0_8_6), .D9(mdout0_9_6), .D10(mdout0_10_6), .D11(mdout0_11_6), 
        .D12(mdout0_12_6), .D13(mdout0_13_6), .D14(mdout0_14_6), .D15(mdout0_15_6), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[6]));

    MUX161 mux_8 (.D0(mdout0_0_7), .D1(mdout0_1_7), .D2(mdout0_2_7), .D3(mdout0_3_7), 
        .D4(mdout0_4_7), .D5(mdout0_5_7), .D6(mdout0_6_7), .D7(mdout0_7_7), 
        .D8(mdout0_8_7), .D9(mdout0_9_7), .D10(mdout0_10_7), .D11(mdout0_11_7), 
        .D12(mdout0_12_7), .D13(mdout0_13_7), .D14(mdout0_14_7), .D15(mdout0_15_7), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[7]));

    MUX161 mux_7 (.D0(mdout0_0_9), .D1(mdout0_1_9), .D2(mdout0_2_9), .D3(mdout0_3_9), 
        .D4(mdout0_4_9), .D5(mdout0_5_9), .D6(mdout0_6_9), .D7(mdout0_7_9), 
        .D8(mdout0_8_9), .D9(mdout0_9_9), .D10(mdout0_10_9), .D11(mdout0_11_9), 
        .D12(mdout0_12_9), .D13(mdout0_13_9), .D14(mdout0_14_9), .D15(mdout0_15_9), 
        .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), .SD4(addr13_ff), 
        .Z(Q[8]));

    MUX161 mux_6 (.D0(mdout0_0_10), .D1(mdout0_1_10), .D2(mdout0_2_10), 
        .D3(mdout0_3_10), .D4(mdout0_4_10), .D5(mdout0_5_10), .D6(mdout0_6_10), 
        .D7(mdout0_7_10), .D8(mdout0_8_10), .D9(mdout0_9_10), .D10(mdout0_10_10), 
        .D11(mdout0_11_10), .D12(mdout0_12_10), .D13(mdout0_13_10), .D14(mdout0_14_10), 
        .D15(mdout0_15_10), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[9]));

    MUX161 mux_5 (.D0(mdout0_0_11), .D1(mdout0_1_11), .D2(mdout0_2_11), 
        .D3(mdout0_3_11), .D4(mdout0_4_11), .D5(mdout0_5_11), .D6(mdout0_6_11), 
        .D7(mdout0_7_11), .D8(mdout0_8_11), .D9(mdout0_9_11), .D10(mdout0_10_11), 
        .D11(mdout0_11_11), .D12(mdout0_12_11), .D13(mdout0_13_11), .D14(mdout0_14_11), 
        .D15(mdout0_15_11), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[10]));

    MUX161 mux_4 (.D0(mdout0_0_12), .D1(mdout0_1_12), .D2(mdout0_2_12), 
        .D3(mdout0_3_12), .D4(mdout0_4_12), .D5(mdout0_5_12), .D6(mdout0_6_12), 
        .D7(mdout0_7_12), .D8(mdout0_8_12), .D9(mdout0_9_12), .D10(mdout0_10_12), 
        .D11(mdout0_11_12), .D12(mdout0_12_12), .D13(mdout0_13_12), .D14(mdout0_14_12), 
        .D15(mdout0_15_12), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[11]));

    MUX161 mux_3 (.D0(mdout0_0_13), .D1(mdout0_1_13), .D2(mdout0_2_13), 
        .D3(mdout0_3_13), .D4(mdout0_4_13), .D5(mdout0_5_13), .D6(mdout0_6_13), 
        .D7(mdout0_7_13), .D8(mdout0_8_13), .D9(mdout0_9_13), .D10(mdout0_10_13), 
        .D11(mdout0_11_13), .D12(mdout0_12_13), .D13(mdout0_13_13), .D14(mdout0_14_13), 
        .D15(mdout0_15_13), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[12]));

    MUX161 mux_2 (.D0(mdout0_0_14), .D1(mdout0_1_14), .D2(mdout0_2_14), 
        .D3(mdout0_3_14), .D4(mdout0_4_14), .D5(mdout0_5_14), .D6(mdout0_6_14), 
        .D7(mdout0_7_14), .D8(mdout0_8_14), .D9(mdout0_9_14), .D10(mdout0_10_14), 
        .D11(mdout0_11_14), .D12(mdout0_12_14), .D13(mdout0_13_14), .D14(mdout0_14_14), 
        .D15(mdout0_15_14), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[13]));

    MUX161 mux_1 (.D0(mdout0_0_15), .D1(mdout0_1_15), .D2(mdout0_2_15), 
        .D3(mdout0_3_15), .D4(mdout0_4_15), .D5(mdout0_5_15), .D6(mdout0_6_15), 
        .D7(mdout0_7_15), .D8(mdout0_8_15), .D9(mdout0_9_15), .D10(mdout0_10_15), 
        .D11(mdout0_11_15), .D12(mdout0_12_15), .D13(mdout0_13_15), .D14(mdout0_14_15), 
        .D15(mdout0_15_15), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[14]));

    MUX161 mux_0 (.D0(mdout0_0_16), .D1(mdout0_1_16), .D2(mdout0_2_16), 
        .D3(mdout0_3_16), .D4(mdout0_4_16), .D5(mdout0_5_16), .D6(mdout0_6_16), 
        .D7(mdout0_7_16), .D8(mdout0_8_16), .D9(mdout0_9_16), .D10(mdout0_10_16), 
        .D11(mdout0_11_16), .D12(mdout0_12_16), .D13(mdout0_13_16), .D14(mdout0_14_16), 
        .D15(mdout0_15_16), .SD1(addr10_ff), .SD2(addr11_ff), .SD3(addr12_ff), 
        .SD4(addr13_ff), .Z(Q[15]));



    // exemplar begin
    // exemplar attribute ram_dq_0_0_15 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_0_0_15 MEM_INIT_FILE 
    // exemplar attribute ram_dq_0_0_15 RESETMODE SYNC
    // exemplar attribute ram_dq_1_0_14 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_1_0_14 MEM_INIT_FILE 
    // exemplar attribute ram_dq_1_0_14 RESETMODE SYNC
    // exemplar attribute ram_dq_2_0_13 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_2_0_13 MEM_INIT_FILE 
    // exemplar attribute ram_dq_2_0_13 RESETMODE SYNC
    // exemplar attribute ram_dq_3_0_12 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_3_0_12 MEM_INIT_FILE 
    // exemplar attribute ram_dq_3_0_12 RESETMODE SYNC
    // exemplar attribute ram_dq_4_0_11 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_4_0_11 MEM_INIT_FILE 
    // exemplar attribute ram_dq_4_0_11 RESETMODE SYNC
    // exemplar attribute ram_dq_5_0_10 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_5_0_10 MEM_INIT_FILE 
    // exemplar attribute ram_dq_5_0_10 RESETMODE SYNC
    // exemplar attribute ram_dq_6_0_9 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_6_0_9 MEM_INIT_FILE 
    // exemplar attribute ram_dq_6_0_9 RESETMODE SYNC
    // exemplar attribute ram_dq_7_0_8 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_7_0_8 MEM_INIT_FILE 
    // exemplar attribute ram_dq_7_0_8 RESETMODE SYNC
    // exemplar attribute ram_dq_8_0_7 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_8_0_7 MEM_INIT_FILE 
    // exemplar attribute ram_dq_8_0_7 RESETMODE SYNC
    // exemplar attribute ram_dq_9_0_6 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_9_0_6 MEM_INIT_FILE 
    // exemplar attribute ram_dq_9_0_6 RESETMODE SYNC
    // exemplar attribute ram_dq_10_0_5 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_10_0_5 MEM_INIT_FILE 
    // exemplar attribute ram_dq_10_0_5 RESETMODE SYNC
    // exemplar attribute ram_dq_11_0_4 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_11_0_4 MEM_INIT_FILE 
    // exemplar attribute ram_dq_11_0_4 RESETMODE SYNC
    // exemplar attribute ram_dq_12_0_3 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_12_0_3 MEM_INIT_FILE 
    // exemplar attribute ram_dq_12_0_3 RESETMODE SYNC
    // exemplar attribute ram_dq_13_0_2 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_13_0_2 MEM_INIT_FILE 
    // exemplar attribute ram_dq_13_0_2 RESETMODE SYNC
    // exemplar attribute ram_dq_14_0_1 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_14_0_1 MEM_INIT_FILE 
    // exemplar attribute ram_dq_14_0_1 RESETMODE SYNC
    // exemplar attribute ram_dq_15_0_0 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_15_0_0 MEM_INIT_FILE 
    // exemplar attribute ram_dq_15_0_0 RESETMODE SYNC
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
